### ISSUE TITLE
Calling .setup with a different configuration causes "Duplicate Analytics client" error

### ISSUE THREAD

**Issue by jhiesey** [segmentio/analytics-react-native#104]
We are using CodePush to update our app, and if we change the Segment config we get `Error: Duplicate Analytics client`.

I think this is because there is currently no way to recreate the singleton `sharedAnalytics` object. I see that the fix for #16 avoids this problem when the config is the same, but that doesn't help if the config changes.

Is there a way to reset the singleton? Or if not, is there a way to detect this other than catching the error?

**Comment by jhiesey** [comment]
We are seeing this error on v1.0.1 on iOS

**Comment by rlopezapplaudo** [comment]
Hi can yo verify with pr should be fixed
https://github.com/segmentio/analytics-react-native/commit/28a981dba2416461ba617ab16e40c4b1eece694d

**Comment by bsneed** [comment]
Closing due to age.  Also, we don't have a way to re-init the singleton.  Future changes will include moving away from the singleton model.
