### ISSUE TITLE
"EX" (EXViewController ) screen always being recorded

### ISSUE THREAD

**Issue by GioLogist** [segmentio/analytics-react-native#105]
We have an app that uses Expokit (detached).

About 70% of our screen analytics are coming from an "EX" (EXViewController) screen. Are there any workarounds? It really clouds our analytics, as it skews our numbers severely 😬

![Screenshot 2019-09-12 14 10 30](https://user-images.githubusercontent.com/4120754/64821365-8880c900-d567-11e9-9cb2-da6c39caf915.png)

**Comment by bsneed** [comment]
Your best bet is to record screen views manually.  Automatic screen recording is for platforms, and react-native throws a layer on top that isn't as predictable.
