### ISSUE TITLE
Upgrading Braze SDK `react-native-appboy-sdk` to 1.17.0 breaks @segment/analytics-react-native-appboy

### ISSUE THREAD

**Issue by coderjonny** [segmentio/analytics-react-native#106]
Hello, 

We are using a Segment integration for Blaze with the package `@segment/analytics-react-native-appboy@1.0.1` 

After upgrading our project to use `react-native-appboy-sdk` to 1.17.0, it now seems Segment's integration won't work anymore.

Also tried updating integration to `@segment/analytics-react-native-appboy@^1.1.0-beta.1`, but doesn't work.

<img width="1178" alt="Screen Shot 2019-09-13 at 9 37 13 AM" src="https://user-images.githubusercontent.com/753091/64879690-5c1e8880-d60b-11e9-8b6b-8f2e47b6b623.png">

Also it might have to do with this Note in Braze's docs:
![Screen Shot 2019-09-12 at 5 36 45 PM](https://user-images.githubusercontent.com/753091/64879719-6a6ca480-d60b-11e9-937e-cd11f51065b1.png)
https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/initial_sdk_setup/cocoapods/#step-5-specify-your-custom-endpoint-or-data-cluster

After uninstalling `@segment/analytics-react-native-appboy@1.0.1` the project builds fine with the updated SDK, but we need the segment integration. 

Any solution would be helpful thank you!

**Comment by bsneed** [comment]
Fixed in #169. Release coming later today.

**Comment by bsneed** [comment]
Closed erroneously.  Will look at this before release is made.

**Comment by bsneed** [comment]
Please reopen if this is an issue still.  Closing due to age.
