### ISSUE TITLE
'@segment/analytics-react-native-mixpanel issue with RN 0.60

### ISSUE THREAD

**Issue by iamchathu** [segmentio/analytics-react-native#108]
After installing the mixpanel device destination mode plugin

I get build failed with error

```
* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
The following dependencies do not satisfy the required version:
project ':@segment_analytics-react-native-mixpanel' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.0
```

**Comment by cristeahub** [comment]
Fixed by https://github.com/segmentio/analytics-react-native/commit/3f4e3cc9c9a5d0008c466cbe33a192fcb8e3e01b in 1.1.0-beta2

**Comment by luskin** [comment]
I am receiving this error on iOS: `Error: Failed to load Mixpanel integration native module`

**Comment by MoeMamdouh** [comment]
after update i found this issue: 

```
* What went wrong:
Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> More than one file was found with OS independent path 'META-INF/-no-jdk.kotlin_module'
```

**Comment by justinairbase** [comment]
I'm getting this error now:
```* What went wrong:
Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> More than one file was found with OS independent path 
'META-INF/segment_analytics-react-native_debug.kotlin_module'

**Comment by justinairbase** [comment]
> I'm getting this error now:
> 
> ```
> * What went wrong:
> Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> > More than one file was found with OS independent path 
> 'META-INF/segment_analytics-react-native_debug.kotlin_module'
> ```
> 
> react-native: 0.61.2
> @segment/analytics-react-native: ^1.1.0

Adding this to `android/app/build.gradle` fixed the issue for now.
```
android {
    ...
   packagingOptions {
        exclude 'META-INF/segment_analytics-react-native_debug.kotlin_module'
        exclude 'META-INF/segment_analytics-react-native_release.kotlin_module'
    }
    ....
}

```

**Comment by tobiasbu** [comment]
I don't know if it's related, but a few days ago I started getting the following error during release build:

```
> Task :segment_analytics-react-native:compileReleaseKotlin FAILED
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':segment_analytics-react-native:compileReleaseKotlin'.
```

**Comment by jbolotin** [comment]
+1 on the issue @tobiasbu is having. This just started occurring for me today on appcenter builds with no related changes in my codebase

**Comment by jbolotin** [comment]
@tobiasbu see https://github.com/segmentio/analytics-react-native/issues/225

**Comment by bsneed** [comment]
Seems to be resolved.
