### ISSUE TITLE
RNAnalytics.screen was called with 3 arguments but expects 4 arguments

### ISSUE THREAD

**Issue by thepost** [segmentio/analytics-react-native#113]
After upgrading to React Native 0.60.5 with analytics-react-native 1.1.0-beta.2, I'm getting the following error when using the `screen` method:

`RNAnalytics.screen was called with 3 arguments but expects 4 arguments.`

I'm passing 2 parameters into screen, but type definition only seems to have 3, and 2 of them can be optional or undefined:

`analytics.screen(screenName, params);`

<img width="722" alt="Screen Shot 2019-09-25 at 11 25 45 AM" src="https://user-images.githubusercontent.com/2742942/65615454-5d46a280-df87-11e9-8157-a0c640ce7472.png">

What am I missing here?

**Comment by bsneed** [comment]
if this is still an issue, please reopen.

**Comment by pbassut** [comment]
I have the same happening but with the identify call.

**Comment by bsneed** [comment]
Please provide more information @pbassut

**Comment by pbassut** [comment]
https://github.com/segmentio/analytics-react-native/commit/b90fb4fe08f275438a02b1383ae07d3563787374
Looks like a new argument was introduced here.

The call stack I'm getting is:

```
com.facebook.react.bridge.NativeArgumentsParseException: RNAnalytics.identify got 5 arguments, expected 4
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:349)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java:-2)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:237)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by pbassut** [comment]
Downgrading to 1.3.2 works.
You don't think this is a general issue with the library?

By sending a support ticket we're assuming I'm having trouble implementing it. If so, is there room for it since the issue is in native code?

**Comment by alanjcharles** [comment]
@pbassut I am able to send identify events on 1.4.3 with Android. For example: 

`analytics.identify('brandon', null, { anonymousId: '0123456789' }, {}, {});`

` analytics.identify('brandon', null, { anonymousId: '0123456789' });`

Both work for me. We can definitely take a closer look on the support team, but we have not been able to replicate your issue so far so we can't say it's a bug at the moment. Either way, support will be the most efficient way to move forward.

**Comment by pbassut** [comment]
Ok. That was caused by a codepush.
"Binary" library version was on and bundle version was another(which didn't account for the extra parameter being introduced). So npm updated the bundle(because of the caret ^ in the version) and the binary was not upgraded.

**Comment by abumalick** [comment]
We got an error similar to this when passing an event object as property of the track method

```
RNanalytics.track got 1 argument expected 4
```

```
analytics.track("Event name", { data: eventFromHandler })
```
