### ISSUE TITLE
Android build with amplitude fails because of jitpack

### ISSUE THREAD

**Issue by deorukhkarchaitanya** [segmentio/analytics-react-native#114]
Android build fails with the following error:

<img width="1541" alt="Screenshot 2019-09-25 at 6 10 05 PM" src="https://user-images.githubusercontent.com/24487274/65663321-12df2780-e054-11e9-9bcd-90fd76d68509.png">

**Comment by amit-prabhakar** [comment]
Any update on this?

**Comment by deorukhkarchaitanya** [comment]
> Any update on this?

Yes, sorry. Should've updated this. In your ```android/build.gradle``` change the jitpack URL from 

```
maven {
            url "https://jitpack.io"
      }
```

to

```
maven {
            url "https://www.jitpack.io"
      }
```
