### ISSUE TITLE
Allow for Kotlin version to to be defined externally

### ISSUE THREAD

**Issue by kristfal** [segmentio/analytics-react-native#118]
Hey,

across all segment packages, it would be super if we could externally declare Kotlin version in case we need specific versions for other packages. 

To enable this, you'd need to add the following lines in `build.gradle`:

```gradle
def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

def defaultKotlinVersion = '1.3.21'
def appliedKotlinVersion = safeExtGet('googlePlayServicesVisionVersion', safeExtGet('kotlinVersion', defaultKotlinVersion))

// Where dependencies a declared
classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:${appliedKotlinVersion}'
```

For consumers of this plugin, you can then do:

```gradle
buildscript {
  ext.kotlinVersion = '1.3.50'
}
```

in `android/build.gradle` to override the default kotlin version.

**Comment by bsneed** [comment]
This has been done afaik.  Closing, please reopen if necessary.

**Comment by JayFeldman12** [comment]
This is done on the main repo, but on the segment_analytics-react-native-mixpanel repo, it's still hardcoded as 1.3.21, which is lower than the default minimum version of 1.3.40 in RN 0.69. It would be great if this same solution could be applied to this repo! That build.gradle even defines that safeExtGet method, it just doesn't use it for Kotlin version.
