### ISSUE TITLE
How to pass custom data?

### ISSUE THREAD

**Issue by jinxac** [segmentio/analytics-react-native#119]
I am currently using [analytics-react-native](https://github.com/neiker/analytics-react-native) library and able to pass custom data to track. 

Please look at the following example:-

```
analytics.track({
  userId: user.id,  -> custom data
  event: 'Item Purchased',
  properties: {
    revenue: 39.95,
    shippingMethod: '2-day'
  }
})
```

However, there is no option in this library to pass custom data. All the data is passed in properties as an object. Please look below for an example

```
analytics.track({
  event: 'Item Purchased',
  properties: {
    revenue: 39.95,
     userId: user.id,  -> custom data
    shippingMethod: '2-day'
  }
})
```

Can someone please help?

**Comment by rlopezapplaudo** [comment]
Currently is available 'track' where you can perform action fill up the example on issue link.
Types available: 
boolean | number | string | null | JsonList | JsonMap

**Comment by rlopezapplaudo** [comment]
@jinxac 
Here you have an example 

_Supposing that you user object is like this_
```
  let user = { 
    id: 4234987,
    email: 'user@mail.com',
    address: { 
      street: 'street name',
      city: 'city name'
    }
  }
```

- Examples

1.  **Specific properties**
```
  analytics
  .track('event_name', { 
    revenue: 39.95, 
    userId: user.id, 
    shippingMethod: 3,
    address: user.address.street
  })
```

2. **Full object**

```
  analytics
  .track('event_name',{ 
    revenue: 39.95, 
    userDetails: user, 
    shippingMethod: 3,
  })
```

This could be customizable as you want
@bsneed @lubird

**Comment by bsneed** [comment]
Closing due to age and appearing to be answered.
