### ISSUE TITLE
iOS crash on release builds

### ISSUE THREAD

**Issue by jinxac** [segmentio/analytics-react-native#121]
I am getting [this](https://stackoverflow.com/questions/45156396/0x8badf00d-in-react-native-ios) error after calling `Analytics.initialize()` on iOS release builds.

Looks like there is something wrong with `analytics-react-native-firebase` package. It works fine on android and iOS development but iOS release build hangs. If I comment out firebase package here it works perfectly fine.

```
const WealthyAnalytics = {
  initialize: () => {
    Analytics
      .setup(analyticsKey, {
        // using: [Firebase],
        recordScreenViews: true,
        trackAppLifecycleEvents: true,
        trackAttributionData: true,
        android: {
          flushInterval: 60,
          collectDeviceId: true
        },
        ios: {
          trackAdvertising: true,
          trackDeepLinks: true
        }
      })
      .then(() =>
        console.log("Analytics is ready")
      )
      .catch(err =>
        console.error("Something went wrong", err)
      );
  },
  identify: (content) => {
    Analytics.identify(content);
  },
  track: async (eventName, properties) => {
    const payload = {
      ...properties
    };
    Analytics.track(eventName, payload);
  }
};
```

Can someone please help?

**Comment by rlopezapplaudo** [comment]
Check the last version beta released
pr https://github.com/segmentio/analytics-react-native/pull/162
should fix this issue
