### ISSUE TITLE
How to record traits without userId? (typescript)

### ISSUE THREAD

**Issue by jefersondaniel** [segmentio/analytics-react-native#124]
In analytics.ts, identify() requires `user`(userId) parameter.

```
public async identify(user: string, traits: JsonMap = {}, options: Options = {})
```

But docs tells userId can be omitted if wanna just record traits.

https://segment.com/docs/sources/mobile/react-native/#identify

> userId | The database ID for this user. If you don’t know who the user is yet, you can omit the userId and just record traits. You can read more in the identify reference.

How can I omit `userId` when call identify() in typescript?

**Comment by justinjoyn** [comment]
If you don't have a userId but want to record traits, you should pass nil.

**Comment by rlopezapplaudo** [comment]
@kellymtrinh 
Actually only can be optional optional if anonymousID is set instead
https://segment.com/docs/connections/spec/identify/

**Comment by rlopezapplaudo** [comment]
@jefersondaniel 
You can call it
`analytics.identify(null, {your_key: 'value'})`

@bsneed @lubird

**Comment by jpolo** [comment]
@rlopezapplaudo Your solution seems to crash on android platform.

**Comment by bsneed** [comment]
seems to be resolved.
