### ISSUE TITLE
Setting anonymousId for user

### ISSUE THREAD

**Issue by DylanAndrews** [segmentio/analytics-react-native#125]
Is there any plan to add the ability to set the `anonymousId` for a user with the SDK? This is currently possible on the web by doing `analytics.user().anonymousId('ABC-123-XYZ')` (see docs [here](https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/#setting-the-anonymous-id)). 

Our current analytics implementation relies on this functionality in order to ensure anonymous events are properly merged in amplitude. It works as follows

1. User accesses our app anonymously and we generate a unique identifier for the user on the server.
2.  This unique identifier is used on the server via the segment-ruby gem as the user's `anonymous_id` for all `track` and `identify` calls. 
3. This unique identifier is set as the user's anonymous id in the client via `analytics.user().anonymousId([unique_identifier])`
4. The combination of steps 3 and 4 ensure that all client and server side events show up under the same profile in amplitude.
5. Anonymous user signs in to the app and a server side `identify` call is made with the `anonymous_id=[unique_identifier of anonymous user]` and `user_id=[unique_identifier of user logging in]`. Sending both of these attributes is what merges the anonymous events of the anonymous user with the events of the user that is logging in.

So, without this ability to set the `anonymousId` we cannot follow this same pattern. As an alternative we can do 2 things (open to hearing other options if you have them).

1. Instead of using the unique identifier we create for anonymous events on the client and the server, we could use the `anonymousId` the RN sdk creates and put it in cookie for use on the server for the anonymous `track` and `identify` calls.
2. Use the `alias` method on the server to merge the accounts (we have had trouble with this in the past)

As I mentioned, the ideal option for us would be to set the `anonymousId` for the user with the RN SDK. Please let us know your thoughts on that matter. Thanks.

**Comment by josephfinlayson** [comment]
We're also trying to achieve exactly the same thing, and are considering forking this repo.

**Comment by aultimus** [comment]
It looks to me like for android this should be possible by setting 'anonymousId' in traits as an argument to Identify()

https://github.com/segmentio/analytics-android/blob/5722505387e108e38122a64a1e41d60e87f32a55/analytics/src/main/java/com/segment/analytics/Analytics.java#L741

For ios I believe that setting 'anonymousId' in options as an argument to Identify() should set anonymousId

**Comment by DylanAndrews** [comment]
@aultimus Thanks for the info. However, I'm a bit confused, as I don't see how that helps with the ability to do this with the RN SDK. Am I misunderstanding something?

**Comment by aultimus** [comment]
This is the native code that an RN Identify call will hit, hence I believe that passing this value in RN will exhibit the same behaviour as in android or IOS

**Comment by rlopezapplaudo** [comment]
@DylanAndrews 
- Get anonymousId
`analytics.getAnonymousId()`
- Override anonymousId 
`analytics.identify(null, {anonymousId: 'ANY_VALUE'})`
- Override user ID and anonymousId 
`analytics.identify('ANY_VALUE', {anonymousId: 'ANY_VALUE'})`

**Comment by rlopezapplaudo** [comment]
@DylanAndrews

You can try sending traits with your value
`analytics.identify(null, {your_key: 'value'})`

For you will be like 
`analytics.identify(null, {anonymousId: 'your_key_here'})`

@bsneed @lubird

**Comment by bsneed** [comment]
This seems to have been answered.  Thanks @rlopezapplaudo !

**Comment by DylanAndrews** [comment]
Thanks to everyone who has weighed in on this in the last month, and very sorry for the late response on this. Things have been crazy at work, and we ended up taking a different direction on this so solve the problem, and then actually had to pull out our usage of the RN SDK altogether because it was causing our app to be rejected (kids apps are now not allowed to have it). However, I still wanted to follow up, as we may still need this in the future, and it sounds like others need it as well.

So, regarding your proposed solution, are you saying that passing `anonymousId` in the traits argument will result in the `anonymousId` being set at the top level (not just in the traits object)? It sounds like you are, and the code you linked to does seem to suggest that, but I just want to clarify because in order for the profile merging functionality that we need this for to work properly, the `anonymousId` cannot live at the traits level of an identify call (see raw segment identify call below), but instead has to live at the same level as the `userId`. 

Thanks again for the help.

#### Segment Identify Call
```
{
  "anonymousId": "507f191e810c19729de860ea",
  "channel": "browser",
  "context": {
    "ip": "8.8.8.8",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36"
  },
  "integrations": {
    "All": false,
    "Mixpanel": true,
    "Salesforce": true
  },
  "messageId": "022bb90c-bbac-11e4-8dfc-aa07a5b093db",
  "receivedAt": "2015-02-23T22:28:55.387Z",
  "sentAt": "2015-02-23T22:28:55.111Z",
  "timestamp": "2015-02-23T22:28:55.111Z",
  "traits": {
    "name": "Peter Gibbons",
    "email": "peter@example.com",
    "plan": "premium",
    "logins": 5,
    "address": {
      "street": "6th St",
      "city": "San Francisco",
      "state": "CA",
      "postalCode": "94103",
      "country": "USA"
    }
  },
  "type": "identify",
  "userId": "97980cfea0067",
  "version": "1.1"
}
```

**Comment by aultimus** [comment]
@DylanAndrews I believe that to be the case from looking at the code, yes. Let me know if that does not work for you

**Comment by gauravdani-joyn** [comment]
it wont work.

**Comment by gantunesr** [comment]
Hi @DylanAndrews, Is there a way of setting the `anonymousId` at the top level?

**Comment by jenshandersson** [comment]
Sending it as a trait won't work. Why aren't there `options` on the identify call in RN lib?
Seems like it works to assign/override `anonymousId` on the web SDK and the iOS/Android ones.
https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/identity/#override-the-anonymous-id-using-the-options-object

**Comment by cyhoon** [comment]
Hi @gantunesr, I try it as follows.

```
segmentClient.userInfo.set({ anonymousId: 'your_anonymousId' });
```
