### ISSUE TITLE
Is there any documentation or access to source for integrations?

### ISSUE THREAD

**Issue by twelve17** [segmentio/analytics-react-native#129]
Other than the [main API docs](https://github.com/segmentio/analytics-react-native/blob/master/packages/core/docs/classes/analytics.client.md), I'm not having much luck finding information on specific integrations.  

The [main README's links to integrations](https://github.com/segmentio/analytics-react-native#integrations) point to NPM pages, none which seem to have a README.

Without having found much info, I am currently concluding that each integration is doing some magic, or has an opinion, as to how to construct the underlying configuration on the native side (I see there is a generic type of [bridge](https://github.com/segmentio/analytics-react-native/blob/master/packages/core/src/bridge.ts) that seems to be handing the wrapping of the underlying libraries for each integration, but I have no insight as to how each one might configure itself, since each one might have different options).  Or is it just the case that none of the integrations have options?

**Comment by ardyfeb** [comment]
I stopping using segment on react native because of this, there no clear documentation about this library and integrations. i trying to contact ustomer support and they also don't know about this

**Comment by bsneed** [comment]
There's not really any documentation for the integrations.  The main analytics-react-native repo covers everything necessary.  You add it in the 'use' section of your setup of Analytics.  Any subsequent track/screen/identify/etc calls simply get passed to the integration to do whatever makes sense for that particular vendor.  The source code to these is typically relatively small and straightforward.

**Comment by ardyfeb** [comment]
@bsneed how we can setup each integration like their api key, installation, etc. We need know how magic happen, thats work or not, thats error or not.

If we setup a mixpanel integration, install segment react native integration then pass that integration to `use` field on segment configuration, but how segment know my MixPanel api key ???

Not everyone having work with segment before, person who first using segment exactly on react native will stuck and never use this library
