### ISSUE TITLE
Cannot find module '@segment/analytics-ios/package.json'

### ISSUE THREAD

**Issue by ConnectedReasoning** [segmentio/analytics-react-native#130]
I got this message on my console after issuing the command react-native run-ios

warn Package @segment/analytics-ios has been ignored because it contains invalid configuration. Reason: Cannot find module '@segment/analytics-ios/package.json'

Where is the package.json for @segment/analytics-ios?

**Comment by rlopezapplaudo** [comment]
Please look inside 
Add analytics-ios as a npm dependency: 

yarn add @segment/analytics-ios@github:segmentio/analytics-ios

Or even better inside podfile 
pod 'Analytics', '~> 3.0'

Doc files
https://segment.com/docs/connections/sources/catalog/libraries/mobile/react-native/
