### ISSUE TITLE
Android build intermittently fails 

### ISSUE THREAD

**Issue by rborn** [segmentio/analytics-react-native#138]
I have  the case where the build fails for android and I need to rebuild again without any change in the code. Sometimes however the only way to make it work is to clear the `.gradle` folders in the project and the global one

The errors are:

`> Task :@segment_analytics-react-native-amplitude:compileDebugKotlin FAILED`

and

`> Task :@segment_analytics-react-native:compileDebugKotlin
w: Argfile not found: /Work/clients/current/emjoy/app/letsemjoyapp/segment_analytics-react-native_debug
`

Any ideas? 
I tried all the ideas/workarounds found in issues but it wouldn't fix anything.
Thank you 🤗

**Comment by rborn** [comment]
A similar error happened here https://github.com/matei-radu/react-native-in-app-browser/issues/72 and it seems to be an issue with AndroidX.

I run `npx jetify` as a postinstall script, so maybe somehow the module gets confused by this? 
I also see there is PR for this that's not merged: https://github.com/segmentio/analytics-android/pull/618

Thank you.

**Comment by rborn** [comment]
And another error, same behaviour

~~~
* What went wrong:
--

Execution failed for task ':@segment_analytics-react-native-amplitude:transformClassesAndResourcesWithSyncLibJarsForDebug'.
--
~~~

**Comment by bsneed** [comment]
The PR isn't merged because the author didn't go back to get the CI working.  AndroidX support is on our short-term roadmap, but I don't have an exact date yet.  I'm not sure if jetify is confusing things, entirely possible.

**Comment by rborn** [comment]
@bsneed could you please point me to that  PR, I'd rather have a forked/patched module than having to baby sit the build twice a day or worse, not to be able to make a release without cleaning all the caches in the world and build few times in a row 😅
Thank you 😻

**Comment by bsneed** [comment]
@rborn the PR I was referring to was the one you linked above: https://github.com/segmentio/analytics-android/pull/618.  I do have a PR in progress over in #157, which you may find useful.
