### ISSUE TITLE
Support put device token to life cycle events

### ISSUE THREAD

**Issue by quyentran-agilityio** [segmentio/analytics-react-native#144]
Hi guys, My react native app need to implement push notifications that required put device token to segment life cycle events. Does segment react-native lib support to add device token to life cycle events? 

Something like this: https://segment.com/docs/connections/sources/catalog/libraries/mobile/ios/#how-do-i-use-push-notifications
https://segment.com/docs/connections/destinations/catalog/customer-io/#device-token-set-up

**Comment by hvlong** [comment]
@quyentran-agilityio I have the same issue.

**Comment by adamjuhasz** [comment]
The iOS native library auto-adds it, we use this middleware for android

```typescript
import {
  Notification,
  Notifications,
  Registered,
} from 'react-native-notifications';

// global to store token
let deviceToken: string | null = null;

// called at startup
export const registerforPN = () => {

  if (Platform.OS === 'android') {
    Notifications.registerRemoteNotifications();
    Notifications.events().registerRemoteNotificationsRegistered(
      (event: Registered) => {
        deviceToken = event.deviceToken;
      },
    );
  }
};

// middleware for this library
export const pnMiddleware: Middleware = payload => {
  const {next, context} = payload;
  if (Platform.OS === 'android' && deviceToken !== null) {
    if (!context.device) {
      context.device = {token: deviceToken};
    }
  }
  next(context);
};
```

**Comment by bsneed** [comment]
@adamjuhasz that is a *VERY* clever work around, I dig it.  We're gonna make this easier though.

**Comment by aliwaqar981** [comment]
@adamjuhasz 

> The iOS native library auto-adds it, we use this middleware for android
> 
> ```ts
> import {
>   Notification,
>   Notifications,
>   Registered,
> } from 'react-native-notifications';
> 
> // global to store token
> let deviceToken: string | null = null;
> 
> // called at startup
> export const registerforPN = () => {
> 
>   if (Platform.OS === 'android') {
>     Notifications.registerRemoteNotifications();
>     Notifications.events().registerRemoteNotificationsRegistered(
>       (event: Registered) => {
>         deviceToken = event.deviceToken;
>       },
>     );
>   }
> };
> 
> // middleware for this library
> export const pnMiddleware: Middleware = payload => {
>   const {next, context} = payload;
>   if (Platform.OS === 'android' && deviceToken !== null) {
>     if (!context.device) {
>       context.device = {token: deviceToken};
>     }
>   }
>   next(context);
> };
> ```

This is only working for custom events. Is there any wayout to set data in context for default lifecycle events?

**Comment by cdedreuille** [comment]
I'm having a same issue. In our set up we have `trackAppLifecycleEvents: true` set up when creating the client. I'm not sure how I could add the middleware on the default lifecycles events.

Any idea?
