### ISSUE TITLE
"premature close" when trying to npm install the package (manual install into iOS)

### ISSUE THREAD

**Issue by jtrinhx33** [segmentio/analytics-react-native#148]
I'm following the steps found here for the iOS portion of the React Native library install:
https://github.com/segmentio/analytics-react-native#ios-support-without-cocoapods

We are not using cocoapods so we have to go with the manual approach.

However I am failing at the first step with error "**premature close**" after running:

`npm install @segment/analytics-ios@github:segmentio/analytics-ios --save`

Here's the console output:
```
➜  worker git:(add-reactnative-segment-library) ✗ npm install @segment/analytics-ios@github:segmentio/analytics-ios --save
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jeannie/.npm/_logs/2020-03-19T20_43_31_109Z-debug.log
➜  worker git:(add-reactnative-segment-library) ✗
```

The details in that debug.log is this:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/jeannie/.nvm/versions/node/v11.11.0/bin/node',
1 verbose cli   '/Users/jeannie/.nvm/versions/node/v11.11.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   '@segment/analytics-ios@github:segmentio/analytics-ios',
1 verbose cli   '--save' ]
2 info using npm@6.13.4
3 info using node@v11.11.0
4 verbose npm-session a76853a413ca17c8
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for @segment/analytics-ios@github:segmentio/analytics-ios premature close
8 timing stage:rollbackFailedOptional Completed in 1ms
9 timing stage:runTopLevelLifecycles Completed in 56590ms
10 verbose stack Error: premature close
10 verbose stack     at PassThrough.onclose (/Users/jeannie/.nvm/versions/node/v11.11.0/lib/node_modules/npm/node_modules/end-of-stream/index.js:47:67)
10 verbose stack     at PassThrough.emit (events.js:202:15)
10 verbose stack     at emitCloseNT (internal/streams/destroy.js:59:8)
10 verbose stack     at processTicksAndRejections (internal/process/next_tick.js:76:17)
11 verbose cwd /Users/jeannie/Documents/projects/monorepo/mobile/worker
12 verbose Darwin 19.3.0
13 verbose argv "/Users/jeannie/.nvm/versions/node/v11.11.0/bin/node" "/Users/jeannie/.nvm/versions/node/v11.11.0/bin/npm" "install" "@segment/analytics-ios@github:segmentio/analytics-ios" "--save"
14 verbose node v11.11.0
15 verbose npm  v6.13.4
16 error premature close
17 verbose exit [ 1, true ]
```

The same error happens whether or not I specify the version `#3.6.10`. 

Any ideas on this?

Thanks

**Comment by bsneed** [comment]
What versions of node/npm do you have installed?  A quick google search in "2pm premature close", returns quite a few hits, some seem dependent on version to determine a solution.

**Comment by jtrinhx33** [comment]
Hi there, thanks for checking in - we've found the issue. It looks `premature close` is an npm error that happens when we try to `npm install` the target library (`@segment/analytics-ios@github:segmentio/analytics-ios`). Reason: this is because that target library does not have a package.json file within it.

Our workaround: This just means we cannot include this library in our internal package.json. Our workaround for this was to `yarn add` that library elsewhere, then drag and drop it over to our `/ios` folder, and finally go about manually linking that within XCode.

**Comment by bsneed** [comment]
thanks for researching @jtrinhx33. We can't include a package.json in our analytics-ios repo as it has no reason to be there otherwise.  Though if you can think of some other way we can mitigate this, or have a test app we can use to duplicate the issue we can prioritize and get it fixed.  Please reopen this issue if either of those are the case. 🙏
