### ISSUE TITLE
How can I set requestFactory within react-native sdk?

### ISSUE THREAD

**Issue by fr33z3** [segmentio/analytics-react-native#151]
I have found a guide https://segment.com/docs/connections/sources/catalog/libraries/mobile/ios/#proxy-http-calls to use a proxy server for ios sdk. Is there a way we can set this up within react-native sdk? Or is there workaround for this anywhere?

**Comment by bsneed** [comment]
There's not currently a way to set this in react native.  You'd need to write a native wrapper to provide that functionality.
