### ISSUE TITLE
Cannot compile latest version on Android

### ISSUE THREAD

**Issue by kingston** [segmentio/analytics-react-native#152]
I was able to integrate the library just fine on iOS, but when I tried to compile on Android, I got the following error:
```
FAILURE: Build failed with an exception.

* Where:
Build file '/.../node_modules/@segment/analytics-react-native/android/build.gradle' line: 16

* What went wrong:
A problem occurred evaluating project ':@segment_analytics-react-native'.
> Could not get unknown property 'defaultKotlinVersion2' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

```

I was able to get it to compile on 1.1.0 but the latest 1.1.1-beta version appears to error out on compile. 

Digging around - not sure if somehow this commit https://github.com/segmentio/analytics-react-native/commit/3c29a889dfb142ca357129685c73cbc2f99b9b16#diff-53e51ee8427e664794253d1b95f14fcb caused some incompatibilities with my build setup?

OS: Mac OSX 10.15.3
Command: react-native run-android
React Native: 0.61.4

**Comment by bsneed** [comment]
Hi @Kingston,

A conversation was started in the PR for that, not the best place for it, but to repeat that info here:

not seeing that error here. In packages/android/build.gradle, could you try removing line 4, and editing lines 16 and 45 where it's used with the actual 1.3.21 value and see if that resolves it for you?

**Comment by kingston** [comment]
Actually - I narrowed it to just line 16. Once I replaced line 16 with 1.3.21 it worked fine:

```
buildscript {
    repositories {
        jcenter()
        maven { url 'https://maven.google.com' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.21"
    }
}

```

**Comment by kingston** [comment]
Did some more digging. Found two blog posts that seem relevant:

+ https://wtanaka.com/node/8111
+ https://greggigon.com/2011/06/14/build-script-and-project-level-variables-gradle/

Not sure why yours works though - maybe different version of Gradle that changed this behavior?

**Comment by jeiemgi** [comment]
I am facing a similar issue:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/josemiguel/MixPanelTest/node_modules/@segment/analytics-react-native/android/build.gradle' line: 16

* What went wrong:
A problem occurred evaluating project ':segment_analytics-react-native'.
> Could not get unknown property 'defaultKotlinVersion' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
`
``

**Comment by jeiemgi** [comment]
> 

Sorry, which version of this library are you installing?

**Comment by bsneed** [comment]
Ok, I'm gonna ping the author of the PR for this and see what he can possibly do here.  If nothing, we'll revert that commit and issue a follow on beta.  The defaultKotlinVersion bits are so it can be supplied from the developer using the library, so if that goes back to being hard coded, might as well revert the PR and bump the kotlin version #.

**Comment by bsneed** [comment]
ps. @Kingston thanks so much for digging into that, much appreciated!

**Comment by rborn** [comment]
@bsneed any news about this? it breaks any build we try to do, and 1.1.0 doesn't want to play noce with RN 0.62, at least on my end. 
Thanks 😻

**Comment by bsneed** [comment]
@rborn I can't speak to 0.62, haven't tried that yet.  However, this particular issue mentioned here will get resolved by EOW.

**Comment by rborn** [comment]
@bsneed thank you 😻

**Comment by bsneed** [comment]
The fix for this is pending in PR #157

**Comment by sdenaci** [comment]
hi @bsneed !! thank you so much for your quick pr. however, after having updated to the new version (1.1.1-beta.1), the build fails at line 45 now

`FAILURE: Build failed with an exception.

* Where:
Build file '/Users/sarahdenaci/code/MobileApp/node_modules/@segment/analytics-react-native/android/build.gradle' line: 45

* What went wrong:
A problem occurred evaluating project ':@segment_analytics-react-native'.
> Could not get unknown property 'defaultKotlinVersion' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.`

Could you please advise? Thank you in advice for all your help :)

**Comment by rborn** [comment]
@sdenaci could you  try and move `def defaultKotlinVersion = '1.3.21'` outside the `buildscript` block (above) ?

**Comment by sdenaci** [comment]
hi @rborn! thanks for your response!

changing the gradle file to 

```
def safeExtGet(prop, fallback) {
    return rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

def defaultKotlinVersion = '1.3.21'

buildscript {
    repositories {
        jcenter()
        maven { url 'https://maven.google.com' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${rootProject.ext.has("kotlinVersion") ? rootProject.ext.get("kotlinVersion") : defaultKotlinVersion}"
    }
}
```

results in the following error for me:

```
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/sarahdenaci/code/MobileApp/node_modules/@segment/analytics-react-native/android/build.gradle' line: 17

* What went wrong:
A problem occurred evaluating project ':@segment_analytics-react-native'.
> Could not get unknown property 'defaultKotlinVersion' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

**Comment by bsneed** [comment]
@rborn @sdenaci i think we’re running into gradle version differences/incompatibilities. I’m using 4.4 here as is the CI and it’s quite old. I’m just going to pull that variable/function stuff out completely and do another release. Should be up in a few hours.

**Comment by rborn** [comment]
I just built with `distributionUrl=https\://services.gradle.org/distributions/gradle-6.2-all.zip` and it seems it works fine. (waiting for my CI to build also, I'll come back if it fails)

**Comment by bsneed** [comment]
@rborn good to know!  confirms my suspicions, thanks for checking that out!

**Comment by bsneed** [comment]
@sdenaci what version of gradle do you have?

**Comment by sdenaci** [comment]
@bsneed the version my project is using is 5.5 
thank you for your prompt response and help on this! :)

**Comment by bsneed** [comment]
No problem @sdenaci !  So what do we think the best path forward is here?  4.4 works, 5.5 does not, but 6.2 does.  Is this ability to supply version numbers from outside the project worth this incompatibility?

**Comment by sdenaci** [comment]
@bsneed @rborn when i change android>gradle>wrapper>gradle-wrapper.properties to 6.2 it still fails for me. is there someplace else i should change it?

**Comment by bsneed** [comment]
@sdenaci can you try this PR that was submitted this morning, #158 ?

**Comment by sdenaci** [comment]
@bsneed yes #158  that works for me! with gradle 5.5 as well :)

**Comment by bsneed** [comment]
@sdenaci Excellent, it's passing the CI so works on 4.4 as well.  It's not my favorite since it duplicates the version number, but I'm not inclined to keep messing with it. 😭 😂

**Comment by rborn** [comment]
@bsneed you could add a comment in the file though to remember to change that in multiple places 😅

**Comment by sdenaci** [comment]
@bsneed @rborn awesome! thank you both very much! :)

**Comment by nutlike** [comment]
For me it worked to replace `def defaultKotlinVersion = '1.3.21'` with `ext.defaultKotlinVersion = '1.3.21'` within the buildscript block (line 9 in build.gradle) – this way the version number doesn't need to be repeated. I never really worked with Gradle files, so it would be nice if someone could confirm whether this is a viable solution.

**Comment by bsneed** [comment]
@nutlike thanks!!  @sdenaci @rborn does this #159 PR seem better?

**Comment by sdenaci** [comment]
@bsneed #159 works great for me! and it is more concise so that is great! thank you very much @nutlike !

**Comment by bsneed** [comment]
@nutlike thanks so much for figuring out the magic incantation to get this working! 👍 Just merged that PR, will spin another beta.

**Comment by rborn** [comment]
@bsneed tested 1.1.1-beta.2 with gradle 6.2, worked ok 😻

**Comment by bsneed** [comment]
@rborn YAY!!  I'm so relieved, hehe.

**Comment by sdenaci** [comment]
works for me too @bsneed !! thank you so much for your thorough and quick help with this :)

**Comment by joaovpmamede** [comment]
I'm still getting
```
A problem occurred evaluating project ':segment_analytics-react-native-intercom'.
> Project with path ':@segment_analytics-react-native' could not be found in project ':segment_analytics-react-native-intercom'.
```
using gradle 5.5 with version `1.1.1-beta.2`.
Already tried changing to gradle 6.2 but I'm getting the same error.

Anything I should try next?

**Comment by rborn** [comment]
@joaovpmamede try to clean both `app/android/gradle` and  `your_user/.gradle` folders and build again. (the hidden folders) - this helped me built before this PR was done

**Comment by joaovpmamede** [comment]
@rborn I tried what you suggested with version `1.1.1-beta.2` and it failed again.
What version were you running?

**Comment by rborn** [comment]
I'm not using intercom, but amplitude, maybe there is an issue in intercom indeed?
