### ISSUE TITLE
React Native: Firebase and Flurry not receive Event

### ISSUE THREAD

**Issue by ththugues44** [segmentio/analytics-react-native#161]
Good morning all .

I wanted to try segment in my chat appliction. I installed react Native segment without any problem. I configured 4 statistical analysis platform namely: Amplitude, Flurry, Firebase, MixPanel. As below.

> analytics
  .setup('MY_KEY_SEGMENT', {
    using: [Mixpanel, Amplitude, Firebase, Flurry],
    recordScreenViews: true,
    trackAppLifecycleEvents: true,
    trackAttributionData: true,
    debug: true,
    android: {
      flushInterval: 60,
      collectDeviceId: true,
    },
    ios: {
      trackAdvertising: true,
      trackDeepLinks: true,
    },
  })
  .then(() => console.log('Analytics is ready'))
  .catch(err => console.error('Something went wrong', err));
analytics.track('demo_envent');

I decided to send a test event. Amplitude and MixPanel receive the test event almost instantaneously. but after against Firebase and Flurry do not receive an event. I do not know how to solve this problem.

Thank you

**Comment by rlopezapplaudo** [comment]
Actually I try same configuration and it works
Just be sure that you already setup GoogleService-Info.plist
Also firebase integrate the SDK and within 24 hours you'll see your first event reports try to use StreamView

**Comment by keenubee** [comment]
I also can't see any custom events in Firebase (from iOS) - only screen_view and user_engagement that are collected by Firebase by default.
Can you guys check if integration with Firebase works please?

**Comment by matAlmeida** [comment]
Any update? I'm having the same issue with the Firebase, using the exact same config as @ththugues44

**Comment by bsneed** [comment]
Please reopen this issue if more data can be provided, such as log output from Xcode and React-Native, screenshots of configs, etc.

**Comment by tien** [comment]
I'm having the exact same problems. only screen_view and user_engagement event seems to work.
