### ISSUE TITLE
[Android] Project with path ':@segment_analytics-react-native' could not be found in project ':segment_analytics-react-native-firebase'

### ISSUE THREAD

**Issue by warrify** [segmentio/analytics-react-native#164]
Hi after upgrading to react native 62.2 all of a sudden my android build fails with the error 

```
Build file '/Users/user/Documents/app/app/node_modules/@segment/analytics-react-native-firebase/android/build.gradle' line: 42
A problem occurred evaluating project ':segment_analytics-react-native-firebase'.
> Project with path ':@segment_analytics-react-native' could not be found in project ':segment_analytics-react-native-firebase'.
```

now line 42 reads:
```groovy
api project(":@segment_analytics-react-native")
```

I am currently on the following versions:
```json
"@segment/analytics-react-native": "^1.1.0",
"@segment/analytics-react-native-firebase": "^1.1.0",
"@segment/analytics-react-native-mixpanel": "^1.1.0",
```

I have tried deleting the node_modules folder and running `npm install`, cleaning the project but nothing worked so far. Only android is affected

**Comment by warrify** [comment]
I also left a https://github.com/segmentio/analytics-react-native/issues/21#issuecomment-616248895 in an old already closed issues

**Comment by warrify** [comment]
I got it temporarily working by:

```diff
-    api project(":@segment_analytics-react-native")
+    api project(":segment_analytics-react-native")
```

**Comment by A-Tokyo** [comment]
I fixed it by editing settings.gradle and adding:
```
// By Us - @segment/analytics-react-native-mixpanel - to make @segment/analytics-react-native-mixpanel work with rn 0.62.2 - 0.63-rc0
include ':@segment_analytics-react-native'
project(':@segment_analytics-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/@segment/analytics-react-native/android')
```

**Comment by warrify** [comment]
@A-Tokyo thanks that should work as well 👍 

But it's unfortunately not the solution as the module should link automatically :/

**Comment by A-Tokyo** [comment]
@warrify Thanks! I understand, opened an issue here as well https://github.com/segmentio/analytics-react-native/issues/165

I honestly always have so much trouble linking segment whenever I upgrade RN or touch any android related deps 😓

**Comment by dagi3d** [comment]
I had the same issue and the solution proposed by @warrify  worked for me. The one by @A-Tokyo seemed to work but then raised another different error(which apparently was related to duplicated classes, so it's very likely there was something else I was missing about how to apply the patch)
In case you need to make a release in your CI environment and apply the proposed workaround, you can write this simple task in the build.gradle file:

```
task fixLib {
    ant.replaceregexp(match:':@segment_analytics-react-native', replace:':segment_analytics-react-native', flags:'g', byline:true) {
        fileset(dir: '../../node_modules/@segment/analytics-react-native-firebase/android', includes: 'build.gradle')
    }
}

fixLib;
apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
```

**Comment by warrify** [comment]
@dagi3d  as an alternative one could also use [patch-package](https://www.npmjs.com/package/patch-package)

**Comment by A-Tokyo** [comment]
@dagi3d Awesome! Thanks a lot for posting the solution!

**To wrap up, the fix is:**

1) edit settings.gradle and add:
```
// By Us - @segment/analytics-react-native-mixpanel - to make @segment/analytics-react-native-mixpanel work with rn 0.62.2 - 0.63-rc0
include ':@segment_analytics-react-native'
project(':@segment_analytics-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/@segment/analytics-react-native/android')
```
2) Edit app/build.gradle and add: (Note that you need to add it only for the packages you use eg firebase and mixpanel in this case) -- Author: @dagi3d 
```
// By Us - byUs_FixSegmentLibs for segment analytics https://github.com/segmentio/analytics-react-native/issues/164
task byUs_FixSegmentLibs {
    ant.replaceregexp(match:':@segment_analytics-react-native', replace:':segment_analytics-react-native', flags:'g', byline:true) {
        fileset(dir: '../../node_modules/@segment/analytics-react-native-mixpanel/android', includes: 'build.gradle')
    }
    ant.replaceregexp(match:':@segment_analytics-react-native', replace:':segment_analytics-react-native', flags:'g', byline:true) {
        fileset(dir: '../../node_modules/@segment/analytics-react-native-firebase/android', includes: 'build.gradle')
    }
}
byUs_FixSegmentLibs;

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
```


Note: The `By Us` prefix is a highly opinionated prefix we use to easily detect what we add to the native files usually edited by RN.

**Comment by bsneed** [comment]
This is fixed in #169 and will go out in an updated release later this week.

**Comment by bsneed** [comment]
ps.  Thank you guys so much for helping each other and coming up with these solutions!   @A-Tokyo & @dagi3d 🙏

**Comment by A-Tokyo** [comment]
@bsneed Thank you guys for the amazing work ( : 🎉
