### ISSUE TITLE
Cannot build ios with appsflyer

### ISSUE THREAD

**Issue by jpolo** [segmentio/analytics-react-native#171]
After a `yarn add @segment/analytics-react-native` (v1.1.1-beta.2) on a react native 0.61.x project
we have a build error :
```bash
fatal error: 'Segment-AppsFlyer/SEGAppsFlyerIntegrationFactory.h' file not found
#import <Segment-AppsFlyer/SEGAppsFlyerIntegrationFactory.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Looking at the podspec of this integration it depends on segment-appsflyer-ios which places the pod in the segment-appsflyer-ios folder after the `pod install`.

I tried tinkering the `node_modules/@segment/analytics-react-native` folder and I managed to build the project if I apply :
```diff
-#import <Segment-AppsFlyer/SEGAppsFlyerIntegrationFactory.h>
+#import <segment-appsflyer-ios/SEGAppsFlyerIntegrationFactory.h>
```

**Comment by bsneed** [comment]
A fix for this is included in #169 and will be released shortly.  Thanks for providing the clues @jpolo !
