### ISSUE TITLE
Cannot build with @segment_analytics-react-native-appboy

### ISSUE THREAD

**Issue by Francesco-Voto** [segmentio/analytics-react-native#174]
Hello!

I'm facing problem with the AppBoy integration.

On Android when I am trying to build the app I receive

```
* What went wrong:
A problem occurred evaluating project ':@segment_analytics-react-native-appboy'.
> Project with path ':segment_analytics-react-native' could not be found in project ':@segment_analytics-react-native-appboy'.
```

I am using     
@segment/analytics-react-native: ^1.1.1-beta.3
@segment/analytics-react-native-appboy: ^1.1.1-beta.3

on RN 0.61.4.

Any Suggestion?

I saw the issue [#164](https://github.com/segmentio/analytics-react-native/issues/164) and it seems to be the other way round.

**Comment by bsneed** [comment]
@Francesco-Voto can you update to RN 0.62 and try with that?

**Comment by Francesco-Voto** [comment]
@bsneed thanks for replying.
I update to RN 0.62 and it seems to fix that problem.

Anyway now I have this one:

```
   > Could not find com.appboy:android-sdk-ui:6.0.0.
     Required by:
         project :app > com.appboy:appboy-segment-integration:4.0.0
```

**Comment by bsneed** [comment]
@Francesco-Voto Maybe Appboy's maven installation was down.  That message is coming from Gradle and I can see the package here: https://appboy.github.io/appboy-android-sdk/sdk/com/appboy/android-sdk-ui/6.0.0/. You might retry it and see.
