### ISSUE TITLE
Support for React Native for Web

### ISSUE THREAD

**Issue by daxfrost** [segmentio/analytics-react-native#176]
![image](https://user-images.githubusercontent.com/1788177/81978825-1252cb80-95fa-11ea-9158-d3aa63860e43.png)

The above issue has been reported before [here](https://github.com/segmentio/analytics-react-native/issues/19).

But I thought it best to suggest it is also occurs when the consuming application is supporting **React Native for Web**, it would be great if there was handling for this by bundling your javascript SDK and piping [Platform](https://reactnative.dev/docs/platform-specific-code) specific API calls to this instead, many React Native 3rd party libraries are starting to handle the web. Do you have a solution for this already that I am missing?

**Comment by bsneed** [comment]
Hi @daxfrost!  We don't currently have a solution for this.  Our react-native library is just a thin wrapper on top of our existing native libraries and doesn't provide much functionality on its own.  Building support for it to wrap analytics.js isn't practical just yet.  We have been having internal discussions that would likely address this but aren't ready to announce anything just yet.

**Comment by hsavit1** [comment]
any updates on this?
