### ISSUE TITLE
Failed to load Analytics native module

### ISSUE THREAD

**Issue by isonlaxman** [segmentio/analytics-react-native#177]
I'm trying to use Segment for analytics on my React Native app. I want it to work for both Android and iOs. This issue persists on both OS's.

I installed the NPM library as explained [here][1] by doing:

    yarn add @segment/analytics-react-native
    yarn react-native link

Expected behaviour: I'm able to use analytics in the app

Actual behaviour: an error is thrown with message "Failed to load Analytics native module"

Code: (i do this in App.tsx/componentDidMount)

    import Segment from '@segment/analytics-react-native';
    import FirebaseAnalytics from '@segment/analytics-react-native-firebase'

    Segment.setup(keys.segment.writeKey, {
      recordScreenViews: true,
      trackAppLifecycleEvents: true,
      trackAttributionData: true,
      using: [FirebaseAnalytics]
    })

This is pretty much what they use in the documents. I'm not sure what I'm doing wrong. One thing to note is that I'm using Expo, not plain react-native. 

I've tried solutions mentioned [here][2] and [here][3] but to no avail.

  [1]: https://github.com/segmentio/analytics-react-native#installation
  [2]: https://github.com/segmentio/analytics-react-native/issues/19
  [3]: https://github.com/segmentio/analytics-react-native/issues/19

**Comment by isonlaxman** [comment]
This is my MainApplication.java file:
`import com.segment.analytics.reactnative.core.RNAnalyticsPackage;
.
.
.
@Override
    protected List<ReactPackage> getPackages() {
      List<ReactPackage> packages = new PackageList(this).getPackages();
      packages.add(new ModuleRegistryAdapter(mModuleRegistryProvider));
      packages.add(new RNAnalyticsPackage());
      return packages;
    }`

**Comment by bsneed** [comment]
We don't currently support Expo.  It doesn't work well with native code, which is more or less what our RN SDK is.   Look into expo's eject functionality, it may help you get it working.
