### ISSUE TITLE
"Failed to load Analytics native module" error with using iOS manually

### ISSUE THREAD

**Issue by vladTrex** [segmentio/analytics-react-native#19]
Hi there!

We tried to install segment through manually install (don't use CocoaPods), passed all steps described in readme and build was launched.

But when I try to import analytics lib `import analytics from '@segment/analytics-react-native';`
I got an error: Failed to load Analytics native module'
Error was reproduced on 2 environments.

I also checked integration in xcode:
- Embedded Binaries (added Analytics.framework) 
- Embed Frameworks
Versions: RN 0.55, analytics-ios SDK 3.7.0-beta.2

**Comment by ravirupareliya** [comment]
@vladTrex Did you get any solution? I am having same error with `ios`

**Comment by fathyb** [comment]
Hey! We've improved support for using iOS manually in `0.0.1-beta.3`, could you try it out? Be sure to follow the [migrations instructions](https://github.com/segmentio/analytics-react-native/blob/master/CHANGELOG.md#migration-instructions). Feel free to reopen if you're still experiencing the issue.

**Comment by jjingrong** [comment]
Just in case anyone is still having this error (Aka. `Failed to load Analytics native module`), and you weren't trying to do it manually - 

You will have to run 
```bash
pod install
```

inside your `/ios` folder in your React Native project, then compile it through xcode.

**Comment by mickmak-busicat** [comment]
I just fixed this problem by doing:
1. Add `${PROJ_DIR}/node_modules/@segment/analytics-react-native/ios/RNAnalytics.xcodeproj` to your project `Libraries` folder group.
2. Under the project `General` tab, `Linked Frameworks and Libraries` section, search for `libRNAnalytics.a` and add it.
3. Try to build again and run the app.

This is common react native module manually linking process which I have missed out.
Not sure if it is the case, but worth a try if the library is not added.

**Comment by AmitPandya007** [comment]
> I just fixed this problem by doing:
> 
> 1. Add `${PROJ_DIR}/node_modules/@segment/analytics-react-native/ios/RNAnalytics.xcodeproj` to your project `Libraries` folder group.
> 2. Under the project `General` tab, `Linked Frameworks and Libraries` section, search for `libRNAnalytics.a` and add it.
> 3. Try to build again and run the app.
> 
> This is common react native module manually linking process which I have missed out.
> Not sure if it is the case, but worth a try if the library is not added.

this solution did not helped out, will you please suggest some different solution.

**Comment by gavrilin-remote** [comment]
> I just fixed this problem by doing:
> 
> 1. Add `${PROJ_DIR}/node_modules/@segment/analytics-react-native/ios/RNAnalytics.xcodeproj` to your project `Libraries` folder group.
> 2. Under the project `General` tab, `Linked Frameworks and Libraries` section, search for `libRNAnalytics.a` and add it.
> 3. Try to build again and run the app.
> 
> This is common react native module manually linking process which I have missed out.
> Not sure if it is the case, but worth a try if the library is not added.
Works for me, thanks a lot!
