### ISSUE TITLE
Android hangs on .useNativeConfiguration()

### ISSUE THREAD

**Issue by SMJ93** [segmentio/analytics-react-native#190]
On Android, if you press the hardware back button and then open up the app again it hangs on `useNativeConfiguration` because it has `already been configured`:

```
Possible Unhandled Promise Rejection (id: 0):
Error: Analytics has already been configured
Error: Analytics has already been configured
    at Client.useNativeConfiguration
```

To fix this you need to check if `SegmentAnalytics` has already been imported before calling useNativeConfiguration:

```
import SegmentAnalytics from '@segment/analytics-react-native';

if (!SegmentAnalytics.ready) {
    SegmentAnalytics.useNativeConfiguration();
}
```

This should probably be handled inside `node_modules/@segment/analytics-react-native/src/analytics.ts` line 161 or at least mentioned in the docs.

**Comment by prayansh** [comment]
@SMJ93 thank you for bringing this up. We will make sure to update our docs with the code snippet you suggested

**Comment by bsneed** [comment]
@prayansh can we push this logic into useNativeConfiguration() itself so customers don't need to worry about it?
