### ISSUE TITLE
configuring `WRITE_KEY` on-the-fly

### ISSUE THREAD

**Issue by viggyfresh** [segmentio/analytics-react-native#191]
Hi there! We're trying to integrate segment into our RN app and have come across an issue that we're not sure how to solve.

Our app has an admin panel with an environment switcher - this allows us to release one binary and have it be able to switch between production / staging / dev environments. Because of this, for any third-party integration, we need to be able to switch up environments as well.

In the case of Segment analytics, one would think this is achievable by calling `await analytics.setup(segmentWriteKey, ...);` with the appropriate key for the environment. However, the gotcha is that this doesn't take effect until the app is fully quit and restarted. So, if you change environments from production to dev and then proceed to emit some events, they'll get tracked to production.

Is there any way that we can work around this?

**Comment by viggyfresh** [comment]
the method we've chosen to employ is to intentionally crash the app to reset the analytics SDK. i hope that there is a better way...

**Comment by bsneed** [comment]
@viggyfresh unfortunately not. :( The underlying iOS library does not support changing the write key post-initialization.  We are looking at changing this in the future though, but I don't have a timeframe to provide just yet.
