### ISSUE TITLE
flushAt milliseconds or seconds?

### ISSUE THREAD

**Issue by jbolotin** [segmentio/analytics-react-native#199]
Hey all, quick question regarding the `flushAt` property during configuration setup:

Per [this comment](https://github.com/segmentio/analytics-react-native/blob/74295673172b8bc3665f66a7b1e981bd0b094f72/packages/core/src/analytics.ts#L79), it seems as though `flushInterval` is an interval in milliseconds, but I'm a bit confused by the [example configuration](https://github.com/segmentio/analytics-react-native/blob/master/README.md#usage) setting `flushInterval` to `60`. Assuming this is milliseconds, it seems to violate the recommended behavior in [Segment's documentation](https://segment.com/docs/connections/sources/catalog/libraries/mobile/react-native/#how-does-the-sdk-queue-api-calls) around queuing events because 60 ms would functionally make a call for every few events at most.

Is the recommended `flushInterval` for Android supposed to be 60 seconds, or do you mind providing additional information on why such a short `flushInterval` is best? At 60ms, I would think that it might be better to just set `flushAt: 1` instead and not deal with `flushInterval` at all.

Any help would be greatly appreciated!

**Comment by bsneed** [comment]
Hi @jbolotin!  `flushAt` is based on number of events.  `flushInterval` is using using milliseconds, yes.  The example shown is incorrect.  I'll make an update to fix that.  Thanks for bringing it to our attention! 👍
