### ISSUE TITLE
Get the native Intercom instance to show the chat

### ISSUE THREAD

**Issue by thib92** [segmentio/analytics-react-native#20]
Hello 👋 

I am trying to integrate the Segment React-Native SDK with Intercom.

Reading [the native docs for the Intercom integration](https://segment.com/docs/destinations/intercom/#control-the-intercom-chat-widget-mobile-only-), I see that it is possible in Objective-C or in Java to get access to the `Intercom` instance. I believe this is required in order to display the Intercom chat.

I don't see any documentation allowing to get an integration's instance. Is this not available yet?

**Comment by RahavLussato** [comment]
@bsneed is there any answer for this?

**Comment by bsneed** [comment]
There's no way (that I'm aware of) to get the intercom instance in react-native unfortunately.
