### ISSUE TITLE
Unable to anonymize IPs

### ISSUE THREAD

**Issue by albertovillalobos** [segmentio/analytics-react-native#201]
As per the docs: https://segment.com/docs/connections/sources/catalog/libraries/mobile/react-native/#anonymizing-ip

I'd like to anonymize IPs by overriding the context.ip (among other data) when using the track method.

Currently the `track` method only takes three arguments `event, properties, options` however we are unable to remove PII information from it by overriding data in the payload.

Is there another way to achieve this (through code)?

**Comment by albertovillalobos** [comment]
This was fixed here: https://github.com/segmentio/analytics-react-native/pull/188/files

**Comment by dbilgin** [comment]
How was this fixed exactly? I'm not able to set it, could you show me how you did it?

**Comment by albertovillalobos** [comment]
@dbilgin 
1 - Make sure to update your segment package, mine was `1.1.0` and I updated to `1.2.1`
2 - When you call `track` you can pass a third parameter which is an object with overrides.

```
   analytics.track(event, data, { context: { ip: '0.0.0.0' } });
```

Before the issue was resolved, context wasn't override-able, now it is.
