### ISSUE TITLE
Error: Failed to load Analytics native module

### ISSUE THREAD

**Issue by champ3oy** [segmentio/analytics-react-native#203]
I'm getting this error 'Error: Failed to load Analytics native module' just by importing '@segment/analytics-react-native'

I'm using it in a project initialized with 'npx create-react-native-app' with react native version 0.62.2
I saw some answers but they were for IOS, I'm using it with Android and Expo Client

Any help here?

**Comment by bsneed** [comment]
We don't currently support using Expo, so hard to say what could be happening here.  We're working on some updates here to make that an actual supported use case, but it probably won't happen till the end of the year.  If you're not using 3rd party device-mode integrations, you might also check out the Segment module maintained by the Expo team.
