### ISSUE TITLE
iOS 14 IDFA

### ISSUE THREAD

**Issue by SMJ93** [segmentio/analytics-react-native#205]
Hi,

Will we need to make any changes to how we use Segment because of the new IDFA changes coming in iOS 14?

More details [here](https://www.forbes.com/sites/johnkoetsier/2020/06/24/apple-just-made-idfa-opt-in-sending-an-80-billion-industry-into-upheaval/).

At the moment it says in the [docs](https://segment.com/docs/connections/sources/catalog/libraries/mobile/react-native/#submitting-to-the-app-store) we need state the app collects IDFA when submitting an app for review even if we’re not currently doing mobile install attribution.

**Comment by bsneed** [comment]
@SMJ93 Yeah, changes will need to be made.  We're still working on the RN side, but for iOS, we've moved IDFA out to the app so those options when submitting are no longer necessary (unless you're using IDFA).  More details on this will show up in the next week or so.

**Comment by SMJ93** [comment]
Hi @bsneed  any update with this? In the [docs](https://segment.com/docs/connections/sources/catalog/libraries/mobile/react-native/#submitting-to-the-app-store) it still says it's turned on by default.

**Comment by phuochau** [comment]
Hi all, I have same question here

**Comment by lucidlive** [comment]
Same question

**Comment by bsneed** [comment]
@SMJ93 @phuochau @lucidlive https://segment.com/docs/connections/sources/catalog/libraries/mobile/react-native/#set-idfa
