### ISSUE TITLE
Overriding Timestamps [Feature Request]

### ISSUE THREAD

**Issue by Frans-L** [segmentio/analytics-react-native#209]
Hey!

It seems like HTTP API supports overriding the timestamps, but this native one doesn't. Overriding the timestamps would be really handy in situations, where old actions should be sent to the servers. 

Or are there any alternative ways to modify the timestamps? Thanks :)

**Comment by bsneed** [comment]
Timestamps are a combination of client-side and server-side generation.  Best to not modify them.  An alternative might be inserting your own data into context/properties/etc child dictionaries and then working with that instead.  Once everything has left the Segment system, it'd probably be ok to modify.

**Comment by Frans-L** [comment]
@bsneed 

Could a client-side timestamp be modified?

For example: Let’s say there is a app that is running on background and uses phone’s accelometer to spot when a user jumps. The background process is running natively, and everything else is running over react-native.

The usage statistics are sent through react-native. After the user opens the app, the jump log can be created. Unfortunately, the timestamp will be the app opening time instead of jumping time. 

If a client-side timestamp could be overridden, this problem could be fixed easily.
