### ISSUE TITLE
React native latest version can not run project

### ISSUE THREAD

**Issue by Jalson1982** [segmentio/analytics-react-native#218]
Hello,

I am using analytics and amplitude. But if I add amplitude package, I get error 74 duplicate symbols for architecture x86_64 pointing on Amplitude package. On old version 0.61.5 all works fine but with latest react native there is no chance to run analytics and amplitude in same time. Any help?

**Comment by bsneed** [comment]
Old version of what, React Native?  A build log would be helpful so we can see what's going on.
