### ISSUE TITLE
CocoaPods could not find compatible versions for pod "RNAnalytics"

### ISSUE THREAD

**Issue by justinairbase** [segmentio/analytics-react-native#219]
Error when trying to install latest version of SDK
```[!] CocoaPods could not find compatible versions for pod "RNAnalytics":
  In Podfile:
    RNAnalytics (from `../node_modules/@segment/analytics-react-native`)

Specs satisfying the `RNAnalytics (from `../node_modules/@segment/analytics-react-native`)` dependency were found, but they required a higher minimum deployment target.

Aborting run
An unexpected error was encountered. Please report it as a bug:
```

I'm on latest version of Xcode 12.0 (12A7209).
The current deployment target is iOS 10.0.
```
"@segment/analytics-react-native": "^1.3.1",
"react": "16.13.1",
 "react-native": "0.63.2",
```

**Comment by bsneed** [comment]
Sounds like you have another pod dependency that's pinned at 3.x.  If you look through your podfile.lock, you can see what versions of things you have installed and see if they're pinned.  If it's a segment owned piece, let me know can I can fix that.

**Comment by jonathanm-tkf** [comment]
I have the same problem

**Comment by bsneed** [comment]
@jonathanm-tkf it would be helpful if you answered the same questions I asked of the OP.  I can't do anything for you if you're willing to provide zero information.

**Comment by bsneed** [comment]
Also of note for all of you... iOS minimum deployment is 11.  So check that too.

**Comment by jonathanm-tkf** [comment]
If you create a react native project from 0 install @ segment / analytics-react-native, try to do a pod install and you will see the error

**Comment by jonathanm-tkf** [comment]
Why does the minimum version have to be 11?

**Comment by bsneed** [comment]
@jonathanm-tkf because that's required for analytics-ios to support swift package manager.

**Comment by jonathanm-tkf** [comment]
thanks it's working

**Comment by justinairbase** [comment]
> Also of note for all of you... iOS minimum deployment is 11. So check that too.

@bsneed Thanks for clarifying. Please add this in the documentation to avoid future confusion and looking through podfile.lock is a non trivial task.

**Comment by Garrett1Tolbert** [comment]
My minimum deployment target is 11.0 but i'm unable to 'pod install' @bsneed 
<img width="410" alt="Screen Shot 2020-10-12 at 7 08 13 PM" src="https://user-images.githubusercontent.com/17864504/95797746-48d26680-0cbe-11eb-95c2-3848a59539d6.png">

**Comment by bsneed** [comment]
@Garrett1Tolbert can't really diagnose the issue or troubleshoot without the output from the pod install command.

**Comment by Garrett1Tolbert** [comment]
@bsneed This is what I get when I 'pod install'

<img width="1050" alt="Screen Shot 2020-10-14 at 11 22 04 AM" src="https://user-images.githubusercontent.com/17864504/96017327-7ed33000-0e0f-11eb-9ed7-c80857ace897.png">

**Comment by bsneed** [comment]
@Garrett1Tolbert can you try it with `pod install --repo-update`?

**Comment by Garrett1Tolbert** [comment]
@bsneed Unfortunately, I get the same error. Do you have any other ideas?

**Comment by bsneed** [comment]
From what I can tell it looks like your minimum target is still < 11.0.  Edit your podfile to specify.

**Comment by Garrett1Tolbert** [comment]
That worked! I never knew the first line was where the deployment target was set. Thanks a lot @bsneed

**Comment by bsneed** [comment]
No problem!  It has no bearing on reality, it's just used for cocoapods to identify deps and versions.
