### ISSUE TITLE
Amplitude won't build

### ISSUE THREAD

**Issue by rborn** [segmentio/analytics-react-native#222]
Hi, 
It seems that Amplitude removed `enableLocationListening` in the latest version so the plugin won't build anymore

```
ios/Pods/Segment-Amplitude/Pod/Classes/SEGAmplitudeIntegration.m:30:29: error: no visible @interface for 'Amplitude' declares the selector 'enableLocationListening'
            [self.amplitude enableLocationListening];
             ~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~
```

https://github.com/amplitude/Amplitude-iOS/blob/eaed8f8f4547ca1b6af096fc04153884f945e495/CHANGELOG.md#breaking-changes

I'm using the latest version of the plugin.

Thank you 🤗

**Comment by rborn** [comment]
I fixed it for now with this in my Podfile
```
pod 'Amplitude', '~> 6.0'
```

**Comment by bsneed** [comment]
We've got an issue internally around this that I'm working on.  I'll post here with an update once I've pushed a new version up.

**Comment by bsneed** [comment]
Segment-Amplitude 3.2.1 pushed to cocoapods.  Should be available in React-Native now.
