### ISSUE TITLE
(question) does identify override previous call?

### ISSUE THREAD

**Issue by littlehome-eugene** [segmentio/analytics-react-native#224]
suppose you call
```

analytics.identify(user_id, params1)

analytics.identify(user_id, params2)
```

is it equal to calling ?
`analytics.identify(user_id, params2)`

(params1 has no effect)

**Comment by wmcbain** [comment]
From our experience the traits would be merged on multiple identify calls.

**Comment by bsneed** [comment]
Yes, traits will be merged.
