### ISSUE TITLE
Error when deep linking on app boot

### ISSUE THREAD

**Issue by zibs** [segmentio/analytics-react-native#226]
Hi Segment,

I'm seeing an error on a deep linking cold boot: 
```
Exception 'key `url` is a NSURL and can't be serialized for delivery.' was thrown while invoking setup on target RNAnalytics with params (
etc...
)
```

This occurs on the simulator when I boot the app with a command like: 
```
xcrun simctl openurl booted appSchemeName://path/to/link/to
```
Notably, this doesn't occur when using universal links, and doing something like
```
xcrun simctl openurl booted https://appSchemeName.com/path/to/link/to
```

This error is most likely a bug within the Segment RNAnalytics library as it only happens when using the `trackApplicationLifecycleEvents` flag during init, which causes a crash in the library [in this line](https://github.com/segmentio/analytics-react-native/blob/6ec053b1e2c5fcb1e7276c64ade9752c0417a615/packages/core/ios/RNAnalytics/RNAnalytics.m#L122) when it tries to send the `_bridge.launchOptions` since it seems to have trouble dealing with UIApplicationLaunchOptionsURLKey that our deep link opens with. Hence the error 'key url is a NSURL and can't be serialized for delivery.'

If we disable the `trackApplicationLifecycleEvents`, it doesn't happen, but I'd like to use that.

Any thoughts here? I can provide more info too if necessary.

relevant packages:
```
"@segment/analytics-react-native": "^1.3.1",
"react-native": "0.63.3"
```

**Comment by kurniawanw0194** [comment]
I got the same issue.

**Comment by zibs** [comment]
Any updates here?

**Comment by noobDev88** [comment]
when debug, i found they has Assert here http://prntscr.com/v9woko, and when you open with deeplink, the url is handled by launchOptions[UIApplicationLaunchOptionsURLKey]  in http://prntscr.com/v9wpqi has NSURL type, so, it doesn't match with type that can be serialized.

**Comment by sregg** [comment]
Seems like it was fixed in the iOS repo: https://github.com/segmentio/analytics-ios/issues/947
Hopefully we'll get a new release of the pod and the npm 🤞

**Comment by MateuszRostkowski** [comment]
I've struggled with this issue on 1.3.1 version. After upgrading to 1.3.2 everything works fine 🎉
