### ISSUE TITLE
Property 'trackAttributionData' not found on object of type 'SEGAnalyticsConfiguration *' during build

### ISSUE THREAD

**Issue by patrick-samy** [segmentio/analytics-react-native#228]
Hello,

I'm getting the following build error for iOS after updating my dependencies and pods:
```
/Users/patrick/Projects/span/app/node_modules/@segment/analytics-react-native/ios/RNAnalytics/RNAnalytics.m:63:12: Property 'trackAttributionData' not found on object of type 'SEGAnalyticsConfiguration *'
```

RNAnalytics.m:63
```
config.trackAttributionData = [options[@"trackAttributionData"] boolValue];
```

package.json:
```
"react-native": "^0.63.3",
"@segment/analytics-react-native": "^1.3.1",                                                                                                      
"@segment/analytics-react-native-firebase": "^1.3.1",
```

Podfile.lock
```
- Analytics (4.1.0)
- RNAnalytics (1.3.1)
- RNAnalyticsIntegration-Firebase (1.3.1)
- Segment-Firebase (2.7.0)
```

Any ideas? Thanks

**Comment by shikharmohan** [comment]
Seeing the same issue here. Seems to be caused by this change in the iOS SDK: https://github.com/segmentio/analytics-ios/commit/4c76dc9a0eca7e6978e1cbf3194cbe2c9e7f1ce5

**Comment by shikharmohan** [comment]
Fixed it by setting Analytics to 4.0.5 manually in the `Podfile`

**Comment by crrobinson14** [comment]
I had to do the same thing but also had this error:

```
[!] CocoaPods could not find compatible versions for pod "Analytics":
  In snapshot (Podfile.lock):
    Analytics (= 4.1.0, ~> 4.0)

  In Podfile:
    Analytics (= 4.0.5)

    RNAnalytics (from `../node_modules/@segment/analytics-react-native`) was resolved to 1.3.2, which depends on
      Analytics (~> 4.1)
```

So in addition to the above I had to force-set my React Native library version to 1.3.1:

`"@segment/analytics-react-native": "1.3.1",`

**Comment by crrobinson14** [comment]
Actually even that didn't get me over the hump, build still broken. segment.com seems to be offline as well. Had to yank the service from the app. Will try again in a few days.

**Comment by andiradulescu** [comment]
Works for me with `"@segment/analytics-react-native": "^1.3.2",`

"trackAttributionData" was removed in 1.3.2.

I was on "^1.3.1" and only did `yarn add @segment/analytics-react-native` to update it to "^1.3.2".

**Comment by patrick-samy** [comment]
Thanks, I can confirm `1.3.2` fixed this issue. Closing as resolved.

**Comment by patrick-samy** [comment]
@crrobinson14 Not sure if you ever managed to solve this, but a similar error with a different dependency now happens on `1.3.2` with the RN segment firebase integration:
https://github.com/segment-integrations/analytics-ios-integration-firebase/issues/62

**Comment by mloisotto** [comment]
Error still happening in the last version (1.4.1). Any updates on this?

**Comment by banky** [comment]
For people who come across this, you might have a mismatch between your `analytics-react-native` and your `Analytics` libraries. I was able to get around this issue with a `pod update` to update the sub-dependency

**Comment by zvs001** [comment]
There is no version specified in Pofile: https://github.com/segmentio/analytics-react-native/blob/master/packages/core/RNAnalytics.podspec

It should be v4+ now.
I upgraded to `Analytics 4.1.4` and it works now.
