### ISSUE TITLE
[Question] Is there a way to override the automatically collected version?

### ISSUE THREAD

**Issue by justDanielMata** [segmentio/analytics-react-native#229]
we have implemented appcenter codepush into our application now, which means that our mobile application will start to update without actually having the native build version move up. This poses a problem where the automatically collected context object will no longer be accurate. Is there any way to override that object either on the track call or somewhere else?

**Comment by bsneed** [comment]
@justDanielMata in your analytics calls, there's an options parameter, where you can pass in a dictionary named 'context' and insert a custom value there.  It'll be separate from what segment naturally reports, but I imagine at that point having both becomes useful.
