### ISSUE TITLE
Traits values are not being updated

### ISSUE THREAD

**Issue by robertgreso** [segmentio/analytics-react-native#231]
There is a scenario when traits values are not being updated after calling `analytics.identify(userId, traits);`

From debugging and comparing the traits I send as parameter in `identify` method and received raw data observed in source Segment debugger, it appears that the value is being set for particular traits key only if there hasn't been set any value for that key before.  

If there was value set before, and I call `analytics.identify(userId, traits);` where traits include updated value for particular key, I still see `Identify` event in Segment debugger, but the raw data show the old value which was previously set. If there havent been set any value for particular key before, correct value (the one sent from the app) is being shown in raw data.

Using "@segment/analytics-react-native": "1.3.2"

**Comment by bsneed** [comment]
I haven't been able to replicate this locally.  Can you reopen this issue if it's still occurring and post some examples?

**Comment by ghacosta** [comment]
I'm having this exact same issue, but this time using `"@segment/analytics-react-native": "^1.5.0",` @robertgreso did you find any solution on this one?

**Comment by erwannbst** [comment]
Same problem here with `"@segment/analytics-react-native": "^2.0.0-pilot.1"`
