### ISSUE TITLE
Invalid IPHONEOS_DEPLOYMENT_TARGET in Segment-Intercom pod

### ISSUE THREAD

**Issue by dani-mp** [segmentio/analytics-react-native#233]
The Segment-Intercom pod has an invalid IPHONEOS_DEPLOYMENT_TARGET, making the build fail.

We're currently using this workaround in the Podfile's `post_install`:
```ruby
# The dependency Segment-Intercom has set an invalid iOS deployment target.
# This script removes it so it can default to the one of the project.
installer.pods_project.targets.each do |target|
  if target.name.eql?("Segment-Intercom")
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
```

**Comment by santitipro** [comment]
Try this in your podfile.

`post_install do |installer|
    flipper_post_install(installer)
    t = installer.pods_project.targets.find { |t| t.name == 'Segment-Intercom' }
    t.build_configurations.each do |bc|
      bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
    end
  end`

**Comment by bsneed** [comment]
Fixed in Segment-Intercome 1.0.2

**Comment by dani-mp** [comment]
Hey, @bsneed. Unfortunately, this library hasn't yet been updated, could we reopen the issue until it's really resolved?

Thanks.

**Comment by bsneed** [comment]
Hi @dani-mp, you may need to do a `pod repo update`.  https://cocoapods.org/pods/Segment-Intercom
