### ISSUE TITLE
Irregularly missing calls

### ISSUE THREAD

**Issue by smn-snkl** [segmentio/analytics-react-native#237]
Hi there,

we are using version 1.3.1 of this SDK together with Wix' react-native-navigation library. We recently noticed, that when building our app in Release Mode, a significant share of tracking call goes missing, while working very stable in Debug Mode.

Missing events are triggered at various places:
- On react-native-navigation events, e.g. didAppear to track screen views using
```
Navigation.events().registerComponentDidAppearListener(({ componentName, componentType }) => {
  if (componentType === 'Component') {
    segmentAnalytics.screen(componentName, { context: { ip: '0.0.0.0' } });
  }
});
```
- In Redux reducers
- In callback functions
etc.

The only pattern we noticed is that events often go missing when navigating to different screens etc. So e.g. events that are triggered right before a screen is popped go missing very often, whereas events that get triggered within a screen without any transitions work fine.

For example, when running the app in Debug Mode on an iOS simulator, 12/12 screen transitions are tracked properly. Same code run in Release Mode on iOS device only 10/12 screen transitions end up showing in the Segment debugger.

Are there any known libraries interfering with segment? Does react-native-navigation or CodePush etc. cause problem with the flushing of Segment events?

Does anyone here know about similar issues or has a glue about what is happening here?

**Comment by wmcbain** [comment]
@smn-snkl Dealing with a different problem but found this on this documentation page: https://segment.com/docs/connections/sources/debugger/

> The Debugger is separate from your workspace’s data pipeline and is not an exhaustive view of all the events ever sent to your Segment workspace. The Debugger only shows a sample of the events that the Source receives in real time, with a cap of 500 events. The Debugger is a great way to test specific parts of your implementation to validate that events are being fired successfully and arriving to your Source.

**Comment by smn-snkl** [comment]
@wmcbain thx for sharing. I realized that the Debugger is an issue, but unfortunately the problem is not limited to the Debugger. I also connected the app with other destinations such as a database and Mixpanel and I dont see the events there either ...

It's really crazy because I tested every single event in Debug mode before releasing the app update. And it worked sufficiently well, but after two weeks, I realized that in the production environment some tracking calls don't ever get fired at all.

**Comment by wmcbain** [comment]
@smn-snkl Question for you, are you dynamically setting up the segment instance? We have multiple environments and the issue that we had is that the iOS SDK only allows you to call `setup` once. If you're possibly calling it twice with different keys this might be the issue.

**Comment by smn-snkl** [comment]
@wmcbain not sure I exactly understand your point. We do setup segment dynamically as described in the docs by calling `analytics.setup` after we got consent from the user. However, we define the key in an `.env` file, so there's no chance a user calls setup twice with two different keys.

Moreover, we also have the same issue on Android. E.g. we have one event in our app onboarding, that hasn't fired once in the last two weeks, but works fine when running the app in the simulator in debug mode.

**Comment by bsneed** [comment]
not sure there's anything I can offer to help here.  if you're manually calling screen, seems more like an issue in your codebase rather than this library.
