### ISSUE TITLE
SKAdNetwork support for Firebase integration

### ISSUE THREAD

**Issue by smn-snkl** [segmentio/analytics-react-native#243]
I couldn't find any information on whether the Segment's RN SDK and its Firebase integration already support SKAdNetwork?

I'd like to add App Open conversion tracking for Google Ads to our app, but because of specific App Store Guidelines for our app, we cannot collect IDFAs. Therefore, before starting to set everything up I wanted to check if the RN SDK and the Firebase integration support SKAdNetwork already?

If so, is there anything that needs to be set up explicitly or is it working out-of-the-box?

**Comment by bsneed** [comment]
Hi @smn-snkl, we don't do anything specific for SKAdNetwork.  This would need to be implemented on your end.
