### ISSUE TITLE
java.lang.IllegalAccessError: Interface androidx.lifecycle.d implemented by class com.segment.analytics.AnalyticsActivityLifecycleCallbacks is inaccessible

### ISSUE THREAD

**Issue by ofri-7chairs** [segmentio/analytics-react-native#244]
Application crash on release mode when we call analytics.setup

version: 1.3.2
react-native: 0.63.3

**Comment by prayansh** [comment]
This seems related to https://github.com/segmentio/analytics-android/issues/735. Try updating your proguard config to match our [docs](https://segment.com/docs/connections/sources/catalog/libraries/mobile/android/android-faqs/#how-should-i-configure-proguard)
