### ISSUE TITLE
pod install fails 

### ISSUE THREAD

**Issue by amitemrit** [segmentio/analytics-react-native#245]
Info:
System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 669.86 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found

Pod install error:
[!] CocoaPods could not find compatible versions for pod "RNAnalytics":
  In Podfile:
    RNAnalytics (from `../node_modules/@segment/analytics-react-native`)

Specs satisfying the `RNAnalytics (from `../node_modules/@segment/analytics-react-native`)` dependency were found, but they required a higher minimum deployment target.

**Comment by efstathiosntonas** [comment]
update platform in Podfile to `platform :ios, '11.0'`

**Comment by amitemrit** [comment]
Thats works great! thanks @efstathiosntonas
