### ISSUE TITLE
Cannot build in Android

### ISSUE THREAD

**Issue by ricechenghk** [segmentio/analytics-react-native#248]
I tried to build in Android but seeing this error.
Anyone help please? Thanks.

![Screenshot 2020-12-15 at 7 08 07 PM](https://user-images.githubusercontent.com/6051908/102207357-f05f5580-3f08-11eb-9ade-e952dd15e17c.png)

**Comment by bsneed** [comment]
looks like your app is depending on 17.5.0 and we're looking for 17.2.1?  is that right?  I can make a ticket to loosen the version for the android library, but in the meantime you should be able to use 17.2.1.
