### ISSUE TITLE
Can't launch IOS build

### ISSUE THREAD

**Issue by YevheniiShabelnykkk** [segmentio/analytics-react-native#249]
Hello! 
Could someone help with a problem, please?

At first, we get this issue https://github.com/segmentio/analytics-react-native/issues/226
To fix this issue we upgrade the library as mentioned in the link above. But then, we get this crash<img width="517" alt="Screenshot 2020-12-18 at 17 54 06" src="https://user-images.githubusercontent.com/53472115/102634450-876f1c00-415a-11eb-8e6f-864041086f41.png">

And to fix this we should downgrade the library and this like a vicious circle.

Can someone help with this, please?

**Comment by FadiAboMsalam** [comment]
Same issue here as well when using segment-amplitude
any fix for it ?

**Comment by IsmaelMiber** [comment]
same issue any fixt for it?

**Comment by IsmaelMiber** [comment]
@FadiAboMsalam @YevheniiShabelnykkk 

Guys I have fixed it
you will go to podfile and wrote this code first: 
`  pod 'Segment-Amplitude', :git => "https://github.com/IsmaelMiber/analytics-ios-integration-amplitude.git"
`

**Comment by alexpluto** [comment]
@IsmaelMiber thanks of this! I also have an open ticket with Segment (as a paying customer) and they said this should be fixed very soon. I will ask for another update and share it here. Naturally, we would ideally wait until they push the fixes to this repo.

**Comment by IsmaelMiber** [comment]
@alexpluto You are welcome, great news, waiting for theses fixes <3

**Comment by bsneed** [comment]
You need to do an update of your pod repos, typically the `--repo-update` flag will do it.  The fix was made to that integration back in October.

**Comment by bsneed** [comment]
Reopened, as I think there's some broader issue after looking at @IsmaelMiber 's change.

**Comment by bsneed** [comment]
Fixed in Segment-Amplitude 3.2.4.  Please update your pod.  Reopen this issue if there are still concerns.
