### ISSUE TITLE
[Android] Error on setup: "Method addObserver must be called on the main thread"

### ISSUE THREAD

**Issue by cristeahub** [segmentio/analytics-react-native#255]
Hi,

After upgrading one of my other dependencies in my android app (namely Stripe Android SDK from 10.x to 16.x) I surprisingly encountered an error in this SDK. Note that one of the changes from this huge jump is that the StripeSDK has migrated to AndroidX.

When i do `analytics.setup(MY_WRITE_KEY, {some: 'options'}` I get a redbox in my app with the text `writeKey must not be null or empty`.

I have debugged and verified that the writeKey is indeed set correctly, so this is just a symptom and not the actual issue.

Digging further down I found that when initializing the Segment Android SDK I got the following error `Method addObserver must be called on the main thread`. This seems to be the actual issue causing my subsequent calls to `analytics` to fail due to the writeKey not being set.

The error is caught here:

https://github.com/segmentio/analytics-react-native/blob/226a9e4a5010b116d173da80ca1d335a5b7b01b9/packages/core/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalyticsModule.kt#L187-L191

This error comes from the `analytics-android` package that this package depends on. The error seems to stem from AndroidX issues, and there's even an issue on that repo for the error: https://github.com/segmentio/analytics-android/issues/725 .

This is a blocker for us now, I am asking here since we are using react native and there was no answer from the developers at the other repo. Is there a way to escalate this issue so it gets attention and gets fixed?

I found a related issue from a different vendor here: https://github.com/getsentry/sentry-android/issues/520 . This issue was about lifetime handlers, which both the original issue creator on the segment-android repo and myself use. However simply turning that off was not enough to fix the issue.

Alternatively do you know of any workarounds?

Thanks for a great library otherwise!

**Comment by wmonecke** [comment]
@cristeahub Hi there! I am currently facing the same issue with another RN library. 
Did you manage to solve your issue? :)

**Comment by cristeahub** [comment]
> @cristeahub Hi there! I am currently facing the same issue with another RN library.
> Did you manage to solve your issue? :)

There's a chain of issues here, but https://github.com/segmentio/analytics-react-native/pull/256 fixed the issue for me.

You can read more on this issue: https://github.com/segmentio/analytics-android/issues/725 and I used this patch here at one point to fix it: https://github.com/segmentio/analytics-android/issues/725#issuecomment-767069769 .

**Comment by wmonecke** [comment]
The patch says we should call `builder.experimentalUseNewLifecycleMethods(false)`.

However `builder` is created like [this](https://github.com/segmentio/analytics-react-native/blob/5a2ed9bb8b62b89c4ce557b76c7b98a91b309e27/packages/core/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalyticsModule.kt#L127):

`````
val builder = Analytics
                .Builder(reactApplicationContext, writeKey)
                .flushQueueSize(options.getInt("flushAt"))

`````

In the library that is causing the issue for me `react-native-location` there is no `builder` object.
This is why I am so confused as to where to call `experimentalUseNewLifecycleMethods(false)`.

I am very inexperienced with Java, sorry if this does not make much sense.

**Comment by cristeahub** [comment]
> The patch says we should call `builder.experimentalUseNewLifecycleMethods(false)`.
> 
> However `builder` is created like [this](https://github.com/segmentio/analytics-react-native/blob/5a2ed9bb8b62b89c4ce557b76c7b98a91b309e27/packages/core/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalyticsModule.kt#L127):
> 
> ```
> val builder = Analytics
>                 .Builder(reactApplicationContext, writeKey)
>                 .flushQueueSize(options.getInt("flushAt"))
> ```
> 
> In the library that is causing the issue for me (`react-native-location`) there is no `builder` object.
> This is why I am so confused as to where to call `experimentalUseNewLifecycleMethods(false)`.
> 
> I am very inexperienced with Java/Kotlin, sorry if this does not make much sense.

You'll have to take that up with the library authors. I'm not familiar with that library.

**Comment by wmonecke** [comment]
I have migrated to another library since `react-native-location` seems abandoned and the authors are not addressing issues or requests to transfer the library to other community members.

Thank you for your help anyways!

**Comment by prayansh** [comment]
Hi All! just wanted to call out that we have shipped the change to fix the main issue in `analytics-react-native v1.4.4`
