### ISSUE TITLE
Using two writeKeys for different sources

### ISSUE THREAD

**Issue by anthonychung14** [segmentio/analytics-react-native#261]
Hello 👋 ,

We're piloting a new analytics system on React Native, but also want to maintain our current system.

Is it possible to have TWO write keys writing to different sources within the same application?

My preliminary testing on shows that this is not the case. If I'm correct, is there another method you recommend for achieving parallel analytics streams from the same device?

**Comment by bsneed** [comment]
Hi @anthonychung14, that's not currently possible unfortunately.  We're working on some new stuff that would allow this, but it's still a ways out.

**Comment by anthonychung14** [comment]
thanks!
