### ISSUE TITLE
amplitude sessionId -1

### ISSUE THREAD

**Issue by KJoobin** [segmentio/analytics-react-native#263]
i'm using analytics-react-native for analytics,

i want to use amplitude session property but it's not working in my app..( all user session value = -1 )

how to working sessionId? 
anything set up for sessionId? 

 "@segment/analytics-react-native": "1.3.1",
 "react-native-appsflyer": "^6.0.50",

**Comment by bsneed** [comment]
Please see Amplitude's docs and usage.  https://segment.com/docs/connections/destinations/catalog/amplitude/#sessionid

**Comment by IsmaelMiber** [comment]
@KJoobin 
Did you fix it or know why this issue happened?

**Comment by KJoobin** [comment]
@IsmaelMiber 
yes, i should set session Id directly,
`
analytics.track
  event,
  properties,
  {
      integrations: {
        Amplitude: {
         // like this
          session_id: sessionId,
        },
      },
    },
  );
`
