### ISSUE TITLE
@segment/react-native-appsflyer depends on outdated version of com.appsflyer:segment-android-integration

### ISSUE THREAD

**Issue by shzhng** [segmentio/analytics-react-native#270]
If I'm understanding [this](https://github.com/segmentio/analytics-react-native/blob/master/packages/integrations/integrations.yml#L78) correct, the android version of `@segment/react-native-appsflyer` is being built with a very outdated version of `com.appsflyer:segment-android-integration` at `1.19`. The latest version of that library is [`6.1.4`](https://search.maven.org/artifact/com.appsflyer/segment-android-integration/6.1.4/jar). 

This renders `@segment/react-native-appsflyer` incompatible with current versions of appsflyer (which everyone will now need to update to accommodate iOS 14 changes). It now results in this error:
```
java.lang.NoSuchMethodError: No virtual method startTracking(Landroid/app/Application;)V in class Lcom/appsflyer/AppsFlyerLib; or its super classes (declaration of 'com.appsflyer.AppsFlyerLib' 
```

`startTracking` has since been removed from AppsFlyer altogether.

I've managed to get around this by manually dropping in
```gradle
    implementation "com.appsflyer:segment-android-integration:6.1.4"
```
into `app/build.gradle` to override the version declared by `@segment/react-native-appsflyer`.

What's the right way to fix this? Should this library be updated to reflect the latest version, or is your recommended approach to have every integration doing what I've done?

**Comment by ivansnek** [comment]
Same issue here:
Versions used: 
- "@segment/analytics-react-native": "^1.3.2"
- "@segment/analytics-react-native-appsflyer": "^1.3.2"

@shzhng any changes you're using the library: https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin to install the native SDKs? or are you manually installing each native SDK?

Thanks

**Comment by shzhng** [comment]
> @shzhng any changes you're using the library: https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin to install the native SDKs? or are you manually installing each native SDK?

Yes also using this library. I imagine if you're using react-native, segment and appsflyer, then most of us are probably in the same boat.

**Comment by bsneed** [comment]
thanks @shzhng!  I have a CI job pending that tries to build everything with that version.  will report back here with either a PR or more questions if needed.

**Comment by shzhng** [comment]
thanks for the quick fix!

**Comment by bsneed** [comment]
no problem!
