### ISSUE TITLE
Build failed with Internal error: Symbol file with package cannot be empty.

### ISSUE THREAD

**Issue by watadarkstar** [segmentio/analytics-react-native#273]
**Description**

When running an android build release for our React Native app using bitrise I started getting this error as of 1 days ago (Feb 9th). It was working before and we made no changes to segment in the last 1 day.

**Log**

```
> Task :segment_analytics-react-native:processReleaseManifest
> Task :segment_analytics-react-native-amplitude:generateReleaseResValues
> Task :segment_analytics-react-native-amplitude:generateReleaseResources
> Task :segment_analytics-react-native-amplitude:packageReleaseResources
> Task :segment_analytics-react-native-amplitude:parseReleaseLibraryResources
> Task :segment_analytics-react-native-amplitude:processReleaseManifest
> Task :rn-fetch-blob:bundleLibCompileRelease
> Task :segment_analytics-react-native-amplitude:generateReleaseRFile FAILED
> Task :segment_analytics-react-native:generateReleaseRFile
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':segment_analytics-react-native-amplitude:generateReleaseRFile'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Internal error: Symbol file with package cannot be empty. File located at: /Users/vagrant/git/node_modules/@segment/analytics-react-native/android/build/intermediates/res/symbol-table-with-package/release/package-aware-r.txt
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings
BUILD FAILED in 1m 1s
328 actionable tasks: 328 executed
Build task failed, error: exit status 1
```

**Code**

Inside `package.json`:

```
"react-native": "0.63.4",
...
"@segment/analytics-react-native": "1.1.0",
"@segment/analytics-react-native-amplitude": "1.1.0",
```

Inside `android/app/build.gradle`:

```
implementation project(':@segment_analytics-react-native')
```

inside `android/build.gradle`:

```
buildscript {
    ext {
        googlePlayServicesVersion = "+"
        firebaseVersion = "+"

        buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
    }
```

**Comment by bsneed** [comment]
hard to say; something must've changed somewhere, as we can't update your libraries remotely or anything.  best bet is to attempt to move up to the current version of the library.  there's too much stuff in play to troubleshoot an older version and compatibilities.  please reopen if that doesn't address the issue.

**Comment by watadarkstar** [comment]
@bsneed Sure I can attempt to upgrade the library to the latest

**Comment by watadarkstar** [comment]
@bsneed While I got your attention, do you think I need to lock this to a specific version:

```
implementation project(':@segment_analytics-react-native')
```

Maybe gradle updated that library

**Comment by bsneed** [comment]
I don't think you'd need to since it's all bundled together.  that wouldn't update unless your analytics-react-native lib updated.  I could be misunderstanding what you mean or what that's from though.

**Comment by watadarkstar** [comment]
@bsneed I think I'm going to try removing:

```
implementation project(':@segment_analytics-react-native')
```

from build.gradle as you are right its all packaged together now inside node_modules but when we added this library 2 years ago on 1.1.0 it required us to run `react-native link` which probably added this line which downloads the package from gradle servers I think.

**Comment by bsneed** [comment]
sounds good, fingers crossed!

**Comment by watadarkstar** [comment]
@bsneed and any future readers. I was able to fix this by removing:

```
implementation project(':@segment_analytics-react-native')
```

inside my build.gradle file

**Comment by bsneed** [comment]
WOO!!! 💯
