### ISSUE TITLE
writeKey must not be null or empty

### ISSUE THREAD

**Issue by gursesl** [segmentio/analytics-react-native#274]
When launching on Android emulator (MacOS), the app crashes with the message below. Works on iOS.

Any clues?

![image](https://user-images.githubusercontent.com/2237424/107970339-fe6c3980-6f7e-11eb-9d70-e095762953e2.png)

RN code:

```
analytics.setup('writeKey_XXXXXX', {
        // Record screen views automatically!
        recordScreenViews: true,

        // Record certain application events automatically!
        trackAppLifecycleEvents: true,

        android: {
          flushInterval: 60000, // 60 seconds
          collectDeviceId: true,
        },

        ios: {
          trackAdvertising: true,
          trackDeepLinks: true,
        },

      });

```

Library versions:

```
"react-native": "^0.63.4",
"@segment/analytics-react-native": "^1.4.1",
```

**Comment by VladosDosvidos** [comment]
I received the same issue after update some dependencies in the build.gradle file. And after rollback, it’s gone.

**Comment by bsneed** [comment]
Unfortunately, I don't really know what this could be.  Best bet would be to open your project in Android studio, run it from there and see if it provides anymore information.  Please reopen this ticket if you feel it's necessary after looking at the Android Studio output.

**Comment by NiklasMencke** [comment]
same problem since updating react-native-purchases to 
    "react-native-purchases": "^4.1.1",

**Comment by grifotv** [comment]
I started getting this error when upgrading the [Zendesk Messaging SDK for Android](https://developer.zendesk.com/documentation/zendesk-web-widget-sdks/sdks/android/release_notes/) from `zendesk.messaging:messaging-android:1.1.0` to `zendesk.messaging:messaging-android:2.1.0`.

**Comment by grifotv** [comment]
I upgraded to `@segment/analytics-react-native` to `1.4.4` as [described here](https://github.com/segmentio/analytics-react-native/issues/291#issuecomment-828659930) and everything works as expected.
