### ISSUE TITLE
Calling setup() multiple times

### ISSUE THREAD

**Issue by pavermakov** [segmentio/analytics-react-native#275]
I have 2 sources: one for dev and the other for prod. Is it possible to switch sources on the fly? 

I have tried calling setup(), but had no luck because of this code:
![Снимок экрана 2021-02-23 в 17 29 11](https://user-images.githubusercontent.com/10779996/108859766-9bbe1200-75fe-11eb-8471-252db90ff0c8.png)

Thank you in advance!

**Comment by bsneed** [comment]
Hi @pavermakov, it's not currently possible to switch sources on the fly unfortunately.  Needs an app restart because of the singleton.  We're looking at changing this in the near future though.
