### ISSUE TITLE
identify user should has type string | null

### ISSUE THREAD

**Issue by thongncvn** [segmentio/analytics-react-native#278]
https://github.com/segmentio/analytics-react-native/blob/e2b6bc820c0613c8bdf124a1f52633cee2bc0669/packages/core/src/analytics.ts#L304

Identify supports passing null to `user`, so can we modify its type to match?

P/s: People already created a PR #65 for this but closed. I think PR #147 hasn't fixed this typescript issue, as @bsneed stated.

**Comment by bsneed** [comment]
You are totally correct.  Sorry for the miss on that.  I'll look at that this week and get it resolved.

**Comment by bsneed** [comment]
Fixed in 1.4.2, which should be on NPM shortly.
