### ISSUE TITLE
AppsFlyer integration target iOS 11

### ISSUE THREAD

**Issue by magrinj** [segmentio/analytics-react-native#279]
It seems that integration target iOS 11 or higher, but segment base project is targeting iOS 10.

After linking `@segment/analytics-react-native` everything is building properly, but when I add `@segment/analytics-react-native-appsflyer` I got an error telling me there is a mismatch between my platform version in my Podfile and the one of AppFlyer integration.

So, I try to put the platform to 11 in my Podfile, and all the linking Pods seems to be broken and building fail on iOS.

After downgrading `@segment/analytics-react-native-appsflyer` Podfile to iOS 10 everything is building properly.

So my question is, is the platform version set to 11 in integration a need or it ca be downgrade ?

**Comment by magrinj** [comment]
The build fail with iOS 11 doesn't seems to be linked with segment libraries, but more related to `react-native-unimodules` and `expo` with a deployment target set to 11 without the possibility to add `use_frameworks!`.
However I think if it's not a need, deployment target should be the same between segment analytics and integrations.

**Comment by bsneed** [comment]
The integrations build as a really thin wrapper on their native counterparts and use the same template for each pod file.  I suspect there might be a downstream dependency for one or more integration that requires 11, but would need to look through them all.  It could also be that at one point, Analytics-iOS needed iOS 11, and this setting just didn't get changed.  If setting it to 10 works for you, continue to do that.  I'll leave this issue open and when I roll a follow on release, I'll investigate this some more.  Thanks for noticing that detail.

**Comment by bsneed** [comment]
Well, the good news is, I released from the wrong branch so it failed and I'll do this now. haha

**Comment by magrinj** [comment]
@bsneed Haha ok thanks for your help ! 
After more investigation, the build fail came from bad configuration inside `project.pbxproj`.
This file was targeting iOS 10 (`IPHONEOS_DEPLOYMENT_TARGET` key) and my Podfile was targeting iOS 11, of course the build error was totally relevant and I don't lost 3 hours finding this haha

**Comment by bsneed** [comment]
done in 1.4.3 coming shortly.

**Comment by magrinj** [comment]
@bsneed Thanks !
