### ISSUE TITLE
Sending Segment Anonymous ID to the Branch SDK

### ISSUE THREAD

**Issue by pcooney10** [segmentio/analytics-react-native#28]
Hi folks,

Thank you for making this lib, glad to see an official React Native lib from the Segment team 😄 !

I have previously used [leoilab/react-native-analytics-segment-io](https://github.com/leoilab/react-native-analytics-segment-io), which seemed to be the leading RN implementation of Segment for a while.

Has anyone had success sending the Segment Anonymous ID to the Branch SDK using this library? Or is that not possible since the Segment SDK is set up on the JavaScript side of things?

The [documentation](https://docs.branch.io/pages/integrations/segment/#pass-segment-anonymous-id) on the Branch website is a little sparse/unclear for React Native, but essentially the branch sdk needs the user's anonymous id **_before_** the branch sdk is set up, and I am not sure if that is possible using this library. The branch side of things is set up on the native end, while it seems Segment is set up on the JS side of things. As such, I am not sure if it's possible to get the value for  `[[SEGAnalytics sharedAnalytics] getAnonymousId]` while using this implementation.

Here are the relevant excerpts:

**iOS:** 
_Inside didFinishLaunchingWithOptions_
```
Branch *branch = [Branch getInstance];
[[Branch getInstance] setRequestMetadataKey:@"$segment_anonymous_id" value:[[SEGAnalytics sharedAnalytics] getAnonymousId]];
```

**Android:**
_Before you initialize in your Application#onCreate or Deep Link Activity's #onCreate._
```
Branch.getInstance().setRequestMetadata("$segment_anonymous_id", com.segment.analytics.Analytics.with(this).getAnalyticsContext().traits().anonymousId());
...
Branch.initSession(...);
```
_In the above snippet, this is the Activity context._

I opened an [issue](https://github.com/BranchMetrics/react-native-branch-deep-linking/issues/379) in the react-native-branch-deep-linking repo where I go into a little more detail, but wanted to post here since it's obviously related to this library.

Thank you in advance !

**Comment by pcooney10** [comment]
I believe the answer lies somewhere here: `analytics.useNativeConfiguration()`
[react-native/#native-configuration](https://segment.com/docs/sources/mobile/react-native/#native-configuration)
[react-native/#can-i-also-use-the-native-analytics-api](https://segment.com/docs/sources/mobile/react-native/#can-i-also-use-the-native-analytics-api-)

Sorry for posting before fully reading the docs 😅, closing this issue for now.

As an aside - is there a git repo where [these docs](https://segment.com/docs/sources/mobile/react-native/) are maintained?  There's a few minor typos / broken links I would fix ! Thanks.

**Comment by f2prateek** [comment]
@pcooney10 yes - unfortunately the repo is closed source, but if you let us know something is broken (either here or via contacting support), we can get it fixed!

**Comment by pcooney10** [comment]
@f2prateek ok will do ! Going to try out setting things up on the native side, will report back with my findings 😁
