### ISSUE TITLE
Argfile not found:  PATH/android/segment_analytics-react-native_debug

### ISSUE THREAD

**Issue by jeftarmascarenhas** [segmentio/analytics-react-native#289]
I have a error in the version:  1.1.0 of `@segment/analytics-react-native`

About the error:
```
> Task :@segment_analytics-react-native:compileDebugKotlin FAILED
w: Argfile not found: PATH/android/segment_analytics-react-native_debug
e: PATH/node_modules/@segment/analytics-react-native/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalyticsModule.kt: (143, 51): Type mismatch: inferred type is String? but String was expected

w: Argfile not found: PATH/android/segment_analytics-react-native_debug
```
I don't know as to solve that problem.
I didn't update of module because when I do the update crash my app on the iOS.

**Comment by CapitanRedBeard** [comment]
Also getting this error today, also on `1.1.0` and it was working fine before. Only happens on Android

**Comment by neerajbuccam** [comment]
I am facing the same issue with `0.1.0-beta.0`.

I have also tried upgrading to the latest version, but i get the response shown below and it exposes the writeKey as well.
![image](https://user-images.githubusercontent.com/13030805/113248241-28cd4880-92da-11eb-9535-1a3d57efa308.png)

I also found this similar issue with exposing writeKey, which was fixed later. https://github.com/segmentio/Analytics.NET/issues/98

**Comment by neerajbuccam** [comment]
Anyone has got any solution for this issue?

**Comment by mloisotto** [comment]
I'm facing the same error on version 1.3.1.  Error:
`> Task :segment_analytics-react-native:compileDebugKotlin FAILED
e: /Users/xxxxx/workspace/MyApp/node_modules/@segment/analytics-react-native/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalyticsModule.kt: (124, 51): Type mismatch: inferred type is String? but String was expected
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions`

**Comment by neerajbuccam** [comment]
this is the error while building on version 1.2.1

`
> Task :@segment_analytics-react-native:compileDebugKotlin
w: Argfile not found: C:\DATA\app\android\segment_analytics-react-native_debug
w: C:\DATA\app\node_modules\@segment\analytics-react-native\android\src\main\java\com\segment\analytics\reactnative\core\RNAnalyticsModule.kt: (70, 40): 'versionCode: Int' is deprecated. Deprecated in Java
w: C:\DATA\app\node_modules\@segment\analytics-react-native\android\src\main\java\com\segment\analytics\reactnative\core\RNAnalyticsModule.kt: (255, 62): Unchecked cast: Map<Any!, Any!> to Map<String, Any>
`

**Comment by neerajbuccam** [comment]
Build is failing in the versions older than 1.2.1 among the once i tried a few.
Anyways, we are using a old version 0.1.0-beta.0

I have managed to get the builds working with a workaround and a version change of a dependency `analytics-react-native` is using.

I have changed version of analytics plugin in the dependency list in file `node_modules\@segment\analytics-react-native\android\build.gradle`

from:
    `api 'com.segment.analytics.android:analytics:4.9.1-beta'`

changed to (working fine with 4.9.0):
    `api 'com.segment.analytics.android:analytics:4.9.0'`

this has changed with the commit made [here](https://github.com/segmentio/analytics-react-native/commit/8dbadad955199bf58e2490c110101a71696b20e9#diff-5f4a638b3bedba96c3d30df60fbcfc33cd9cc6ca8a2babd7df6f068ec1d59ea5)

I have a workaround which works for now and i hope the segment team will get this fixed soon.

**Comment by alanjcharles** [comment]
Hi Everyone, 

Can I ask what version of React Native you are using? We found a similar issue with react-native 0.64 and have merged a change. We will push a new release early next week. Otherwise, we generally recommend updating your `analytics-react-native` library whenever possible as there have been some pretty fundamental changes in the last year.

**Comment by alanjcharles** [comment]
please feel free to reopen if the issue persists on `analytics-react-native 1.4.4`
