### ISSUE TITLE
Need a way to get IDFA / Ad ID / Segment Anon ID from the RN Client

### ISSUE THREAD

**Issue by manbearshark** [segmentio/analytics-react-native#29]
Customers that use our personalization API with Personas need to be able to access the anon identifiers - this is really difficult to do right now.  In the case of IDFA this means loading another third party library with additional native libraries which customers do not like to do.  For our anon id, I cannot see a way to retrieve that via the RN API which is also going to be an issue for customers.

**Comment by rborn** [comment]
Hi everyone, is there any chance to add this to the RN module? It's needed for integrations with other providers that send server data and need to be able pass the attributed id.
Thank you

**Comment by rborn** [comment]
This is even more important for AppsFlyer so we can use it for 3rd parties integrations.

**Comment by evillemez** [comment]
We are finding a huge need for this, and having difficulty with other options.  Since the SDKs are already getting this value internally, it would be hugely helpful if this library could just expose it to the app.

**Comment by supernayan** [comment]
Bump
