### ISSUE TITLE
Android crash: Attempt to invoke method 'int java.langCharSequence.length()' on a null object reference

### ISSUE THREAD

**Issue by gursesl** [segmentio/analytics-react-native#291]
Possibly related to empty writeKey issues #274 and #290.

Reference code block: https://github.com/segmentio/analytics-android/blob/master/analytics/src/main/java/com/segment/analytics/Analytics.java

It seems isEmptyOrBlank doesn't know how to process a null object. Why the writeKey being passed is null is another question.

```
public Builder(@NotNull Context context, @NotNull String writeKey) {
    if (!hasPermission(context, Manifest.permission.INTERNET)) {
        throw new IllegalArgumentException("INTERNET permission is required.");
    }
    application = (Application) context.getApplicationContext();
    if (isEmptyOrBlank(writeKey)) {
        throw new IllegalArgumentException("writeKey must not be empty.");
    }
    this.writeKey = writeKey;
}
```

<img width="394" alt="Screen Shot 2021-03-29 at 4 15 22 PM" src="https://user-images.githubusercontent.com/2237424/112894547-ff2dda80-90a9-11eb-8bc7-1e67bc1b064d.png">

Any help is highly appreciated.

**Comment by prayansh** [comment]
Hi @gursesl could u attach a snippet of how you are initialising Segment? im suspecting there is an issue present there

**Comment by gursesl** [comment]
@prayansh - thanks. Here's the initialization code:

```
import { Platform } from 'react-native';
import analytics from '@segment/analytics-react-native';
import Amplitude from '@segment/analytics-react-native-amplitude';
import Bugsnag from '@segment/analytics-react-native-bugsnag';
import Branch from '@segment/analytics-react-native-branch';

const SEGMENT_WRITE_KEY = 'XXXXXXX';

class Analytics {
  static async init() {
    // Segment.io
    this.segment = await analytics.setup(SEGMENT_WRITE_KEY, {
      using: [Amplitude, Branch, Bugsnag],
      // Record screen views automatically!
      recordScreenViews: true,
      // Record certain application events automatically!
      trackAppLifecycleEvents: true,

      android: {
        flushInterval: 60000, // 60 seconds
        collectDeviceId: true,
      },
      ios: {
        trackAdvertising: true,
        trackDeepLinks: true,
      },
    });
  }

  static setCurrentScreen = async screen_name => {
    return this.analytics.screen(screen_name, {});
  };

  static logEvent = async (eventName, propertyObject = {}) => {
    return this.analytics.track(eventName, propertyObject);
  };

}

export default Analytics;
```

**Comment by prayansh** [comment]
@gursesl i just tried out your snippet in my test app, and everything seems to work fine. I was unable to replicate the issue, unless i actually passed a `empty/null` value for `writeKey`.

I am unsure as to why your app is failing to that error. If its possible, could you kindly create and link us to a sample test app that replicates the same issue, because without such an example we are unable to move forward. Thanks 😄

**Comment by gursesl** [comment]
@prayansh - yeah, cool!

In the meantime, here's a hunch/theory: Looks like the presence of certain dependent libraries may trigger the issue. Your test app doesn't have my app's dependencies and therefore it works ok. However, please check #290 where the issue is seemingly triggered by the react-native-purchase library. In my app, we have hundreds of dependencies and one of them may well be the cause of the crash.

Thoughts?

**Comment by prayansh** [comment]
That would be pretty insane that a certain dependency can cause this issue 😅 . I will give it a whirl and reply on this thread if that theory is true. Thanks for letting me know about it!

**Comment by a613** [comment]
What version of segment were you using when you saw this @gursesl ? I am seeing it with segment 1.3.0 when I try to integrate firebase into my RN app. The app works fine on iOS but crashes exactly like you showed in the screenshot. Thanks.

**Comment by gursesl** [comment]
@a613 - we've seen the issue in both 1.3.x and 1.4.x. We also use Firebase and myriad of other dependencies.

I am sure Segment is a great team - obviously their product works well on Android and iOS native platforms. I am also confident this might end up being a small issue or a user error, caused by our lack of understanding. But our experience with the RN product has been mixed. We've tried various ways to resolve the issues for Android and we've opened two issues here. Both were dismissed and closed with no plausible explanation or further exploration. We've now given up on Segment and instead  are going straight to Firebase Analytics, Amplitude and Mixpanel. So far their RN libraries have worked with no issues on both platforms.

**Comment by a613** [comment]
I added logging in `RNAnalyticsModule.kt` and showed that indeed the write key is null:

```kotlin
println(getResourceString(reactApplicationContext, "analytics_write_key"))
```

The question remains WHY is it null, when the write key is being correctly passed as the first argument to `segment.setup()`.

**Comment by a613** [comment]
I added logging in `RNAnalyticsModule.kt` and showed that indeed the write key is null:

```kotlin
println(getResourceString(reactApplicationContext, "analytics_write_key"))
```

The question remains WHY is it null, when the write key is being correctly passed as the first argument to `segment.setup()`.

I next added the write key to `android/app/src/debug/res/values/config.xml` to see if it would be picked up at all, and yes it was - the debug log mentioned above correctly prints out the key. However, then the app starts up with a new error:

> Duplicate analytics client created with tag: \<secret write key\>. If you want to use multiple Analytics clients, use a different writeKey or set a tag via the builder during construction.

<img src="https://user-images.githubusercontent.com/5733420/116161911-eb2dc680-a6b1-11eb-9681-f2bb0512173d.png" width="250" />

And that to me is a good clue as to what's happening. Somehow there are two stacks being started, one that's looking for the key in Android resources, and one that's looking for the key to come from JS/TS.

@prayansh given that info, do you now have enough information to suggest a way out for us and anyone who comes after? Thanks.

**Comment by prayansh** [comment]
👋  @a613 & @gursesl We just released a new version of the react-native library (`v1.4.4`), that should fix these `null` writeKey issues. Please do try it out, and let us know if that works for you :)
