### ISSUE TITLE
analytics + firebase. in_app_purchase event is missing

### ISSUE THREAD

**Issue by RohovDmytro** [segmentio/analytics-react-native#296]
I might missing something, but I can see in_app_purchase event in Google Analytics 4 webui, but it's not received by segment.

![image](https://user-images.githubusercontent.com/1548235/114016998-2340a700-9874-11eb-90be-f62c3c41fb9e.png)

Another thing is that I have these packages.

![image](https://user-images.githubusercontent.com/1548235/114017065-38b5d100-9874-11eb-8c7b-896c00815d87.png)

**Comment by alanjcharles** [comment]
@RohovDmytro Can you try changing `using:[firebaseSegment]` to `using: [firebase]`? You also have to import the dependency in the file you are using to initialize the analytics library. You can follow this guide in the readme to set up Firebase: 

https://github.com/segmentio/analytics-react-native#packaging-device-mode-destination-sdks

From there, you can use Firebase's DebugView to validate your events: 

https://firebase.google.com/docs/analytics/debugview

**Comment by alanjcharles** [comment]
Closing for now, please let me know if this persists
