### ISSUE TITLE
RNAnalytics not found

### ISSUE THREAD

**Issue by migue1s** [segmentio/analytics-react-native#30]
I am consistently getting a `@segment/analytics-react-native-mixpanel/ios/main.m:10:9: 'RNAnalytics/RNAnalytics.h' file not found`when adding the mixpanel integration. I am currently integratitng the analytics-react-native library without cocoapods.

I have followed the steps in the readme and #17, running the project without the mixpanel integration will correctly send data to segment but not to mixpanel.

**Comment by Jonovono** [comment]
@migue1s did you solve this? Having the same issue

**Comment by migue1s** [comment]
I did not manage to solve it @Jonovono. The project I'm working on had some previous setup in segment to forward data to mixpanel and it worked (partially) without the integration.

**Comment by caroaguilar** [comment]
Look at https://github.com/segmentio/analytics-react-native/issues/17 maybe that works for you

**Comment by SnidelyWhiplash** [comment]
Same with Firebase, stuck all day on this.

I am not using CocoaPods because everything breaks with just about every RN lib I have when trying to do so. 🙄

This line from the README worries me a bit:
>We do not support sending data to bundled, device-mode integrations outside of Cocoapods.

Does that mean it's _impossible_ for me to use Firebase without somehow figuring out how to integrate Pods into my project? Is that what's causing this error, or..?

**Comment by powersjcb** [comment]
+1 for Amplitude, tried a bunch of the suggested fixes, nothing seems to be working.

**Comment by powersjcb** [comment]
I just uncovered more specific behavior about this failure.

- Building with both the base package and the plugin: Failure - RNAnalytics not found
- Building with just the base package: Success
- Building with the plugin after having first compiled the base package: Success.

I don't know the inner workings of how iOS apps are compiled, but I hope this helps someone figure out a workaround fix for this.

**Comment by CapitanRedBeard** [comment]
Seems no one can get any integrations to work. 

Personally I'm trying to get the AppsFlyer integration working. I've gotten the core RNAnalytics project integrated and I pull down the Analytics SDK via Carthage and it works great. However I get this error after installing the integration and linking it

![image](https://user-images.githubusercontent.com/5445860/58134656-56281600-7bdc-11e9-8f0b-bdca70e84558.png)

I've tried adding the RNAnalytics search path to my Library search paths and also just adding it into the RNAnalyticsIntegration_* project. However it fails every time. 


@fathyb @f2prateek @Jack-Gill-TH @williamgrosset @caroaguilar @ajmath Do the integrations actually work? Any suggestions?

**Comment by CapitanRedBeard** [comment]
### Segment Integrations only work for CocoaPods installation.

There might be a hack you can do to get them to work for your specific setup, but out of the box manual or Carthage installations are going to fail. 

Disappointed in this product and the technical decisions to only support a 3rd party dependency manager and not the default manual installation.
If you're from the Segment tech team and made this decision or know why this decision was made I would love to hear some the reasoning. 

Until then Segment is not in a state where I'd recommend it to anyone. Disappointing tech decisions usually lead to other disappointing tech decisions.

**Comment by YahiaYasLife** [comment]
I m still facing this issue with iOS.
Anyone can help?

**Comment by cmcewen** [comment]
Adding `s.dependency 'RNAnalytics'` to the integration's podspec file (in my case `RNAnalyticsIntegration-Firebase.podspec`) fixes this error, but then I'm left with another one:

`...@segment/analytics-react-native-firebase/ios/main.m:11:9: 'Segment-Firebase/SEGFirebaseIntegrationFactory.h' file not found`

I think this probably requires something similar to what Firebase does to expose public header files but I'm definitely not a CocoaPods expert: https://github.com/firebase/firebase-ios-sdk/blob/release-5.20.0/FirebaseCore.podspec#L28

**Comment by KasparPeterson** [comment]
I had the same error and I discovered that I had one line missing from Podfile:
pod 'RNAnalytics', :path => '../node_modules/@segment/analytics-react-native'

Hope that helps someone.

**Comment by giaset** [comment]
@cmcewen I'm having the same issue as you, but for the Branch integration

Added `s.dependency 'RNAnalytics'` to `RNAnalyticsIntegration-Branch.podspec` fixes one issue, but then it can't find `Segment-Branch/BNCBranchIntegrationFactory.h` :(

**Comment by YahiaYasLife** [comment]
I fixed the issue by adding `s.dependency 'RNAnalytics'` to `RNAnalyticsIntegration-Branch.podspec`
But now I m receiving an other error `'Segment-Firebase/SEGFirebaseIntegrationFactory.h' file not found`
Any idea can help ???

**Comment by AmitPandya007** [comment]
> I had the same error and I discovered that I had one line missing from Podfile:
> `pod 'RNAnalytics', :path => '../node_modules/@segment/analytics-react-native'`
> Hope that helps someone.

Is there any solutions than using "pod install" command? please share.

**Comment by AmitPandya007** [comment]
> I fixed the issue by adding `s.dependency 'RNAnalytics'` to `RNAnalyticsIntegration-Branch.podspec`
> But now I m receiving an other error `'Segment-Firebase/SEGFirebaseIntegrationFactory.h' file not found`
> Any idea can help ???

I have followed the same but did not worked for me. Will you suggest some solution please.

**Comment by jeanregisser** [comment]
One way to workaround the import not found error is to use:
```patch
-#import <Segment-Firebase/SEGFirebaseIntegrationFactory.h>
+#import <Segment_Firebase/SEGFirebaseIntegrationFactory.h>
```

According to https://github.com/CocoaPods/CocoaPods/issues/5264#issuecomment-218038678, CocoaPods needs mobule names to be c99ext identifiers that's why it turns the initial module name with a dash (invalid), to an underscore.

**Comment by emadgit** [comment]
How we can open a PR for this issue? I couldn't find the related code anywhere in this repository

**Comment by llaine** [comment]
Building without the  device-based destination SDKs solved the issue for me.

**Comment by builtbyproxy** [comment]
Sorry to bump an old issue, but I've just removed segment from my project and I was getting this issue. Specifically it's required in the `main.jsbundle` file with this line:
```
__d(function(g,r,i,a,m,e,d){"use strict";Object.defineProperty(e,"__esModule",{value:!0});var t=r(d[0]).NativeModules.RNAnalytics;if(!t)throw new Error('Failed to load Analytics native module.');e.default=t},860,[7]);
```

**The trick for me at least was to re-generate my bundle.** For whatever reason neither my XCode nor CLI was re-creating `main.jsbundle`.

In order to do this, use this command in your project directory: 
```
yarn react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios
```

Some things could change such as your `entry-file` and `bundle-output` but I hope it works for you too!

**Comment by bsneed** [comment]
@builtbyproxy no worries!  thanks for sharing! hopefully it'll help others who come across this.

**Comment by naadir-d** [comment]
With the firebase and mixpanel integration for me adding `s.dependency 'RNAnalytics' to the integration's podspec file` and  adding `pod 'RNAnalytics', :path => '../node_modules/@segment/analytics-react-native-firebase'` worked for me.
