### ISSUE TITLE
How to send `campaign` utm fields on mobile?

### ISSUE THREAD

**Issue by jamie-unmind** [segmentio/analytics-react-native#301]
Hi there,

According to [your documentation](https://segment.com/docs/connections/spec/common/#context-fields-automatically-collected), the `context.campaign.*` fields are populated automatically by Analytics JS, but not Analytics-iOS or Analytics-Android.

I wanted to first confirm that there is no automatic way with `analytics-react-native` of retrieving utm url parameters and passing them through to Segment?

If not, is it recommended to retrieve the utm parameters off a url yourself, and send them via the `context` field inside the `options` argument? Eg:

```javascript
analytics.screen(screenName, properties, { context: { campaign: { ...utmParams } } });
```

If this recommended, is there a reason why Context type has `library` as required field?
https://github.com/segmentio/analytics-react-native/blob/5a2ed9bb8b62b89c4ce557b76c7b98a91b309e27/packages/core/src/bridge.ts#L39-L44

I want this field to be auto populated by `analytics-react-native`, and it appears even if you set a value for `library.name` and `library.version` it gets overridden anyway.

**Comment by alanjcharles** [comment]
Hi @jamie-unmind, you are correct. The react-native library doesn't automatically collect UTM parameters. This method: 

`analytics.screen(screenName, properties, { context: { campaign: { ...utmParams } } });`

would be our recommended approach if you want to use Segment. However, if you're looking for Deep Linking functionality, I would recommend using an attribution partner like Appsflyer or Adjust. Please feel free to reach out to `friends@segment.com` for additional help mapping the context fields and/or to determine if there is any unexpected behavior there. The `library.name` and `library.version` should be auto-populating with  `analytics-react-native` and the version you have in your app and we haven't seen this issue reported elsewhere. Thanks!

**Comment by Moorst** [comment]
@alanjcharles it looks like the analytics.screen only support screenName and options now. How would you suggest I pass the campaign to the context? 

I essentially want to pick up utm params when a deep link is identified and pass them over to segment.

**Comment by Nehal-Zeller** [comment]
+1

**Comment by Nehal-Zeller** [comment]
@Moorst  did you find anything on it?
