### ISSUE TITLE
`context.traits` doesn't work on Android ( doesn't send events to segment )

### ISSUE THREAD

**Issue by Nsquik** [segmentio/analytics-react-native#308]
lib version: `    "@segment/analytics-react-native": "^1.4.4" `

Events on Android with `context.traits` prop doesn't get send to segment.

Example:

```js
// Android: Doesn't get send - NO ERRORS
// iOS: Gets send - NO ERRORS
analytics.track(
          'some_event',
          { property_1: 'hey123' },
          {
            context: {
              traits: {
                myTrait: 'hello',
              },
            },
          }
        )
 
// Android: Doesn't get send - **ERROR** see screenshot! 
// iOS: Gets send - NO ERRORS
analytics.track(
          'some_event',
          { property_1: 'hey123' },
          {
            context: {
              traits: null
            },
          }
        )

// Android: Gets send - NO ERRORS
// iOS: Gets send - NO ERRORS        
analytics.track(
          'some_event',
          { property_1: 'hey123' },
          {
            context: {
              timezone: "Europe/Warsaw"
            },
          }
        )

// Same as above with `screen` event        
// Android: Doesn't get send - NO ERRORS
// iOS: Gets send - NO ERRORS  
analytics.screen(
          'some_screen',
         null,
          {
            context: {
              traits: {
                myTrait: 'hello',
              },
            },
          }
        )

```
<img width="407" alt="Screenshot 2021-04-29 at 16 32 13" src="https://user-images.githubusercontent.com/46610139/116568062-77d1c200-a908-11eb-9365-aa69f83ff1e7.png">

**Comment by Nsquik** [comment]
Related to https://github.com/segmentio/analytics-android/issues/765 ??

**Comment by alanjcharles** [comment]
Hi @Nsquik there is no way to disable the auto-collection of traits in the context object of track/screen events, I'm afraid. I would reference [@prayansh 's response on #765](https://github.com/segmentio/analytics-android/issues/765) as to why this is not something we will be pursuing a fix for. Any changes to the traits object should be made with identify events moving forward.
