### ISSUE TITLE
OkHttpClient: Connection Leaked.

### ISSUE THREAD

**Issue by greengeeko32** [segmentio/analytics-react-native#309]
We are seeing the following error: 

`OkHttpClient: A connection to https://api.segment.io was leaked, Did you forget to close a response body?` 

Tested Package versions `1.1.1-beta.6` to `1.4.4` 

Changed Maven dependency version to `implementation 'com.segment.analytics.android:analytics:4.+'` to 4.9.3

Supposedly the solution is in version 4.5.0 beta 2 https://github.com/segmentio/analytics-android/releases/tag/4.5.0-beta.2.

Someone knows a possible solution.

Thank you very much in advance.

**Comment by bsneed** [comment]
Analytics-react-native only references analytics-android 4.9.3.  Use analytics-react-native 1.4.4.

**Comment by greengeeko32** [comment]
we are using `1.4.4`
