### ISSUE TITLE
Clevertap?

### ISSUE THREAD

**Issue by Jonovono** [segmentio/analytics-react-native#31]
Is there a library for clevertap?

**Comment by f2prateek** [comment]
@fathyb looks like we missed one https://segment.com/docs/destinations/clevertap/

Is there a way we can support these without having to add an adapter in our code each time?

**Comment by Jonovono** [comment]
@f2prateek any plans to add it? i'd love to move over to this library once it's added!

**Comment by f2prateek** [comment]
No immediate plans, but if you sent a PR following an existing integration as an example, that would expedite it :)

**Comment by Jonovono** [comment]
Can you help point me in the right direction? I can't seem to find the source for the existing integrations. Would they be located at -> https://github.com/segmentio/analytics-react-native-amplitude for example?

Any help would be great, it's the only thing stopping me from switching over to this repo!

**Comment by f2prateek** [comment]
CelverTap maintains the integrations in their own repos - [here](https://github.com/CleverTap/clevertap-segment-ios) and [here](https://github.com/CleverTap/clevertap-segment-android).
