### ISSUE TITLE
[docs] Clarify how segment firebase integration works with events that are automatically collected via firebase analytics

### ISSUE THREAD

**Issue by RohovDmytro** [segmentio/analytics-react-native#319]
So we have this list of events that are automatically collected via GA:
https://support.google.com/analytics/answer/9234069?hl=en

I'm having a really hard time understanding, if these events should be automatically detected by segment and appear in my debug view?

In other words, do setting up `@segment/analytics-react-native` & `@segment/analytics-react-native-firebase` make GA events from the above link automagically appear in segment dashboard?

**Comment by bsneed** [comment]
No, the segment dashboard won't show any modifications to events that go to a destination via device mode.

So if you setup analytics-react-native-firebase, they'll be going straight to firebase.  They will still show up in the segment dashboard/debugger, but in their original form, and NOT in the way they would appear in GA.

**Comment by RohovDmytro** [comment]
@bsneed , dear Brandon, I've spend 10+ hours trying to figure out how to properly set up segment & firebase integration.

But I still do NOT see standard firebase events appearing in segment dashboard. So AFAICT the mobile devices does NOT send them, despite I've configured `@segment/analytics-react-native` & `@segment/analytics-react-native-firebase`.

1. I've installed `@segment/analytics-react-native`
2. i've installed `@segment/analytics-react-native-firebase`

I've initialized segment analytics.

````
import firebase from '@segment/analytics-react-native-firebase';

const initializeSegment = async () => {
  const SEGMENT_KEY = "...";
  const opts = {
    using: [firebase],
    recordScreenViews: false,
    trackAppLifecycleEvents: true,
    android: {
      flushInterval: 30000, // 60 seconds
      collectDeviceId: true,
    },
    ios: {
      trackAdvertising: false,
      trackDeepLinks: true,
    },
  };

  await analyticsSegment
    .setup(SEGMENT_KEY, opts)
    .then(() => console.log('enabled segment'))
    .catch((err) => console.error('Something went wrong', err));
};
````

Please, any way I can find some help? I'm no more frustrated, I'm in the doom of despair :) Thank you!

**Comment by alanjcharles** [comment]
@RohovDmytro when a Destination is connected in Device Mode Segment hands the events off to its SDK which make the actual network requests. Your "native" firebase events won't be sent to Segment. Segment is essentially initializing Firebase for you, giving you access to its native functionality and handing off _Segment_ events to it. For more assistance I would recommend reaching out to friends@segment.com they will be able to get you up and running :)  

PS You can implement Firebase's DebugView to validate events but you need to validate them in Firebase, not Segment. Support can also offer guidance there.

**Comment by RohovDmytro** [comment]
@alanjcharles , I appreciate deeply you commenting on this closed issue. Thanks.

I find this contradicting:
> Your "native" Firebase events won't be sent to Segment.

& 

> They will still show up in the segment dashboard/debugger

As I understand @bsneed he's saying events from this list (https://support.google.com/analytics/answer/9234069?hl=en) should appear in segment dashboard after setting things up (2 libs mentioned above).

**Comment by bsneed** [comment]
```As I understand @bsneed he's saying events from this list (https://support.google.com/analytics/answer/9234069?hl=en) should appear in segment dashboard after setting things up```

@RohovDmytro No, that's not I was saying.  Let me try to be more clear.

if you call `analytics.track("hello")` for example. You're sending an event to Segment.  If you have the firebase device mode destination set up in your application, it will then also go to firebase directly.  The transforms firebase does to get events into GA4 aren't known to us.  So, the event, when you DO see it in the Segment debugger will be as the event was originally constructed, and NOT what firebase would put into GA.

**Comment by RohovDmytro** [comment]
@bsneed , I think I got this. It's the other way around of syncing. I thought firebase 'standart' events would appear in segment.

Now I know that I'm not crazy. Cause I was NOT manage to make it work. :)

I do think we need to update the docs to be clear about that.

Anyway, happy hacking, guys. Thanks for your time.

**Comment by bsneed** [comment]
@RohovDmytro you're very welcome!  Can you point us to the doc page you were reading so that we can update it to be more clear?

Thanks for your inquiry!

**Comment by RohovDmytro** [comment]
This one is for sure:
https://segment.com/docs/connections/destinations/catalog/firebase/

Possibly here also:
https://segment.com/integrations/firebase/
