### ISSUE TITLE
Failed to load Analytics native module in js test

### ISSUE THREAD

**Issue by iadcg** [segmentio/analytics-react-native#32]
Its throwing this error in my test

![screen shot 2018-12-26 at 11 28 10 am](https://user-images.githubusercontent.com/45412363/50430873-96bb8600-0901-11e9-97be-0e689c5ec62e.png)

Basically, it will happen in when importing segment from '@segment/analytics-react-native'.
Is there a proper way to test this?

**Comment by patrick-samy** [comment]
I have the same problem with a manual integration of `Analytics.framework` installed from the NPM repository:
`https://github.com/segmentio/analytics-ios`

**Comment by TeresaNesteby** [comment]
Thanks for reaching out! For support questions, please reach out to our team directly at https://segment.com/contact/.

**Comment by Eyesonly88** [comment]
Try to mock out the `analytics-react-native` dependency

**Comment by stevula** [comment]
For anyone else that had this issue, the error comes from [here](https://github.com/segmentio/analytics-react-native/blob/cdc62a9f1fe178cc4bf1b9ac4adde58873c3e124/packages/core/src/bridge.ts#L46). From there, I was able to determined that `NativeModules.RNAnalytics` was the source of the error.

I resolved this by stubbing out `NativeModules.RNAnalytics` in the test:

```
import { NativeModules } from 'react-native';
NativeModules.RNAnalytics = {};
```

I also use the the Mixpanel integration so I had to add this bit:

```
// fixes error "Failed to load Mixpanel integration native module"
NativeModules.RNAnalyticsIntegration_Mixpanel = {};
```

**Comment by jjbeach** [comment]
I got it to work using @stevula and @Eyesonly88 solutions in the following way:

In my jest setupFile:

```javascript
import { NativeModules } from 'react-native';

NativeModules.RNAnalytics = {};

const mockAnalytics = jest.genMockFromModule('@segment/analytics-react-native');

jest.mock('@segment/analytics-react-native', () => mockAnalytics);
```

**Comment by alexpanov** [comment]
Has anyone experienced a `Failed to load Analytics native module.` issue after upgrading to React Native 0.61?

**Comment by acollazomayer** [comment]
@alexpanov I have the same problem. Did you solve it?

**Comment by acollazomayer** [comment]
@alexpanov Did you solve this problem. I am not able to react native 
upgrade due to this.

**Comment by ospfranco** [comment]
I used @jjbeach solution and it was working on RN 0.59, after upgrading to 0.61 it no longer works. any word from segment here would be nice.

**Comment by ospfranco** [comment]
I was using @jjbeach solution, after upgrading to rn 0.61 it stopped working, however, if you remove some of the code it works again:
```javascript
// MOCK SEGMENT
// NativeModules.RNAnalytics = {};

// const mockAnalytics = jest.genMockFromModule('@segment/analytics-react-native');

jest.mock('@segment/analytics-react-native', () => ({
  setup: () => null,
}));
```

**Comment by acollazomayer** [comment]
@ospfranco I remove the analytics error with this. But mocking setup to be null is not a good Idea

**Comment by ospfranco** [comment]
I'm sorry why would mocking it be a bad idea, unless you are running e2e tests or complete integration tests, you don't want to test the funcionality of 3rd party packages, right?

**Comment by acollazomayer** [comment]
@ospfranco Mocking it to null, I am having problems since setup is a promise my tests now are crashing since it tells me that setup does not have a catch function

**Comment by ospfranco** [comment]
@acollazomayer eh? it is just a matter of returning a promise:
jest.mock('@segment/analytics-react-native', () => ({
  setup: () => Promise.resolve(true), // or w/e your test needs
  identify: () => null,
  reset: () => null,
}));

**Comment by lucianomlima** [comment]
Someone have a example repro for this?! I try @ospfranco and @jjbeach approaches but still get the native module error with RN 0.61.5

**Comment by StoyanD** [comment]
create a file with path from root: `__mocks__/@segment/analytics-react-native.js` 
```
export default {
  setup: () => null,
  identify: () => null,
  reset: () => null,
}

```

Basically you need to tell jest what to mock, works with `react native 0.61.5`

**Comment by skanwarjeet** [comment]
@StoyanD It's giving me error 
`TypeError: Super expression must either be null or a function`
