### ISSUE TITLE
Property 'adSupportBlock' not found on object of type 'SEGAnalyticsConfiguration *'

### ISSUE THREAD

**Issue by blurrypixeldust** [segmentio/analytics-react-native#320]
Getting the `Property 'adSupportBlock' not found on object of type 'SEGAnalyticsConfiguration *'` error located in the RNAnalytics.m file when trying to build app from xcode. Attempting to build from react native cli also fails

`"react-native": "0.63.3"`
`"@segment/analytics-react-native": "^1.4.4"`

**Comment by alanjcharles** [comment]
@blurrypixeldust what version of `analytics-ios` is in your `podfile.lock`? Are you using XCode 125.?

**Comment by blurrypixeldust** [comment]
Yes xcode 12.5

I dont have any `analytics-ios` in the podfile only: 

`- Analytics (3.9.0)`

` - RNAnalytics (1.4.4):
    - Analytics
    - React-Core`

**Comment by alanjcharles** [comment]
No worries. Can you upgrade to `analytics-ios 4.1.4` and let me know if the issue persists?
