### ISSUE TITLE
Release version issues

### ISSUE THREAD

**Issue by oferRounds** [segmentio/analytics-react-native#33]
See picture please. Any ideas?

<img width="764" alt="screen shot 2019-01-13 at 18 29 47" src="https://user-images.githubusercontent.com/1477963/51087861-477aaf80-1761-11e9-9503-aa3e4b30c3ae.png">

**Comment by oferRounds** [comment]
I am using the latest Xcode version...

**Comment by TeresaNesteby** [comment]
Hi @oferRounds! Thanks for reaching out! For support questions, please reach out to our team directly at https://segment.com/contact/.

**Comment by MaxInMoon** [comment]
@oferRounds any update on this problem since January? thank you
