### ISSUE TITLE
Getting 'Appboy-iOS-SDK/ABKAppboyEndpointDelegate.h' file not found when trying to build ios project

### ISSUE THREAD

**Issue by kbihani** [segmentio/analytics-react-native#330]
Hello,

I am trying to use segment/analytics-react-native with @segment/analytics-react-native-appboy.

I was able to successfully install the libraries, link them, and pod install as well (without errors)

But when building the xcode project, I am getting this error:

**'Appboy-iOS-SDK/ABKAppboyEndpointDelegate.h' file not found when trying to build ios project**
**In file included from /ios/Pods/Segment-Appboy/Pod/Classes/SEGAppboyIntegrationEndpointDelegate.m:1:**

I am using:
"react-native": "0.59.10",
"@segment/analytics-react-native": "1.2.1",
"@segment/analytics-react-native-appboy": "1.2.1",
"react-native-appboy-sdk": "1.28.0"

I have only tested this on iOS.

**Comment by alanjcharles** [comment]
Hello- 

[We support ](https://segment.com/docs/connections/sources/catalog/libraries/mobile/react-native/#getting-started)`react-native 0.62`  and greater. Please upgrade that as well as  `analytics-react-native` and `analytics-react-native-appboy` to the latest versions .

**Comment by kbihani** [comment]
Hi, 

We are using the segment version 1.2.1 which I feel should be able to support react-native 0.59. Please correct me if wrong.

Our project is huge and the react-native upgrade is not as simple (it might take some time for us to upgrade)

Cn we please look at this issue if it's something that can be fixed?

**Comment by alanjcharles** [comment]
We can't really say how those versions will work with any of the new IOS (or XCode) versions which is why we no support it. Even if we could fix it, it would require you to update to the latest version of `analytics-react-native` and `analytics-react-native-appboy` when we release the fix, which would also require you to update `react-native` to at least 0.62, I'm afraid.
