### ISSUE TITLE
How to reset traits only?

### ISSUE THREAD

**Issue by Tale-Dev** [segmentio/analytics-react-native#331]
Hello team,

I would like to change user's properties (such email, name, phone number, address, ....) I used method "identify" with traits, then I track an event, all traits will be sent to event as event's properties (email, name, phone number, ...), so I would like to send events without traits and I tried to find a method to reset traits but no hope (I found method "reset" but it will reset all traits and userId, it looks like logout method)

Could you please point me some ways I can do it?

Thanks in advance!
Tai

**Comment by alanjcharles** [comment]
Hi @Tale-Dev would you be able to reach out to friends@segment.com with this request? We would like to limit the Github issues section to bug reports, if possible. You should be able to just add an empty traits object to your payloads to achieve this, like so `analytics.track('My Event', {<properties>}, context: {traits: {}});` , but support engineering will be able offer any additional advice based on your specific use-case and explain potential unintended consequences. Thanks!
