### ISSUE TITLE
Set Data in context of LifeCycle Events

### ISSUE THREAD

**Issue by aliwaqar981** [segmentio/analytics-react-native#333]
Hi! Thankyou for this great package. I'm trying to find out that how can I set some data in the context of Lifecycle Events (Application Opened, Application Installed e.t.c) of segment api.

Any help would be much appreciated!

**Comment by alanjcharles** [comment]
Hi @aliwaqar981! Manipulating the data of life lifecycle events is currently not something this library supports I'm afraid. It is on our roadmap for the near future, though. I would recommend reaching out to friends@segment.com for further technical support and for any updates in regard to new functionality. Best of luck!

**Comment by aliwaqar981** [comment]
> Hi @aliwaqar981! Manipulating the data of life lifecycle events is currently not something this library supports I'm afraid. It is on our roadmap for the near future, though. I would recommend reaching out to [friends@segment.com](mailto:friends@segment.com) for further technical support and for any updates in regard to new functionality. Best of luck!

https://segment.com/docs/connections/destinations/catalog/customer-io/#device-token-set-up
Hi @alanjcharles I can see that in the documentation there are methods to set device token for android and ios:

1. putDeviceToken
2. registeredForRemoteNotifications

But I'm not how to call them. I'm not getting these methods from the api

**Comment by alanjcharles** [comment]
@aliwaqar981  these methods are not available from the React Native API. This library is essentially a wrapper for the `analytics-ios` and `analytics-android` libraries. You will have to access the native functionality for each to enable native functionality. Here is the config option for Android: https://github.com/segmentio/analytics-react-native/issues/333 

I would recommend reaching out to the support engineering team at friends@segment.com for more assistance. They will definitely be able to get you squared away. We are trying to limit this Issues section to bugs and breaking changes. Thanks!
