### ISSUE TITLE
@segment/analytics-react-native-appsflyer changes for IOS 14.*

### ISSUE THREAD

**Issue by beqramo** [segmentio/analytics-react-native#338]
Hi, I'm trying to add support for IOS 14 and when I'm trying to run the app it throws an error. I think this is a problem because I tried to submit in an AppStore without this code and they rejected it with the error:
![image](https://user-images.githubusercontent.com/40486471/125038680-bf15c500-e0a6-11eb-950a-5d24382de4f5.png)

the instructions that I'm trying to add:
![image](https://user-images.githubusercontent.com/40486471/125036644-4877c800-e0a4-11eb-9005-ca8a027ecb23.png)

and actual code from  `AppDelegate.m`:

``` c
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{

  if #available(iOS 14, *) {
    // Set a timeout for the SDK to wait for the IDFA collection before handling app launch
      AppsFlyerLib.shared().waitForAdvertisingIdentifier(withTimeoutInterval: 60)
      // Show the user the Apple IDFA consent dialog (AppTrackingTransparency)
      // Can be called in any place
      ATTrackingManager.requestTrackingAuthorization { (status) in
      }
  }
}

```

The error:
![image](https://user-images.githubusercontent.com/40486471/125036960-a7d5d800-e0a4-11eb-9f3c-ee53fdeaf76c.png)

`package.json`:

```json
    "@segment/analytics-react-native": "^1.4.9",
    "@segment/analytics-react-native-appsflyer": "^1.4.9",
    "@segment/analytics-react-native-mixpanel": "^1.4.9",
    "react-native": "0.64.1",
```

Thanks.

**Comment by alanjcharles** [comment]
Hi @beqramo can you please reach out to friends@segment.com if you are still running into issues submitting to the app store? We are attempting to limit the issues here to bugs and other unexpected behavior with the library itself. Thanks, good luck!
