### ISSUE TITLE
Remove Tracing Screen Events only needed track event

### ISSUE THREAD

**Issue by leena-sharma** [segmentio/analytics-react-native#339]
Hi
Remove Tracing Screen Events only needed track event.
In dashboard debugger getting events like RCTModalHost, UIInputOverlay etc. I want remove these.
How can i achieve this?

**Comment by leena-sharma** [comment]
Hi
Remove Tracing Screen Events only needed track event.
In dashboard debugger getting events like  RCTModalHost, UIInputOverlay etc. I want remove these. 
How can i achieve this?

**Comment by alanjcharles** [comment]
Hi @leena-sharma please reach out to friends@segment.com for support with this. They will be able to take a closer look at your implementation and offer advice from there. Thanks!
