### ISSUE TITLE
Didn't find class "com.mixpanel.android.mpmetrics.MixpanelAPI"

### ISSUE THREAD

**Issue by Antoine-Mace** [segmentio/analytics-react-native#34]
Hi, 

We have integrated Segment with one of our existing RN app.

On Android the app crash, from our log we can see that `Didn't find class "com.mixpanel.android.mpmetrics.MixpanelAPI"` error is thrown.

Any idea what might cause this issue?

Cheers,

**Comment by Antoine-Mace** [comment]
Seems to be something linked to `@segment/analytics-react-native-mixpanel`

`
import pkg from '../package.json'
import analytics from '@segment/analytics-react-native'
// import Mixpanel from '@segment/analytics-react-native-mixpanel'
import GoogleAnalytics from '@segment/analytics-react-native-google-analytics'

const key = pkg.segment.key

const initSegment = () => analytics.setup(key, {
    using: [GoogleAnalytics/*, Mixpanel */],
    recordScreenViews: false,
    trackAppLifecycleEvents: true,
    trackAttributionData: true
})

export default initSegment
`
When MixPanel commented out the app run fine. Does any other configuration is required?

**Comment by TeresaNesteby** [comment]
Hi @Antoine-Mace ! Thanks for reaching out! For support questions, please reach out to our team directly at https://segment.com/contact/.

**Comment by t3chnoboy** [comment]
We are getting the same error after upgrading to `0.0.1-beta.4`
