### ISSUE TITLE
No podspec found for `RNAnalyticsIntegration-Amplitude-Analytics` in `../node_modules/@segment/analytics-react-native-amplitude-analytics`

### ISSUE THREAD

**Issue by edem** [segmentio/analytics-react-native#340]
environment :

$ yarn -v
1.22.4
$ npm -v
6.14.13
$ node -v
v14.17.3
$ react-native -v
react-native-cli: 2.0.1
react-native: 0.64.2

$ yarn add @segment/analytics-react-native
$ yarn add @segment/analytics-react-native-amplitude
$ cd ios
$ pod install 

get error as below : ---------------------------------------------------------------------

Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "RNAnalyticsIntegration-Amplitude":
  In Podfile:
    RNAnalyticsIntegration-Amplitude (from `../node_modules/@segment/analytics-react-native-amplitude`)

Specs satisfying the `RNAnalyticsIntegration-Amplitude (from `../node_modules/@segment/analytics-react-native-amplitude`)` dependency were found, but they required a higher minimum deployment target.

-----------------------------------------------------------------------------------------------------
then I added these into  Podfile : 
pod 'RNAnalytics', :path => '../node_modules/@segment/analytics-react-native'
pod 'RNAnalyticsIntegration-Amplitude-Analytics', :path => '../node_modules/@segment/analytics-react-native-amplitude-analytics'

$ pod install 

get another error as below : 
------------------------------------------------------------------------------------
No podspec found for `RNAnalyticsIntegration-Amplitude-Analytics` in `../node_modules/@segment/analytics-react-native-amplitude-analytics`
-------------------------------------------------------------------------------------

Could you help me to resolve it?
This is the content of my Podfile : 

###########################################################
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
#use_frameworks!

target 'CSApp3' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
.................. (ignore) ...........................
  #Segment-Anplitude
  pod 'RNAnalytics', :path => '../node_modules/@segment/analytics-react-native'
  pod 'RNAnalyticsIntegration-Amplitude-Analytics', :path => '../node_modules/@segment/analytics-react-native-amplitude-analytics'
................. (ignore) ...................
end

**Comment by edem** [comment]
I edit Podfile : 

platform :ios, '10.0'      -->  platform :ios, '11.0'

install success

**Comment by alanjcharles** [comment]
Hi @edem I have just published a new release that should address this issue. Please update your Amplitude package and let me know if the problem persists. Thanks!
