### ISSUE TITLE
Segment Write Key missing notification

### ISSUE THREAD

**Issue by zeusstl** [segmentio/analytics-react-native#344]
Our Segment Write Key lives in a .env file in our codebase. Unfortunately, it was missing from a testing version while testing with an incorrect copy of the .env file.

We spent a full day trying to find the error which was presenting as a failure in Xcode related to:
__NSPlaceholderDictionary initWithObjects:forKeys:count

Unfortunately, we didn't save the full copy of the error, but hopefully you can add a validation alert or console log error message so that future developers can easily know that they are simply missing their Segment Write Key.

**Comment by alanjcharles** [comment]
Hi @zeusstl thanks for letting us know! Sorry to hear you ran into so much trouble. We are actively working to improve our logging functionality and will be sure to take this into account.
