### ISSUE TITLE
Reloading app causes exception "Segment Analytics Client was allocated multiple times, please check your environment."

### ISSUE THREAD

**Issue by ex3ndr** [segmentio/analytics-react-native#345]
A lot of apps in RN are able to restart to apply update or for various other reasons.

Analytics throws exception in this case.

**Comment by rafaj10** [comment]
Also, I'm getting the same issue but I'm trying to reload the setup keys in order to QA team test in different envs...

**Comment by alanjcharles** [comment]
Hi @ex3ndr we're going to need more information to take a closer look at this. I am able to spin up a bare-bones react native app, add analytics-react-native and reload as quickly and often as I like with no issues.  If you would like additional support getting to the bottom of this please reach out to us at friends@segment.com. Closing for now but am willing to reopen if you can send a more detailed description of your implementation/issue.

**Comment by pavermakov** [comment]
@zeusstl 

```
import analytics from "@segment/analytics-react-native";

...

if (analytics.ready) {
     ...
}
```

**Comment by zeusstl** [comment]
Unfortunately, analytics.ready isn't helping in this situation. It says that it is ready, so continues, but then it fails as above.
