### ISSUE TITLE
Amplitud Actions

### ISSUE THREAD

**Issue by horaciomoreno100** [segmentio/analytics-react-native#348]
Hi, there!
I would like to use Amplitud Actions, but i dont know if this version of analytics-react-native works/implements with Analytics.js 2.0 that as i understand, is necesary to work with Amplitud Actions

[actions-amplitude](https://segment.com/docs/connections/destinations/catalog/actions-amplitude/)  

> Connection Modes for Amplitude (Actions) destination
> The Amplitude (actions) destination does not offer a device-mode connection mode. If you’re using one of Segment’s new libraries (Analytics.js 2.0, Swift or Kotlin) with the Actions-framework version of the destination, you do not need the device-mode connection.

Thanks in advace!

**Comment by alanjcharles** [comment]
Hi @horaciomoreno100 Amplitude Actions is not currently available for this library, I'm afraid. We are actively working on it and should have something for you very soon, thought! Thanks for your patience, we'll be sure to let you know.
