### ISSUE TITLE
Android lifecycle events not captured

### ISSUE THREAD

**Issue by anandwahed** [segmentio/analytics-react-native#36]
We are using `@segment/analytics-react-native - ^0.0.1-beta.3` in our application. But the Lifecycle events are not being tracked automatically in the case of Android, though it works fine in iOS. We tried to simulate the same using a new RN project and facing the same issue with Android.

```
"dependencies": {
    "@segment/analytics-ios": "github:segmentio/analytics-ios#3.6.10",
    "@segment/analytics-react-native": "^0.0.1-beta.3",
    "react": "16.6.3",
    "react-native": "0.58.3",
    "react-native-gesture-handler": "^1.0.15"
  },
  "devDependencies": {
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "24.0.0",
    "jest": "24.0.0",
    "metro-react-native-babel-preset": "0.51.1",
    "react-test-renderer": "16.6.3"
  }
```

Test Repo:

https://github.com/anandwahed/test-rn-segmentsdk

**Comment by anandwahed** [comment]
@fathyb can you have a look into it or let us know if we are doing something wrong in the config?

**Comment by TeresaNesteby** [comment]
Thanks for reaching out! For support questions, please reach out to our team directly at https://segment.com/contact/.

**Comment by ericketts** [comment]
in regards to this issue, it looks like the TS source does queueing for events that are tracked before the segment setup has occurred -- however because the lifecycle events are dispatched directly from the native SDKs (skipping the TS queueing mechanism), and the native SDKs look to have been built under the assumption that setup would happen synchronously (which would make a queueing mechanism redundant), this issue might be a bit of a difficult one to fix...

**Comment by socheat1994** [comment]
currently, I am facing with this problem too. does anyone has solution with this yet ? 🙁

**Comment by ericketts** [comment]
you can see that the native lib [won't dispatch events before enabled is true](https://github.com/segmentio/analytics-ios/blob/3be84b2a2af326a9ff502f53efeb5725e2aae142/Analytics/Classes/SEGAnalytics.m#L426-L428) (it bails out from the call before this), and enabled only becomes true after the `Analytics.setup` call crosses the JS<->native bridge, which as I mentioned in my prior comment is asynchronous; I'm in direct contact with a segment rep for this issue and will keep you folks apprised as to any developments that come out of this dialog.

**Comment by masterial** [comment]
@ericketts any traction on this?

**Comment by ericketts** [comment]
@masterial I think I may have been barking up the wrong tree with my previous comment since RN iOS lifecycle events appear to work with this lib, however android is still broken from what I can see (I believe I'm on the latest lib, though I'm not 100% sure about that)

**Comment by masterial** [comment]
@ericketts I think I see the same issue.
