### ISSUE TITLE
Is recordScreenViews flag working?

### ISSUE THREAD

**Issue by gsunsnackv** [segmentio/analytics-react-native#37]
I don't see it work for me on Android. We are using react-native-navigation. Is it fundamentally different from Android screens so that Segment cannot record screen automatically?

**Comment by gsunsnackv** [comment]
It seems to give only one screen with the name of our app
![image](https://user-images.githubusercontent.com/44099616/52732981-6cd42680-2f76-11e9-9c60-9f72ad12dbcf.png)

**Comment by TeresaNesteby** [comment]
Hi @gsunsnackv! 

Thanks for reaching out! :) 

For support questions, please reach out to our team directly at https://segment.com/contact/.

**Comment by powersjcb** [comment]
Hey, @TeresaNesteby was there any resolution on this? (I just noticed we have the same issue.)

**Comment by gsunsnackv** [comment]
@powersjcb They have no solution. Apparently it is useless https://segment.zendesk.com/hc/en-us/requests/169119

**Comment by nachtien** [comment]
You need to have a label assigned in your Android Manifest for this to work, otherwise it will show up as the application name.

**Comment by gsunsnackv** [comment]
Thank you @nachtien . Do you have any examples on how to set this label? Is that a label per screen? Right now we manually in JS track the screen event. We were able to get route name and previous route name. That's all react-navigation gave us.

**Comment by ryanbabbly** [comment]
Can someone clarify why this issue was closed with no resolution? This is an issue for us as well.

**Comment by bsneed** [comment]
@ryanbabbly I'm not sure what the previous conversation in this thread refers to, but the gist of it is this:  React Native doesn't use the native navigation, which is why it's not working.  Way back when, this was not the case and it was actually useful.  We're going to remove this option in the near future to prevent confusion.

To get automatic screen tracking, you can use react-navigation's hooks to issue a screen call as changes occur.  We did look at doing this automatically, but given all the navigation options (react-nav 3.x, 4.x, 5.x, and a handful of other libs) we decided it wasn't something we could support in the long term.

**Comment by ryanbabbly** [comment]
@bsneed very sorry to hear this as it would have helped us out. We currently use the onStateChange on the navigator object to track screens, but we've noticed it doesn't fire the first time a navigator is loaded. So we've been missing screens and have a hacky way of fixing it at the moment. If we could have let segment handle this it would have solved our problem.

**Comment by pepf** [comment]
@bsneed Thanks for clarifying this!

Tracking and logging inside react-nav (5.x) works fine for us, but it seems like some destinations are not natively picking this up, while support for screen tracking is available on the platform, for example on Firebase :). I would be ok with calling this trough NativeModules if this method could be exposed one way or the other (segment already includes firebase, no need for pulling in more firebase wrappers for example), but ideally it would be amazing if `screen()` calls just magically work.

As a solution I'm considering to migrate to https://github.com/software-mansion/react-native-screens to actually get back these "native" screens, but if you mention this config will be deprecated I'm not going to put in that effort ;)

**Comment by bsneed** [comment]
@pepf No problem, thanks for the additional info!

Good to know it's working for you in 5.x.  I'm not sure re the destinations.  Could vary depending on cloud vs. device, and some destinations might not work with or accept `screen`.  I'm not sure what you mean when you say "I would be ok with calling this through native modules if this method could be exposed".  Could you elaborate?

You made a pretty good case for leaving that screen tracking option in, so I'll leave it as-is.
