### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by cmaycumber** [segmentio/analytics-react-native#372]
## Summary

We currently use react native as a cross-platform solution across the web, iOS, and Android. It would be great if the `analytics-react-native` library somehow supported web out of the box. 

## Proposed Solution

Add web support for a single and easy-to-use cross-platform analytics solution.

**Comment by alanjcharles** [comment]
@cmaycumber thanks for the recommendation! We do not have any plans to support web at the moment as the core library still relies on a few native files and analytics.js 2.0 already does a great job. However, feel free to purpose a solution here or in a PR as we're more than happy to consider it.
