### ISSUE TITLE
How long will the Pilot designation last?

### ISSUE THREAD

**Issue by jgable** [segmentio/analytics-react-native#373]
Hi 👋 We are considering updating our Segment dependency to this new version but would like more information on how long the pilot designation will last. It doesn't have to be an exact date, can be a ballpark figure or just something based on how long other projects had the pilot designation before removing.

Thanks for your time, if there is a better place to ask this question feel free to redirect.

**Comment by alanjcharles** [comment]
Hi @jgable!  It is our top priority to provide solid libraries that don't require fundamental API changes once released to general availability. We don't have a strict timeline as we base it on adoption, issues filed, support, etc. Historically, some of our pilots for new libraries have lasted anywhere from 2-4 months before moving to beta with a similar time period between beta and GA. With that said, please feel free to send us all of your feedback while we move through the phases. While we're in pilot and beta, we have the cycles to take on issues or feature requests. Once we've moved to GA those things will have to be escalated via standard support channels.
