### ISSUE TITLE
Multiple identify calls result in unwanted traits

### ISSUE THREAD

**Issue by pavermakov** [segmentio/analytics-react-native#375]
I have an app with a simple email / password authentication. After the login, I call the `identify` method with some traits that may include an optional `region` property. Let's say I login under a user with a region set to "south-east". I can see that trait on the dashboard. Then I logout and login under another user that doesn't have a `region` property. What I observe on the dashboard now is that the region of the first user is merged into the traits of the second user. 

What can I do to prevent such behaviour? 

- `analytics-react-native` version: 1.4.9
- `react-native` version: 0.64.2
- Both platforms

**Comment by ghacosta** [comment]
@pavermakov did you solve this bug? I'm having same behavior on `"@segment/analytics-react-native": "^1.5.0",`

**Comment by kuldeepGomilestone** [comment]
@ghacosta i am also facing the same issue , did you find anything to resolve this ?
