### ISSUE TITLE
context.device.type is not collected and it's required for Kochava according to docs

### ISSUE THREAD

**Issue by caroaguilar** [segmentio/analytics-react-native#38]
In Kochava destination docs (https://segment.com/docs/destinations/kochava/#getting-started) it says `context.device.type` (has value of ‘ios’ or ‘android’), `context.device.advertising_id` (IDFA on iOS and adID on Android) and `context.device.id` are required in all calls to Kochava. Then in https://segment.com/docs/spec/common/#context-fields-automatically-collected it says that `device.type` is populated automatically by iOS library. However looking at the request data sent to Segment, context.device object only has `manufacturer`, `model`, `id`, `advertisingId`,  `adTrackingEnabled` fields, and looking at the code of the iOS SDK https://github.com/segmentio/analytics-ios/blob/master/Analytics/Classes/Internal/SEGSegmentIntegration.m#L162  the field type doesn’t exist. Is this field still required for Kochava calls or are the docs outdated?

**Comment by TeresaNesteby** [comment]
Hi @caroaguilar, 

Thanks for reaching out - and great question. 

Our team would be happy to take a closer look here. Please, reach out to us directly at https://segment.com/contact/.

**Comment by fortydegrees** [comment]
I have this issue when trying to assign my users deviceIDs with customerio

**Comment by raiss** [comment]
@TeresaNesteby could you please get your team to provide some help here so the users can see the answer here. It is not productive for your team and users to ask the same questions over and over. Thanks
