### ISSUE TITLE
Unable to resolve path to module '@segment/analytics-react-native-plugin-appsflyer'

### ISSUE THREAD

**Issue by gshaw1997** [segmentio/analytics-react-native#380]
Hi,

I'm trying to use the `AppsFlyerPlugin`

I've tried to install it directly using `yarn add @segment/analytics-react-native-plugin-appsflyer`, but it doesn't seem to be a published package.

It's also does not appear to be added in the `@segment/analytics-react-native` package.

- `analytics-react-native` version: ^2.0.0-pilot
- Integrations versions (if used): None, but trying to use AppsFlyer
- React Native version: 0.64.1
- iOS or Android or both? - Both

**Steps to reproduce**
- `yarn add @segment/analytics-react-native`
- `import { AppsflyerPlugin } from '@segment/analytics-react-native-plugin-appsflyer';`

**Expected behavior**
`AppsflyerPlugin` is able to be imported

**Actual behavior**

**Comment by alanjcharles** [comment]
Hi @gshaw1997 sorry about that. Thanks for bringing this to our attention! They were unintentionally marked as private. Please let me know if you still have issues: https://www.npmjs.com/package/@segment/analytics-react-native-plugin-appsflyer
