### ISSUE TITLE
useNativeConfiguration for v2

### ISSUE THREAD

**Issue by adkenyon** [segmentio/analytics-react-native#381]
## Summary

Is there a `useNativeConfiguration` in the v2 implementation? Perhaps I overlooked it or it isn't documented yet. 

In my specific use case, we have a native integration (Branch) that needs segment's anonymous ID ASAP, before RN (and the JS segment client would be initialized).

**Comment by alanjcharles** [comment]
@adkenyon the new library doesn't rely on underlying native code like the old one did for both the library itself and device mode destinations. With that said, I'm not sure this issue will be a problem now but we haven't yet built out a Branch Plugin to say for sure. I will prioritize it and we can take it from there. Sound good?

**Comment by andrew-hm** [comment]
With `getAnonymousId()` missing, there is no other way to retrieve the uuid generated by the userinfo in the store. What's the syntax to pass in and setup the store with an anonymous id then in  2 impplementation?

**Comment by adkenyon** [comment]
@alanjcharles now I have more questions 😄 

Regarding the branch integration, wait and see is fine, we're in no rush to upgrade to v2. I'd be curious how the JS implementation will work with Branch though. The issue we ran into when we were using the JS initialization of V1 was that the `segment_anonymous_id` was not attached to the install/reinstall events sent to Branch. Subsequent events did have that `segment_anonymous_id`, the issue was a race condition. Branch would capture those events immediately before the JS engine was able to initialize segment and attach the `segment_anonymous_id` to branch events. Moving to a native initialization we were able to initialize segment before Branch. Therefore attaching the `segment_anonymous_id` to the branch install/reinstall events.

Followup question, If the native SDKs are no longer used how is the event cache persisted? With a default flush interval of 30 seconds, there's a high chance of events being completely lost when the user kills the app. With the persistent cache of the SDKs the events are eventually sent when the app boots back up. (At least I _thought_ the SDKs did this). Granted we can manually flush, decrease the flushAt, or decrease the flushInterval parameters (granted with a hit on battery life).

**Comment by kadikraman** [comment]
Hi @adkenyon and @andrew-hm  👋  - the events are stored in a redux store and persisted in Async Storage using redux persist. They get flushed when you get to 20 events or 30 seconds, whatever happens first (both options are [configurable](https://github.com/segmentio/analytics-react-native#client-options)) _or_ when you resume the app. E.g. if you trigger an event an immediately close the app, the event will be sent the next time you open it again.

As for the anonymous ID: you do have to initialise the client to get it. On the very first launch, it would first get set [with the initial redux state](https://github.com/segmentio/analytics-react-native/blob/a2a24af094b4198486d6a203bd96a9f64e7f616b/packages/core/src/store/userInfo.ts#L12) so it would be impossible to have the anonymous ID _before_ the client is initialised on first launch.

Once the Segment client has been initialised though, you could get access to it by calling [`getUserInfo`](https://github.com/segmentio/analytics-react-native/blob/a2a24af094b4198486d6a203bd96a9f64e7f616b/packages/core/src/analytics.ts#L153) on the client:

```js
const { anonymousId } = client.getUserInfo();
```

**Comment by alanjcharles** [comment]
@adkenyon is there any other prop you need before initializing the Segment client? Or is it just the anonymousId? do you have any documentation from Branch you could share to make sure we don't miss anything as we begin to dive into this? Thanks so much!
