### ISSUE TITLE
Ability to access the client in useAnalytics hook?

### ISSUE THREAD

**Issue by studiobrain** [segmentio/analytics-react-native#389]
## Summary

I am using the client to access some built in params via the getState call:
```
const {
  main: {
    context: { app },
  },
  userInfo,
} = SegmentClient.store.getState()
```
We will need access to these params throughout the app, and since the provider is passing client:
```
<AnalyticsProvider client={segmentClient}>
```
Is it possible to access the client on the context object via the provided hook?

## Proposed Solution

```
import { useAnalytics } from '@segment/analytics-react-native'

...
const { track, client } = useAnalytics()
```
Potentially there is a better or already existing solution?

**Comment by alanjcharles** [comment]
Hi @studiobrain apologies, I'm not sure I understand the question. Your purposed solution is how we recommend using hooks to access the client from anywhere in your app: 

```  const { screen, track, identify, group, alias, reset, flush } = useAnalytics();```

[Here's where you can find it in the example app](https://github.com/segmentio/analytics-react-native/blob/master/example/src/Home.tsx#L17)

I'm going to close this for now but please feel free to re-open if there's something I have misunderstood.
