### ISSUE TITLE
Type error on registering FacebookAppEventsPlugin

### ISSUE THREAD

**Issue by imAliAzhar** [segmentio/analytics-react-native#393]
- `analytics-react-native` version: 2.0.0-pilot.1
- Integrations versions (if used): @segment/analytics-react-native-plugin-facebook-app-events (0.1.0-pilot.1)
- React Native version: 0.64.3
- iOS or Android: Both

**Steps to reproduce**
1. Install latest versions of analytics-react-native and analytics-react-native-plugin-facebook-app-events.
2. Register FacebookAppEventsPlugin to segment client like so:
```ts
  segmentClient.add({ plugin: new FacebookAppEventsPlugin() });
```

**Expected behavior**
No errors

**Actual behavior**
Type error: 
```
Type 'FacebookAppEventsPlugin' is not assignable to type 'Plugin'.
  Types of property 'configure' are incompatible.
    Type '(analytics: SegmentClient) => Promise<void>' is not assignable to type '(analytics: SegmentClient) => void'.
      Types of parameters 'analytics' and 'analytics' are incompatible.
```

I think FacebookAppEventsPlugin (added in #377) depends on unreleased changes of core analytics-react-native and the issue can be fixed with a new release. A new release would also fix react-native-community/async-storage issue which was fixed in #378 but still exist on tag 2.0.0-pilot.1.

**Comment by LFMAKER** [comment]
same here
@kadikraman

**Comment by rafael-antunes-natoora** [comment]
It's actually not just related to the Facebook. It's not working with expo for the same reason...

**Comment by alanjcharles** [comment]
Hi @imAliAzhar  @LFMAKER thanks for flagging. A Fix for this will be included in our next release. In the meantime, please feel free to use our FBAppEvents Plugin to make your own. The core library extends all of the functionality you need. Let me know if you have any other questions in the meantime. 

@rafael-antunes-natoora how are you building in Expo? With the new EAS deploy framework? Any additional info you can provide will be helpful.

**Comment by imAliAzhar** [comment]
@alanjcharles Do you have any timeline for your next release?

**Comment by MorenoMdz** [comment]
Hey there, did the update get released already? I am still seeing this same error. In case we have to use a plugin for this one, is there an example of how to do it?

Thanks!

**Comment by walterholohan** [comment]
I am getting the same type error when trying to register this plugin.
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/5293650/166434731-7d8b9f70-af6b-4830-b336-d3594bcdb0f1.png">

**Comment by weeksie** [comment]
Getting the same type error here.
