### ISSUE TITLE
Error with  analytics-react-native-plugin-idfa - TypeError: null is not

### ISSUE THREAD

**Issue by johnsoncwb** [segmentio/analytics-react-native#394]
- `analytics-react-native` version: "^2.0.0-pilot.1"
- Integrations versions (if used): "^0.1.0-pilot" (@segment/analytics-react-native-plugin-idfa)
- React Native version: 0.66.4
- iOS or Android or both?  - iOS

**Steps to reproduce**
npx react-native init segmentTest --template react-native-template-typescript
yarn add @segment/analytics-react-native
yarn upgrade @segment/analytics-react-native@2.0 > set 2.0.0-pilot.1
yarn add @react-native-async-storage/async-storage
yarn add @segment/analytics-react-native-plugin-idfa
set NSUserTrackingUsageDescription in Xcode with any message 

npx pod-install

yarn run ios

**Expected behavior**
No warnings and I expect to get a message asking for enabling track on iOS device.

**Actual behavior**

instead, I have  this error: 

Error: Requiring module "node_modules/@segment/analytics-react-native-plugin-idfa/src/index.ts", which threw an exception: TypeError: null is not an object (evaluating '_$$_REQUIRE(_dependencyMap[7], "./AnalyticsReactNativePluginIdfa").AnalyticsReactNativePluginIdfa.getTrackingAuthorizationStatus') 

![Screen Shot 2021-12-24 at 6 26 36 PM](https://user-images.githubusercontent.com/80973949/147372770-24451330-38b0-4452-a60c-b30954bf8051.png)

**Comment by LFMAKER** [comment]
Same here

**Comment by Kerumen** [comment]
I have the same issue.
I've tracked it down: I think it's because the published package is missing the podspec file.
To reproduce, `yarn add @segment/analytics-react-native-plugin-idfa` and search for the podspec file in the `node_modules` folder.

**Comment by alanjcharles** [comment]
Hi @johnsoncwb @LFMAKER  @Kerumen  Happy New Year. Thanks for flagging, we have a few things to wrap up before we push the next release but this fix will definitely be included. In the meantime, please feel free to use our idfa plugin as an example to build your own. The core library extends all of the functionality you need. Let me know if you have any other questions in the meantime.

**Comment by LFMAKER** [comment]
Hi @alanjcharles, Happy new year!
Abou this issue:
This is because the native method is not calling ATT authorization. As of IOS 15 you must call ATT in the applicationDidBecomeActive method.
https://developer.apple.com/forums/thread/690607

So for this lib to keep working, it must remove the ATT call in its method and create a guide stating that it must be added in the method above in AppDelegate.m
Furthermore, it needs to improve the fallback to versions below 14, as the method they use to retrieve the status is only available above it.

Unfortunately I don't have time to contribute a PR, but if possible I will try.

**Comment by alanjcharles** [comment]
podfile issue addressed here #418

@LFMAKER we have not been able to reproduce what you've described. Once we add the podspec correctly everything works as expected. We plan to push a release at the beginning of next week so let me know if the issue persists once we publish. Thanks for the input everyone.
