### ISSUE TITLE
Wrong condition in Adjust plugin

### ISSUE THREAD

**Issue by Kerumen** [segmentio/analytics-react-native#395]
It seems that there is a typo in the Adjust plugin on L23:

https://github.com/segmentio/analytics-react-native/blob/106c50b69ddb63c85cfa47ad89eac058adbd32a1/packages/plugins/plugin-adjust/src/AdjustPlugin.tsx#L22-L24

I think the condition should be `type !== UpdateType.initial` because when the plugin is added, the `update` is called with:

https://github.com/segmentio/analytics-react-native/blob/5a900a2f6a9da654a6dd5fcd46336f2c6e25a51e/packages/core/src/timeline.ts#L30

As is, the plugin is never initialized and the events are never sent.

In the other plugins, the condition is never checked.

Do you want me to setup a PR to fix that?

**Comment by alanjcharles** [comment]
Hi @Kerumen  thanks for flagging this. Please feel free to set up a PR and we'll be sure to review it asap.

**Comment by Kerumen** [comment]
@alanjcharles Thanks for your reply. Should I reverse the condition or completely remove the `if` block?

**Comment by Kerumen** [comment]
@alanjcharles PR is here #396 🙂
