### ISSUE TITLE
`device.type` is wrong on iOS

### ISSUE THREAD

**Issue by Kerumen** [segmentio/analytics-react-native#398]
On iOS the device type should be `ios`. However, the current implementation is checking whether the device is a phone or a tablet:

https://github.com/segmentio/analytics-react-native/blob/106c50b69ddb63c85cfa47ad89eac058adbd32a1/packages/core/ios/AnalyticsReactNative.swift#L84

It breaks some integrations (Adjust in our case).

On Android, the `deviceType` is correctly set to `android`.

https://github.com/segmentio/analytics-react-native/blob/106c50b69ddb63c85cfa47ad89eac058adbd32a1/packages/core/android/src/main/java/com/segmentanalyticsreactnative/AnalyticsReactNativeModule.kt#L103

NB: On v1, the `deviceType` was correctly set to `ios` so I guess this is a regression on v2.

**Comment by Kerumen** [comment]
@alanjcharles Do you want me to set up a PR to fix this also?

**Comment by alanjcharles** [comment]
@Kerumen ah thought we had fixed this already, apologies. Yeah, if you don't mind thank you!
