### ISSUE TITLE
fatal error: 'Analytics/SEGAnalytics.h' file not found

### ISSUE THREAD

**Issue by whoislewys** [segmentio/analytics-react-native#40]
I did the following:
1. `yarn add @segment/analytics-react-native`
2. `yarn react-native link`
3. `cd ios`
4. `pod init`
5. `vim Podfile` and make changes so that my podfile looks like this:
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'my_app' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for my_app
  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'RNAnalytics', :path => '../node_modules/@segment/analytics-react-native'

  target 'my_app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'my_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```
6. `pod install`
7. `cd .. && react-native run-ios`
i am on react-native 0.58.6

I am greeted with
```
10:9: fatal error: 'Analytics/SEGAnalytics.h' file not found
#import <Analytics/SEGAnalytics.h>
```

**Comment by f2prateek** [comment]
Hi! It looks like steps were run in an incorrect order. This step needs to be done first  https://github.com/segmentio/analytics-react-native#setup-cocoapods-in-an-existing-project (it is a pre-requisite).

1. `cd ios`
2. `pod init`
3. edit podfile
4. `pod install`
5. `yarn add @segment/analytics-react-native`
6. `yarn react-native link`
7. `cd .. && react-native run-ios`

Specifically the `yarn react-native link` needs to happen after the `pod install` step.

Also make sure that to have the `# Add new pods below this line` as indicated here https://github.com/segmentio/analytics-react-native#setup-cocoapods-in-an-existing-project, because `yarn react-native link` uses that as a marker to insert references.

**Comment by whoislewys** [comment]
Ended up building my own basic module to hit a REST endpoint for my analytics because segment is overkill right now

attributing this issue to user error and closing

thanks for the response, if i come back to segment i will follow your advice

**Comment by AmitPandya007** [comment]
does it got resolved? please reply.

> I did the following:
> 
> 1. `yarn add @segment/analytics-react-native`
> 2. `yarn react-native link`
> 3. `cd ios`
> 4. `pod init`
> 5. `vim Podfile` and make changes so that my podfile looks like this:
> 
> ```
> # Uncomment the next line to define a global platform for your project
> # platform :ios, '9.0'
> 
> target 'my_app' do
>   # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
>   use_frameworks!
> 
>   # Pods for my_app
>   pod 'React', :path => '../node_modules/react-native'
>   pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
>   pod 'RNAnalytics', :path => '../node_modules/@segment/analytics-react-native'
> 
>   target 'my_app-tvOSTests' do
>     inherit! :search_paths
>     # Pods for testing
>   end
> 
>   target 'my_appTests' do
>     inherit! :search_paths
>     # Pods for testing
>   end
> 
> end
> ```
> 
> 1. `pod install`
> 2. `cd .. && react-native run-ios`
>    i am on react-native 0.58.6
> 
> I am greeted with
> 
> ```
> 10:9: fatal error: 'Analytics/SEGAnalytics.h' file not found
> #import <Analytics/SEGAnalytics.h>
> ```

**Comment by misterpoloy** [comment]
I fix this issue by adding this to my podfile:
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XXX' do
  # Comment the next line if you don't want to use dynamic frameworks
  # Pods for protoseg
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'RNAnalytics', :path => '../node_modules/@segment/analytics-react-native'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'React', :path => '../node_modules/react-native' , :subspecs => [
    'CxxBridge',
  ]
  
end

```
