### ISSUE TITLE
Typescript error with promise type

### ISSUE THREAD

**Issue by dgranahan** [segmentio/analytics-react-native#400]
Using typescript@4.1.2 or more recent I am seeing the following Typescript in my React Native app.
```
node_modules/@segment/analytics-react-native/src/wrapper.ts:49:49 - error TS2345: Argument of type '(value: unknown) => void' is not assignable to parameter of type '() => void'.

49      return new Promise(resolve => this.queue.push(resolve))
```

It looks like this line needs to be updated to fix the Typescript type mismatch: https://github.com/segmentio/analytics-react-native/blob/v1.5.0/packages/core/src/wrapper.ts#L49

Adding the `void` promise param type fixes the Typescript error:
```
return new Promise<void>(resolve => this.queue.push(resolve))
```

- `@segment/analytics-react-native@1.5.0`
- `react-native@0.66.1`
- `typescript@4.1.2`

**Comment by alanjcharles** [comment]
@dgranahan thanks for bringing this to our attention. We don't currently have any plans to push a release versions of this library `<= 1.5.0` for minor updates as we are currently putting all of our resources toward the new build `>= 2.0.0`. Closing this out in an attempt to keep our issues section up to date, let me know if you have any questions.

**Comment by dgranahan** [comment]
@alanjcharles do you have a timeline for the 2.0.0 release? Unfortunately this specific issue is blocking us.

**Comment by dgranahan** [comment]
@alanjcharles or do you have any suggested workaround for this while waiting for 2.0.0?

**Comment by dgranahan** [comment]
Here is the change that fixes this issue: https://github.com/segmentio/analytics-react-native/compare/v1.5.0...dgranahan:v1.5.0-typescript-fix?expand=1

**Comment by dgranahan** [comment]
Hello @alanjcharles is there a timeline for the 2.0.0 release?

**Comment by alanjcharles** [comment]
Hi @dgranahan as soon as possible. Apologies, we have had some members of the team out via unexpected circumstances lately which have delayed things a bit.
