### ISSUE TITLE
Non configurable `console.warning` when sending queued events

### ISSUE THREAD

**Issue by te-online** [segmentio/analytics-react-native#403]
- `analytics-react-native` version: 2.0.0-pilot
- Integrations versions (if used): n/a
- React Native version: 0.64.3
- iOS or Android or both? both

**Steps to reproduce**
Add `analytics-react-native` to app and wait for first batch of events to be sent

**Expected behavior**
If `debug: true` a `console.info` is logged about the number of events being sent

**Actual behavior**
Even with `debug: false` a `console.warning` is logged [from this method](https://github.com/segmentio/analytics-react-native/blob/master/packages/core/src/plugins/SegmentDestination.ts#L81), causing react-native to show a yellow `LogBox` and to print a warning to the developer's console, even though this seems nothing to warn or worry about.

**Comment by oscb** [comment]
Hi Thomas. Thanks for the report! We will address this in the next release of the 2.0 library.
