### ISSUE TITLE
Crash on Emulador without regionCode and languageCode 

### ISSUE THREAD

**Issue by LFMAKER** [segmentio/analytics-react-native#407]
- `analytics-react-native` version: 2.0.0-pilot.1
- Integrations versions (if used): No
- React Native version: 0.66.3
- iOS or Android or both? IOS Only

**Steps to reproduce**
- Install analytics-react-native@2.0.0-pilot.1
- Create a new IOS emulador
- Build app in Debug or Release mode
- Than app will be crash and Xcode will break in this line (line 89).
` let locale = "\(languageCode!)-\(regionCode!)"`

![Screen Shot 2022-01-14 at 16 08 43](https://user-images.githubusercontent.com/8159987/149571505-e837b5c5-abad-4814-840e-42a4839bd2bb.png)

**Expected behavior**
If the languageCode and the regionCode are null, it would be ideal to define an empty string for the locale. This is because emulators when set to default ("United States") will always return null.

**Actual behavior**
When it's an IOS emulator without someone having the region code changed before, it will crash.

How to avoid emulator crash:
- Open the emulator
- Open region settings
- Set the default or any other and wait for it to be applied.
- Build your app.

**Comment by johnsoncwb** [comment]
same error here guys.

**Comment by oscb** [comment]
Thanks for reporting! We'll make sure to include this fix in the next release.
