### ISSUE TITLE
v1.5.1 - error while trying to resolve module

### ISSUE THREAD

**Issue by mlazari** [segmentio/analytics-react-native#417]
When updating from 1.5.0 to 1.5.1 I get this error:
![Simulator_Screen_Shot_-_iPhone_13_Pro_Max_-_2022-01-26_at_09_15_30](https://user-images.githubusercontent.com/4928274/151121325-b93757fb-328d-40ba-bdc4-bd0fda96832f.png)
When comparing the content of [1.5.0](https://registry.npmjs.org/@segment/analytics-react-native/-/analytics-react-native-1.5.0.tgz) and [1.5.1](https://registry.npmjs.org/@segment/analytics-react-native/-/analytics-react-native-1.5.1.tgz) it looks like 1.5.1 is missing the `build` folder, though `main` in `package.json` is still pointing to a file in that folder. Is that a publish issue?
![Screenshot 2022-01-26 at 09 22 13](https://user-images.githubusercontent.com/4928274/151121611-2c348d31-7dea-404e-80c8-cdc17542a324.png)
![Screenshot 2022-01-26 at 09 23 00](https://user-images.githubusercontent.com/4928274/151121618-3dbb3974-c47a-4ac9-8281-c8d4b1931e37.png)

- `analytics-react-native` version: 1.5.1
- Integrations versions (if used): not relevant I think
- React Native version: 0.66.4
- iOS or Android or both? both

**Steps to reproduce**
Install `@segment/analytics-react-native`, version 1.5.1 and start the app.

**Expected behavior**
The app should run without errors.

**Actual behavior**
I get an error saying that metro can't find `node_modules/@segment/analytics-react-native/build/cjs/index.js` (see the screenshot above).

**Comment by efstathiosntonas** [comment]
same here

**Comment by smn-snkl** [comment]
Same here.

**Comment by alanjcharles** [comment]
@mlazari @efstathiosntonas @smn-snkl  thanks for letting us know. We replaced the ci for testing and publishing in the new version (2.0.0) and it seems like it has some unintended consequences. Will fix today and let you know.

**Comment by alanjcharles** [comment]
@mlazari  @efstathiosntonas @smn-snkl  version `1.5.2` is out and is building correctly (for me). Apologies for the inconvenience. Please feel free to re-open if this issue persists.

**Comment by mlazari** [comment]
@alanjcharles Thank you for the quick fix. `1.5.2` works for me.
