### ISSUE TITLE
ERROR  TypeError: null is not an object (evaluating 'RNAppsFlyer.initSdkWithCallBack')

### ISSUE THREAD

**Issue by Akash47** [segmentio/analytics-react-native#420]
- `analytics-react-native` "^2.0.0-pilot:
- Integrations versions (if used):
- React Native version: 0.65.1
-  for  Android

**Steps to reproduce**
npm i "@segment/analytics-react-native-plugin-appsflyer": "^0.1.1-pilot",
import { createClient } from '@segment/analytics-react-native';

import { AppsflyerPlugin } from '@segment/analytics-react-native-plugin-appsflyer';

const segmentClient = createClient({
  writeKey: 'SEGMENT_KEY'
});

const plugin = new AppsflyerPlugin({
  devKey: 'K2***********99',
  isDebug: false,
  appId: '41*****44',
  onInstallConversionDataListener: true, //Optional
  onDeepLinkListener: true, //Optional
  timeToWaitForATTUserAuthorization: 10 //for iOS 14.5
})

segmentClient.add({ plugin });

**Expected behavior**
Push events to Segment. 

**Actual behavior**
Throwing error
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle. ERROR  TypeError: null is not an object (evaluating 'RNAppsFlyer.initSdkWithCallBack')
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling unmountApplicationComponentAtRootTag). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 WARN  Could not receive settings from Segment. Device mode destinations will be ignored unless you specify default settings in the client config.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.

**Comment by alanjcharles** [comment]
@Akash47 I am not able to reproduce with the following config (keys removed). Based on the error message, it seems there is something amiss with your `write-key` or your `SegmentClient` 

```WARN Could not receive settings from Segment. Device mode destinations will be ignored unless you specify default settings in the client config.```

Please confirm you are receiving the settings from Segment on initialization and feel free to reopen with more info if the issue persists.

**Comment by viniciusoliveirabittencourt** [comment]
> @Akash47 I am not able to reproduce. Based on the error message, it seems there is something amiss with your `write-key` or your `SegmentClient`
> 
> `WARN Could not receive settings from Segment. Device mode destinations will be ignored unless you specify default settings in the client config.`
> 
> Please confirm you are receiving the settings from Segment on initialization and feel free to reopen with more info if the issue persists.

I have the same problem. My code be like this 
`import { createClient } from '@segment/analytics-react-native';
import { AppsflyerPlugin } from '@segment/analytics-react-native-plugin-appsflyer';

const segmentClient = createClient({
  writeKey: 'c1v1UsVokPifCguz1lUC813ZStavEf8a',
  trackAppLifecycleEvents: true,
  trackDeepLinks: true,
});

const appsFlyerPlugin = new AppsflyerPlugin({
  devKey: '38wiMmtXCtE5B5Cbnom4EZ',
  isDebug: false,
  appId: 'com.flatmatchapp',
  onInstallConversionDataListener: true,
  onDeepLinkListener: true,
  timeToWaitForATTUserAuthorization: 10
});

segmentClient.add({ plugin: appsFlyerPlugin });

export default segmentClient;`

lookin at error and in the './node_modules/react-native-appsflyer/index.js' I see the code import a class from NativeModules called RNAppsFlyer, but in NativeModules I don't see anything about RNAppsFlyer, and the error appears exactly when RNAppsFlyer is call, saying 'Cannot read properties of undefined'. Maybe it was something about this RNAppsFlyer ?
