### ISSUE TITLE
EXPO init example

### ISSUE THREAD

**Issue by MorenoMdz** [segmentio/analytics-react-native#421]
## Summary
There is some misinformation if this library is usable with Expo managed (Expo Go) or not, based on comments from the Expo team, they stopped support for the original Expo Segment library as this one would be fully supported.

## Proposed Solution

If Expo indeed works with Segment 2.0 for React Native, would be awesome to have a small init example in the readme here.

**Comment by alanjcharles** [comment]
Hi @MorenoMdz the original Expo Segment library was not developed by us or the Expo team and did not work as Segment customers would expect. This library does work with the new Expo EAS managed workflow. We will definitely provide an example as soon as we are able. Thanks for the suggestion!

**Comment by MorenoMdz** [comment]
> Hi @MorenoMdz the original Expo Segment library was not developed by us or the Expo team and did not work as Segment customers would expect. This library (2.0) does work with the new Expo EAS managed workflow. We will definitely provide an example as soon as we are able. Thanks for the suggestion!

Great to hear, waiting for that update.

**Comment by vileikis** [comment]
Yep, it takes quite a good amount of the detective work and I couldn't get it work so far 😥  

Currently, Expo's segment library is **broken for iOS** as it sends incorrect nested payload https://github.com/expo/expo/issues/14218
which breaks most of the marketing destinations (like [Kochava](https://segment.com/docs/connections/destinations/catalog/kochava/) and [Appsflyer](https://segment.com/docs/connections/destinations/catalog/appsflyer/))  and they reject requests 
it was half a year ago and no fix 😞 

@alanjcharles happy to hear the example is coming soon 🙏

**Comment by MrTravisB** [comment]
This would extremely helpful. My recent attempt to get v2 working with a brand new Expo app didn't work at all. In fact, simply calling `createClient` causes the app to not load at all.

**Comment by alanjcharles** [comment]
Hi everyone- I added a note to the readme for initializing this library with an Expo build #442 . After going through the process, I'm not sure it warrants an example app at present. Here are the steps I followed to get everything building on both iOS and Android with a new Expo app. 

1. `expo init segmentExample` (select bare workflow) 
2. `yarn add @segment/analytics-react-native@2.1.2-beta`
3. `yarn add @react-native-async-storage/async-storage && yarn add @segment/sovran-react-native` 
4. `cd ios && pod install` 
5. `cd ..` 
6. `yarn ios/android` 

please feel free to reopen with more information or issues related to building with Expo.

**Comment by MorenoMdz** [comment]
> Hi everyone- I added a note to the readme for initializing this library with an Expo build #442 . After going through the process, I'm not sure it warrants an example app at present. Here are the steps I followed to get everything building on both iOS and Android with a new Expo app.
> 
> 1. `expo init segmentExample` (select bare workflow)
> 2. `yarn add @segment/analytics-react-native@2.1.2-beta`
> 3. `yarn add @react-native-async-storage/async-storage && yarn add @segment/sovran-react-native`
> 4. `cd ios && pod install`
> 5. `cd ..`
> 6. `yarn ios/android`
> 
> please feel free to reopen with more information or issues related to building with Expo.

Sure thing we will give it a try, question is does it work with Expo Go/Sim?

**Comment by alanjcharles** [comment]
@MorenoMdz it does not, I'm afraid. This library supports `Expo's Expo Dev Client & EAS build system`. We do not recommend or support `expo-analytics-segment` (available via the `legacy Expo Go` framework) as it was not built and is not maintained by Segment.

**Comment by MorenoMdz** [comment]
> @MorenoMdz it does not, I'm afraid. This library supports `Expo's Expo Dev Client & EAS build system`. We do not recommend or support `expo-analytics-segment` (available via the `legacy Expo Go` framework) as it was not built and is not maintained by Segment.

Got it, we will have to think about how we are going to manage this. Thanks Alan!

**Comment by alanjcharles** [comment]
no problem! feel free to reach out with any questions. Happy to help where I can. `acharles@twilio.com`

**Comment by mbyrne00** [comment]
Hi @alanjcharles - what does this mean by _legacy Expo Go_? Are you saying "Expo Go" itself is legacy, or just `expo-analytics-segment`?

>  (available via the legacy Expo Go framework)

I _think_ you meant the library itself but just checking I didn't miss anything about Expo Go itself.

**Comment by itaydressler** [comment]
Bumping this up as I'm trying to implement the v2 lib with expo EAS (managed). 
I installed the packages, and things are working on non expo-go builds, but unfortunately I could not get the library disabled when I run it on expo go. 

I tried `require` ing the package only when not on expo go, but the react native metro bundler doesn't see to support conditional imports. 

The error throws is from @segment/sovran-react-native and about not being linked. The issue with the EAS managed builds is that I can't `cd ios && pod install` as there isn't an ios folder in the managed apps. 

Any simple solution on how not to load this lib when running on expo go, but load it only on real builds? 🙏

**Comment by mlalitthapa** [comment]
I am using EAS (managed) workflow and recently upgraded to SDK 46 and switched from `expo-analytics-segment` to this package. Since it does not work with Expo Go app I tried to build dev client for android but the build always fails.

The doc says that only installing the package is enough for the managed workflow but I am not sure what I am doing wrong. Is it the package or the EAS build that is having issues?

<img width="1240" alt="Screen Shot 2022-08-10 at 10 00 37 AM" src="https://user-images.githubusercontent.com/6380157/183814606-20a2e997-f7fc-4e7d-ba61-d7bb8738bb15.png">

**Comment by MorenoMdz** [comment]
> I am using EAS (managed) workflow and recently upgraded to SDK 46 and switched from `expo-analytics-segment` to this package. Since it does not work with Expo Go app I tried to build dev client for android but the build always fails.
> 
> 
> 
> The doc says that only installing the package is enough for the managed workflow but I am not sure what I am doing wrong. Is it the package or the EAS build that is having issues?
> 
> 
> 
> <img width="1240" alt="Screen Shot 2022-08-10 at 10 00 37 AM" src="https://user-images.githubusercontent.com/6380157/183814606-20a2e997-f7fc-4e7d-ba61-d7bb8738bb15.png">
> 
> 

Try to run the build again, but first re install your modules with yarn for example then run the build command with the --clear-cache flag

**Comment by mlalitthapa** [comment]
@MorenoMdz still having the same issue
