### ISSUE TITLE
Android build broken using 2.1.1-beta

### ISSUE THREAD

**Issue by AlexanderEggers** [segmentio/analytics-react-native#431]
When trying to run the latest preview version 2.1.1-beta, I get the following error when running the application:

```
Error: The package 'sovran-react-native' doesn't seem to be linked. Make sure: 

- You rebuilt the app after installing the package
- You are not using Expo managed workflow
```

- `analytics-react-native` version: 2.1.1-beta
- React Native version: 0.67.1

**Steps to reproduce**

Add 2.1.1-beta to your RN project's package.json and run Android.

**Expected behavior**

Latest preview can run without issues on Android.

**Actual behavior**

```
Error: The package 'sovran-react-native' doesn't seem to be linked. Make sure: 

- You rebuilt the app after installing the package
- You are not using Expo managed workflow
```

**Comment by alanjcharles** [comment]
@AlexanderEggers are you using Expo? We have it working with vanilla RN but will take a look at Expo today. The new `@segment/sovran-react-native` package relies pretty heavily on native modules so we might have to build an Expo Config Plugin.

**Comment by AlexanderEggers** [comment]
@alanjcharles Yes correct, the current project I'm working on is using expo version 44.0.6.

**Comment by alanjcharles** [comment]
@AlexanderEggers thanks for letting me know. I'll prioritize expo in the next sprint and let you know as soon as I can.

**Comment by vileikis** [comment]
@alanjcharles I'am facing the same issue with iOS too. 

### My setup
- iOS: 15.2.1
- Expo managed workflow 
- "react-native": "0.64.3",
- "expo": "~43.0.2",
- "expo-dev-client": "~0.6.3",
- "@segment/analytics-react-native": "2.1.1-beta",

### Steps to reproduce with `expo-dev-client`

#### 1. Without old dev build
- Run `yarn add @segment/analytics-react-native@2.1.1-beta`
- Add `import { createClient } from "@segment/analytics-react-native";` (ex: App.js)
- Run `expo start --dev-client` and launch the app
- Results into `Error: The package 'sovran-react-native' doesn't seem to be linked.`

 #### 2. With new dev build
- Run `yarn add @segment/analytics-react-native@2.1.1-beta`
- Add `import { createClient } from "@segment/analytics-react-native";` (ex: App.js)
- Run `eas build --profile development --platform ios`
- Install new app build when ready 
- Run `expo start --dev-client` and launch the app
- Results into **white screen of death** 
   - App will crash after some time
   -  No errors shown at this stage
   -  Phone gets super hot 

@AlexanderEggers do you use expo-dev-client? if so, do you experience the same white screen of death?

**Comment by alanjcharles** [comment]
@vileikis @AlexanderEggers  i'm pretty certain we will have to create a [config plugin](https://blog.expo.dev/expo-managed-workflow-in-2021-d1c9b68aa10) since the new [state management system ](https://github.com/segmentio/sovran-react-native)we added to the beta relies pretty heavily on native modules. I'll get to it as soon as I can but in the meantime feel free to take a closer look yourself and let me know your thoughts.

**Comment by Kerumen** [comment]
I've came across the same issue with the same environment (Expo + Dev Client).
I've tried to install `@segment/sovran-react-native` as a direct dependency of my app: if you install it as a direct dependency, Expo (via RN) can link the native code automatically. Unfortunately, it didn't fix the issue and showed the same "white screen of death" as before.

**Comment by Kerumen** [comment]
Update: I made it works!

I've noticed that I had 2 versions of RN installed in my dependencies. That's because `sovran` declares `react` and `react-native` as a [direct dependency](https://github.com/segmentio/sovran-react-native/blob/557346df922016f3e75cc6663b583a0636771c7e/package.json#L158-L159) which is not correct.
It should be loose peerDependencies ([example from `react-native-reanimated`](https://github.com/software-mansion/react-native-reanimated/blob/7d75b634a6a108a49e0b02f70b80de06230ea919/package.json#L80-L84)).

@alanjcharles Happy to open a PR to fix this if you want!

As a temporary fix on my project, I've added the `resolutions` key in my `package.json`:

```
"resolutions": {
  "react": "17.0.1",
  "react-native": "0.64.3"
}
```

**Comment by AlexanderEggers** [comment]
I can confirm that @Kerumen's solution works for me as well, thanks for that 👍

**Comment by Kerumen** [comment]
@alanjcharles PR here: https://github.com/segmentio/sovran-react-native/pull/15 🙂

**Comment by AlexanderEggers** [comment]
@alanjcharles The latest beta release removes the need to include the `resolutions` part in the setup, but unfortunately the project (due to expo) is still not working without defining `@segment/sovran-react-native` in the `package.json`.

**Comment by alanjcharles** [comment]
@AlexanderEggers thanks for letting me know! I have the same experience. However, since it is working for me in both iOS and Android builds once `@segment/sovran-react-native` is defined, I am going to mark this as resolved for now and add a note in the readme for Expo users. We will also circle back while in beta to see if we can find a better way to optimize this for Expo users. Please feel free to reopen with more info or concerns. Thanks again to you and @Kerumen for the help. 

**this assumes one is not using Expo's legacy `Expo Go & Expo build` framework. This library supports Expo's `Expo Dev Client & EAS build system`.

**Comment by i8ramin** [comment]
I've followed all of the suggestions above, but still facing this issue.

```
Error: The package 'sovran-react-native' doesn't seem to be linked. Make sure:

- You have run 'pod install'
- You rebuilt the app after installing the package
- You are not using Expo managed workflow

at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:204:6 in guardedLoadModule
at http://192.168.1.64:19000/index.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:305898:3 in global code

Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
```

Have pinned `react` and `react-native` versions under package  `resolutions`
```
"resolutions": {
    "react": "17.0.1",
    "react-native": "0.64.3"
}
```

Using the latest versions of `@segment/analytics-react-native` and `@segment/sovran-react-native`
```
    "@segment/analytics-react-native": "^2.1.6-beta",
    "@segment/sovran-react-native": "^0.2.4",
```

Successfully run `pod install` inside the `ios` folder
```
- segment-analytics-react-native (2.1.6-beta):
    - React-Core
 - sovran-react-native (0.2.4):
    - React-Core
```


Running out of ideas. Any suggestions?

**Comment by msluser** [comment]
It has been almost a month without resolution to this issue. @alanjcharles any update on this? Can you re-open this issue please or start another related to Expo SDK 44.0?

Likewise I have followed the suggestions above and I am still having the same issue. I am using this with Expo SDK 44.0 in bare workflow and when running `expo start` with iOS simulator I get:
```
Error: The package 'sovran-react-native' doesn't seem to be linked. Make sure:

- You have run 'pod install'
- You rebuilt the app after installing the package
- You are not using Expo managed workflow

at node_modules/expo/build/logs/LogSerialization.js:156:14 in _captureConsoleStackTrace
at node_modules/expo/build/logs/LogSerialization.js:41:26 in serializeLogDataAsync
- ... 9 more stack frames from framework internals

```
When running  `expo start` with android simulator I get:
```
Error: The package 'sovran-react-native' doesn't seem to be linked. Make sure:

- You rebuilt the app after installing the package
- You are not using Expo managed workflow

at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:204:6 in guardedLoadModule
at http://192.168.71.121:19000/index.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:444016:3 in global code

```

Similar to @i8ramin, I have tried to pin `react` and `react-native` versions under `package.json` `resolutions` with no avail.
```
  "resolutions": {
    "react": "17.0.1",
    "react-native": "0.64.3"
  }
```
I am using these package versions: 
`@segment/analytics-react-native`= 2.1.9
`@segment/sovran-react-native` = 0.2.6

I am out of ideas.

**Comment by weeksie** [comment]
@msluser I was running into the same issue but adding `--clear-cache` to the eas build command seemed to fix things.

**Comment by Moe-kanan** [comment]
+1 I'm still getting the same issue when I run my tests

```
    The package 'sovran-react-native' doesn't seem to be linked. Make sure: 
```

anyone was able to solve this issue?

**Comment by haroonahmad12** [comment]
I was able to solve the issue, had to manually link it in `MainApplication.java`

Step1: Include the project in the `settings.gradle`

`include ':segment_sovran-react-native'`
`project(':segment_sovran-react-native').projectDir = new File(rootProject.projectDir, '../../../node_modules/@segment/sovran-react-native/android')`

Step2: Include it manually in `MainApplication.java`

You first need to import it. 
`import com.sovranreactnative.Sovran;`

Then in the list of Packages add this one. 
` packages.add(new Sovran());`

**Comment by pranavr93** [comment]
+1, running into this issue. As there were expo specific instructions on readme, I assumed things would just work. Would be good to at least make a note on readme.

I tried above fixes and it doesn't seem to work.

**Comment by nickwelp** [comment]
Expo 46 forces us away from Expo's own version and to use Segment's own library, which depends on this one. Setting resolutions to the versions I use (react 18.0.0 and RN 0.69.5) did not fix this issue. 
```
Error: The package 'sovran-react-native' doesn't seem to be linked. Make sure: 

- You have run 'pod install'
- You rebuilt the app after installing the package
- You are not using Expo managed workflow
```
This error happens on iOS and Android. 

I have 
```
    "@segment/analytics-react-native": "^2.7.1",
    "@segment/sovran-react-native": "^0.4.4",
```

**Comment by gantunesr** [comment]
Still facing this issue on 0.4.4 without Expo

**Comment by vijay-j05** [comment]
> Still facing this issue on 0.4.4 without Expo

I am also facing same issue when running jest tests. Appreciate any help or references. Thanks!

**Comment by IB3N** [comment]
Also facing this issue with jest

```
Test suite failed to run

    The package 'sovran-react-native' doesn't seem to be linked.

> 5 | import { AnalyticsProvider } from '@segment/analytics-react-native';
    | ^
```
