### ISSUE TITLE
Our users unable to use @segment/analytics-react-native-clevertap due to restricted dependency 'Segment-CleverTap', '~> 1.1.4'

### ISSUE THREAD

**Issue by piyush-kukadiya** [segmentio/analytics-react-native#441]
We have released [Segment-CleverTap iOS v1.2.1](https://github.com/CleverTap/clevertap-segment-ios/releases/tag/1.2.1) but 
 @segment/analytics-react-native-clevertap unable to fetch latest dependency due to restricted dependency declared as below in  @segment/analytics-react-native-clevertap 
`'Segment-CleverTap', '~> 1.1.4'`

Our users have halted their release due this. Can we have urgent fix over here @oscb.

Thanks a ton.

**Comment by alanjcharles** [comment]
@piyush-kukadiya resolved with [`@segment/analytics-react-native-clevertap@1.5.2`](npmjs.com/package/@segment/analytics-react-native-clevertap/v/1.5.2) thanks for letting us know and please feel free to reopen if you run into any other issues.
