### ISSUE TITLE
How to record traits without userId? (typescript)

### ISSUE THREAD

**Issue by cheolee** [segmentio/analytics-react-native#45]
In analytics.d.ts, identify() requires `user`(userId) parameter.
```
identify(user: string, traits?: JsonMap): Promise<void>;
```

But docs tells userId can be omitted if wanna just record traits.

https://segment.com/docs/sources/mobile/react-native/#identify
> userId | The database ID for this user. If you don’t know who the user is yet, you can omit the userId and just record traits. You can read more in the identify reference.

How can I omit `userId` when call identify() in typescript?

**Comment by TeresaNesteby** [comment]
Hi @cheolee - thanks for reaching out! For support questions, please reach out to our team directly at https://segment.com/contact/.

**Comment by kasterlod** [comment]
hello @cheolee , please try with empty string, it works for me

**Comment by cheolee** [comment]
> hello @cheolee , please try with empty string, it works for me

Thank you @kasterlod ! I will try it. 🙏
