### ISSUE TITLE
2.1.5-beta breaks imports and types provided by the package

### ISSUE THREAD

**Issue by AlexanderEggers** [segmentio/analytics-react-native#453]
- `analytics-react-native` version: 2.1.5-beta
- React Native version: 0.67.3
- iOS or Android or both? both

**Steps to reproduce**

- Update to 2.1.5-beta
- You will have no imports and types provided by the package anymore

**Expected behavior**

Types and imports are working fine.

**Actual behavior**

Imports and types are broken

**Comment by alanjcharles** [comment]
@AlexanderEggers really sorry about that. We are still working out the kinks of our ci and automation. I just published [`v2.1.6-beta`](https://www.npmjs.com/package/@segment/analytics-react-native/v/2.1.6-beta) and it includes the lib directory with all of the imports/types. Thank you very much for letting us know so quickly.
