### ISSUE TITLE
IDFA plugin stops working after closing and reopening the app.

### ISSUE THREAD

**Issue by Jack-Gill-TH** [segmentio/analytics-react-native#469]
- `analytics-react-native` version: `"@segment/analytics-react-native": "2.1.7",`
- Integrations versions (if used): `"@segment/analytics-react-native-plugin-idfa": "^0.2.0-beta","@segment/sovran-react-native": "^0.2.4",`
- React Native version: `"react-native": "0.63.4",`
- iOS or Android or both? Only tested on iOS so far.

**Steps to reproduce**

IDFA plugin stops working after closing and reopening the app. I followed the readme steps for integrating the IDFA plugin, which I wanted to do so that segment would successfully send events to our facebook destination. This works correctly the very first time the app is opened and asks for permission to track (I see successful events sent to facebook on the Segment dashboard) If I close and reopen the app, it no longer works (The dashboard goes back to reporting failed events because of invalid configuration)

Using the regular segment event debugger I can see that the successful events do include the advertising ID as part of the 'device' property. Unsuccessful ones do not. Also I can see that after closing and reopening the app the 'adTrackingEnabled.get' method on the client returns false. 

**Notes**

The app I'm working on is not an expo app. I'm not absolutely sure if I'm supposed to be adding sovran-react-native as a dependency - the documentation is a little unclear.

**Comment by oscb** [comment]
Hi @Jack-Gill-TH ,
I just confirmed this bug was happening in the latest version of the library. Seems to be related to the way the context was restored on startup. I'm submitting a fix, it only needs an upgrade on the core package.

**Comment by Jack-Gill-TH** [comment]
Hey @oscb ! Thanks for letting me know, and for jumping on a fix for it 👍
