### ISSUE TITLE
Lifecycle events are not tracked on iOS

### ISSUE THREAD

**Issue by vytautasvargonas** [segmentio/analytics-react-native#476]
We noticed that we only receive the app lifecycle events from android devices, not from iOS. Specifically looked at Application Opened, Application Backgrounded events.
Regular tracking events work for both platforms.

- `analytics-react-native` version: 1.5.0
- Integrations versions (if used): analytics-react-native-appboy: 1.5.0
- React Native version: 0.66.4
- iOS

**Steps to reproduce**

our setup function:
```
export const setupAnalytics = async () => {
  const apiKey = Platform.select({
    ios: Config.SEGMENT_API_KEY_IOS,
    android: Config.SEGMENT_API_KEY_ANDROID,
    default: Config.SEGMENT_API_KEY_IOS,
  });

  await analytics.setup(apiKey, {
    using: [BrazeSegmentIntegration],

    // We use onStateChange + React Navigation to do this.
    recordScreenViews: false,
    // Record certain application events such as the Application Installed, Application Updated and Application Opened automatically
    // https://segment.com/docs/connections/spec/mobile/
    trackAppLifecycleEvents: true,
  });
};
```

**Expected behavior**

Expect to receive application lifecycle events for both iOS and Android

**Actual behavior**

Only receiving application lifecycle events for Android

**Comment by alanjcharles** [comment]
@vytautasvargonas  versions of `analytics-react native > 2.0.0` do not support `react-native 0.66.4`, I'm afraid. We currently do not have plans to do any additional work on those versions and instead, recommend updating to our latest in order to successfully receive lifecycle events. You can find the [migration guide here](https://github.com/segmentio/analytics-react-native/blob/master/MIGRATION_GUIDE.md). Please feel free to reach out to [friends@segment.com](mailto:friends@segment.com) with any additional questions

**Comment by vytautasvargonas** [comment]
For future reference solution was to add 
`segmentConfig.trackApplicationLifecycleEvents = YES;`
to the ios native initialisation in `AppDelegate.m`

full code:

```
  NSString *segmentWriteKey = [ReactNativeConfig envFor:@"SEGMENT_API_KEY_IOS"];
  SEGAnalyticsConfiguration *segmentConfig = [SEGAnalyticsConfiguration configurationWithWriteKey:segmentWriteKey];
  segmentConfig.launchOptions = launchOptions;
  segmentConfig.trackApplicationLifecycleEvents = YES;

  [segmentConfig use:[SEGAppboyIntegrationFactory instance]];
  [SEGAnalytics setupWithConfiguration:segmentConfig];

  [[SEGAppboyIntegrationFactory instance] saveLaunchOptions:launchOptions];
```
