### ISSUE TITLE
Error: The package 'sovran-react-native' doesn't seem to be linked.

### ISSUE THREAD

**Issue by clinton15** [segmentio/analytics-react-native#478]
issue #474 is still occuring for me. I already tried installing sovran-react-native library itself but the error is still seen. Any suggestions on how to resolve it?

**Comment by alanjcharles** [comment]
@clinton15 have you tried deleting your `node_modules/ yarn.lock` running `yarn`   and then `yarn add @segment/sovran-react-native` ? Don't forget to add update your `podfile` as well. If the issue persists please feel free to re-open with more information including your environment and versions.

**Comment by clinton15** [comment]
@alanjcharles  I'm still facing this issue even after implementing your suggestions.

analytics-react-native version: 2.1.12
sovran-react-native version: 0.2.6
react-native-cli: 2.0.1
react-native: 0.67.3
iOS or Android or both? - Android

**Comment by zhigang1992** [comment]
You have to include sovran-react-native in package.json's dependencies field to have it be picked up by auto-linking

**Comment by clinton15** [comment]
@zhigang1992 I already have it included in my package.json's dependencies.
```
 "@segment/analytics-react-native": "^2.1.12",
 "@segment/sovran-react-native": "^0.2.6",
```

**Comment by Moe-kanan** [comment]
+1 my tests are failing! any ideas on how to solve this? 
```
    The package 'sovran-react-native' doesn't seem to be linked. Make sure: 
```
