### ISSUE TITLE
How to disable the library when running on dev local

### ISSUE THREAD

**Issue by MorenoMdz** [segmentio/analytics-react-native#483]
We are migrating our project from Expo (Go) to the new dev clients, I have the new builds working with the newest version of Segment, but we want to be able to skip the initialization of Segment when running on local dev. Previously we had an `enable` flag we passed to the Expo library and we used it set to `false` when running locally.

**Expected behavior** 
Disable analytics on local dev.

**Actual behavior**
All track calls are being sent even on local.

**Comment by oscb** [comment]
This is not something we currently have in the library but it would be a good thing to add in a future release. I'll add a tag to keep it in mind.

For now I suggest using the `__DEV__` env var. You can use it to change the `writeKey` to use a different source if you are in dev mode. 

You can configure that source to not to send any event to your destinations but you'll still be able to see the events in the segment debugger to confirm everything looks good.

**Comment by MorenoMdz** [comment]
> This is not something we currently have in the library but it would be a good thing to add in a future release. I'll add a tag to keep it in mind.
> 
> For now I suggest using the `__DEV__` env var. You can use it to change the `writeKey` to use a different source if you are in dev mode.
> 
> You can configure that source to not to send any event to your destinations but you'll still be able to see the events in the segment debugger to confirm everything looks good.

In the Web version, we do skip the analytics initialization when running on localhost, I might have to do something similar here, the `enable` flag is pretty helpful in the expo go / node SDKs, for example, we have had issues with our MTU count spiking because we ran some test migrations on local using skewed prod data, that basically doubled our MTU count as the Segment tracks were still going out, so we do need to disable it locally in a way or another. ><

**Comment by alanjcharles** [comment]
@MorenoMdz you can just replace your write-key  with an empty string in dev for now if it helps. The segment endpoints will still accept the calls they just won't be pushed through your source. Alternatively, you can make a free account and route your dev calls to that workspace to avoid adding to your MTU count in prod. Would either of these help until we can prioritize this?

**Comment by MorenoMdz** [comment]
> @MorenoMdz you can just replace your write-key with an empty string in dev for now if it helps. The segment endpoints will still accept the calls they just won't be pushed through your source. Alternatively, you can make a free account and route your dev calls to that workspace to avoid adding to your MTU count in prod. Would either of these help until we can prioritize this?

I think so yes, we will start using the new library soon, I will add those changes to our setup.

**Comment by pTinosq** [comment]
It's been two years - is there a better way of handling this instead of just replacing the string with empty?

A simple `enabled: boolean` flag would solve this issue.
