### ISSUE TITLE
FacebookAppEventsPlugin is not a valid Plugin

### ISSUE THREAD

**Issue by MorenoMdz** [segmentio/analytics-react-native#484]
The plugin `FacebookAppEventsPlugin` exported from `@segment/analytics-react-native-plugin-facebook-app-events` is not considered a valid plugin, it does have a typescript warning and also fails to load.

We are running in the new Expo dev clients, the app was rebuilt for iOS simulator after installing it, the app loads correctly, Segment is tracking normally, but the plugin throws `TypeError: null is not an object (evaluating 'AppEventsLogger.getConstants')` 

  `"@segment/analytics-react-native": "^2.1.9"`
   `"@segment/analytics-react-native-plugin-facebook-app-events": "^0.2.1"`
- React Native version:  0.64.3
- iOS or Android or both?  iOS

**Steps to reproduce**
Install analytics RN and the facebook plugin, load with:

<img width="460" alt="image" src="https://user-images.githubusercontent.com/29472480/159808795-b8913f4d-3ae6-4541-8045-a1e3f95e49b7.png">

**Expected behavior**
Facebook events to be tracked.

**Actual behavior**
`TypeError: null is not an object (evaluating 'AppEventsLogger.getConstants')`

**Comment by oscb** [comment]
Hi @MorenoMdz ,
We were missing a dependency that needs to be manually installed for RN to link it for the FacebookPlugin, I'll update the readme:

You need to install the npm package [react-native-fbsdk-next](https://www.npmjs.com/package/react-native-fbsdk-next):

```
npm install -s react-native-fbsdk-next
```

Let me know if this solves the issue!

**Comment by MorenoMdz** [comment]
Perfect I'll give it a try thank you

**Comment by MorenoMdz** [comment]
I was able to run the build without crashing now, the type is still complaining `Type 'FacebookAppEventsPlugin' is not assignable to type 'Plugin'.`, should I be importing the plugin from somewhere else?

**Comment by oscb** [comment]
What does your import look like?

**Comment by MorenoMdz** [comment]
> What does your import look like?

With `import { FacebookAppEventsPlugin } from '@segment/analytics-react-native-plugin-facebook-app-events'`

**Comment by oscb** [comment]
Uhmm, that's strange, it does look correct.


I just retested our example app adding the FB Plugin with the same import and didn't get that error about the types. Can you double check that there's nothing else that might be causing a dependency issue? Maybe try deleting `node_modules` and reinstall?

**Comment by MorenoMdz** [comment]
> Uhmm, that's strange, it does look correct.
> 
> I just retested our example app adding the FB Plugin with the same import and didn't get that error about the types. Can you double check that there's nothing else that might be causing a dependency issue? Maybe try deleting `node_modules` and reinstall?

I will try, the example you say is the one we have in the docs, not one specific to Facebook right?

**Comment by oscb** [comment]
The example in this repo. 


I just uncommented the lines in here: 
https://github.com/segmentio/analytics-react-native/blob/8faba2d940f2bfdd31a9df6b4223c0ededd2a21a/example/src/App.tsx#L28 

And here: 

https://github.com/segmentio/analytics-react-native/blob/8faba2d940f2bfdd31a9df6b4223c0ededd2a21a/example/src/App.tsx#L55

And made sure to add the FB package: `yarn example add react-native-fbsdk-next`

**Comment by MorenoMdz** [comment]
@alanjcharles I am still seeing the type error, this is the current code we have:

```js
import { Break, Company, IWorkedShiftState, Shift } from '../types'
import Constants from 'expo-constants'
import { getEnvironment } from 'utils/system'
import * as Sentry from 'sentry-expo'

import Env from 'constants/Env'
import { Platform } from 'react-native'
import { createClient } from '@segment/analytics-react-native'
import { SegmentClient } from '@segment/analytics-react-native/lib/typescript/src/analytics'
import { FacebookAppEventsPlugin } from '@segment/analytics-react-native-plugin-facebook-app-events'

import { Transaction } from '../types/payments'
import { ExploreFiltersTracking } from '../hooks/useExploreFilters'

const androidWriteKey = 'key'
const androidDevWriteKey = 'key'
const iosWriteKey = 'key'
const iosDevWriteKey = 'key'

const env = getEnvironment()
const isProd = env === 'production'

const keyset = {
  androidWriteKey: isProd ? androidWriteKey : androidDevWriteKey,
  iosWriteKey: isProd ? iosWriteKey : iosDevWriteKey,
}

/**
 * Initialize the whole analytics tracking here
 */
let segmentClient: SegmentClient | undefined
export function getAnalytics() {
  try {
    const isLocal = Env.ENV_NAME === 'local'
    console.log(!isProd && '...Initializing Segment in development mode...')

    /**
     * If running local use a null write key, Segment calls will be sent but be ignored by Segment
     * This is a workaround recommended by the Segment team until a native disable flag is re-added
     * https://github.com/segmentio/analytics-react-native/issues/483#issuecomment-1106663656
     */
    if (isLocal) {
      console.log('...Skipping Segment in local mode')
    }
    const writeKey = isLocal
      ? ''
      : Platform.OS === 'ios'
      ? keyset.iosWriteKey
      : keyset.androidWriteKey
    segmentClient = createClient({
      writeKey,
      trackAppLifecycleEvents: true,
      collectDeviceId: true,
      debug: false, // set to "true" to log events to console on local
      trackDeepLinks: true,
    })

    segmentClient.add({ plugin: new FacebookAppEventsPlugin() })

    return segmentClient
  } catch (error) {
    console.log('analyticsInit', error)
    Sentry.Native.captureException(error)
  }
}
export { segmentClient }

```

This is the type error:

![image](https://user-images.githubusercontent.com/29472480/181308972-e8f0902d-eae5-46cc-b3cf-66da8e8e8922.png)
