### ISSUE TITLE
Segment failure retries have no pause in between

### ISSUE THREAD

**Issue by AlexanderEggers** [segmentio/analytics-react-native#497]
I have a setup at my home which blocks certain requests from going outside (part of that is segment) - one reason why I cannot test segment well in my wifi network but that is not an issue for me 😆 

The acutal issue is that because my proxy blocks the requests from going out, the segment SDK retries failures extremely fast to a level which actually crashes devices. That is related to https://github.com/segmentio/analytics-react-native/issues/448 which I thought have fixed the issue but it seems like there was a scenario missed. 

@oscb I think you might have missed something in your PR https://github.com/segmentio/analytics-react-native/pull/457.

- `analytics-react-native` version: v2.1.9
- React Native version: 0.68.0
- iOS or Android or both? Android

**Steps to reproduce**
- Have outgoing segment events always fail via a proxy or dns filter
- Try sending segment events
- You will notice that segment cannot fetch its settings but is also re-sending events extremely fast.

**Expected behavior**
- Segment should respect the retry interval for re-fetching its settings and sending events.

**Actual behavior**
- Sending events and settings re-fetch in an extreme speed which crashes devices.

**Comment by AlexanderEggers** [comment]
Just wondering, do you have an ETA on that? Just so that I can some planning myself in regards to releases etc.

**Comment by oscb** [comment]
Hey @AlexanderEggers , sorry for the wait. I published a hot fix today in v2.1.11 that addresses this issue. We have a change freeze for the rest of the week but let me know if you bump into any issue!

**Comment by AlexanderEggers** [comment]
Which PR refers to the fix? Is https://github.com/segmentio/analytics-react-native/pull/502 included in today's release?

**Comment by oscb** [comment]
It's in this [commit](https://github.com/segmentio/analytics-react-native/commit/133b82117ce0cbd0ad2280867bda202bea35dab6)
