### ISSUE TITLE
Use of undeclared identifier error: 'AnalyticsReactNative'

### ISSUE THREAD

**Issue by sergey-ovdienko** [segmentio/analytics-react-native#511]
I'm trying to enable deep link tracking on iOS. In the docs it says to add this snippet to `AppDelegate.m`:

```obj-c
- (BOOL)application:(UIApplication *)application
            openURL: (NSURL *)url
            options:(nonnull NSDictionary<UIApplicationOpenURLOptionsKey, id> *)options {

  [AnalyticsReactNative trackDeepLink:url withOptions:options];  
  return YES;
}
```

However, when doing so, I get "Use of undeclared identifier error: 'AnalyticsReactNative'" error:
<img width="818" alt="Use of undeclared identifier error" src="https://user-images.githubusercontent.com/36043627/165096827-664024fe-55e8-417a-a585-ec9605f84016.png">

It looks like I need to `#import` something, but it's not clear what exactly? Could you please update the instructions?

- `analytics-react-native` version: 2.1.11
- Integrations versions (if used): not used
- React Native version: 0.68.1
- iOS or Android or both? iOS

**Steps to reproduce**
Just follow the [installation guide](https://segment.com/docs/connections/sources/catalog/libraries/mobile/react-native/), it fails on the "Set up iOS Deep Link Tracking" step.

**Expected behavior**
Code snippet contains necessary import statements.

**Actual behavior**
Code snippets is missing some statements.

**Comment by alanjcharles** [comment]
Hi @sergey-ovdienko you have to import `segment_analytics_react_native` https://github.com/segmentio/analytics-react-native/blob/master/example/ios/AnalyticsReactNativeExample/AppDelegate.m#L16

I will fix the readme as well. Please feel free to reopen if you are still running into issues.

**Comment by sergey-ovdienko** [comment]
Hi @alanjcharles,
Thanks for the quick response and updated instructions! Now it builds as expected.

However, to make it work I had to also add `-fcxx-modules` compiler flag:
<img width="743" alt="Screenshot 2022-04-26 at 15 53 29" src="https://user-images.githubusercontent.com/36043627/165304388-444725b4-ef24-417a-9856-d1121db46ecc.png">

It was pretty straight-forward to figure out, but maybe worth mentioning in the docs too.

**Comment by minhchienwikipedia** [comment]
The same issue @alanjcharles the page was not found, can you update in the docs

**Comment by trujic1000** [comment]
It would be helpful if this documentation could also be updated to include the import line. https://segment.com/docs/connections/sources/catalog/libraries/mobile/react-native/
