### ISSUE TITLE
Clarifying Device Mode + Plugins + Mixpanel Super Properties

### ISSUE THREAD

**Issue by amy-dorsia** [segmentio/analytics-react-native#512]
- `"@segment/analytics-react-native": "^2.1.9",`
- `"@segment/analytics-react-native-plugin-mixpanel": "^0.1.1",`
- React Native version: 0.64.3
- iOS or Android or both? iOS

Hello hello! I'm working on a segment + mixpanel integration on an app and am hitting issues when it comes to implementing [super properties](https://segment.com/docs/connections/destinations/catalog/mixpanel/#register-super-properties), which requires a device-mode connection. I'm trying to approach it via a plug-in, but am hitting other issues there as well, so there's a few questions I'm trying to get answered:

1. is there a way to set up device mode for this library? The old docs reference the previous way of setup with `using:` ([link](https://segment.com/docs/connections/destinations/catalog/mixpanel/#getting-started))
2. As it stands, I'm getting weird behavior while using the Mixpanel Plugin — e.g. different `insert_id`s for the same event and a failure to actually reset the user identifier on calling `reset()` — are these bugs or just expected behavior?
3. will setting `autoAddSegmentDestination = false` mean that the events won't end up in segment, or will it eventually sent asynchrously (like in device-mode?)

Would love answers as I've been struggling with this for a bit and haven't been able to get answers in my googling 😭 

**Steps to reproduce**
set up analytics as follows:

```js
import {
  createClient,
  AnalyticsProvider,
} from '@segment/analytics-react-native';
import { MixpanelPlugin } from '@segment/analytics-react-native-plugin-mixpanel'

... 

const segmentClient = createClient({
  writeKey:...
  trackAppLifecycleEvents: true,
});

segmentClient.add({ plugin: new MixpanelPlugin({
  key: ...,
}) });

export default function App() {
  return (
    <AnalyticsProvider client={segmentClient}>
      <RestOfTheApp/>
    </AnalyticsProvider>
  );
}

```

**Expected behavior**
- sends events to both segment and mixpanel, with the same Insert ID for each event
- resets the user id on calling `reset()`

**Actual behavior**
- sends events to both segment and mixpanel with different Insert IDs for each event
- does not reset the user id on calling `reset()`

**Comment by alanjcharles** [comment]
Hi @amy-dorsia, sorry to hear you're running into issues. To answer your questions. 

> 1. is there a way to set up device mode for this library? The old docs reference the previous way of setup with using: ([link](https://segment.com/docs/connections/destinations/catalog/mixpanel/#getting-started))

This documentation refers to the old version of this library ( > `2.0.0`). However, you can consider Destination Plugins to be the same as a Device Mode Connection. 

> 2. As it stands, I'm getting weird behavior while using the Mixpanel Plugin — e.g. different insert_ids for the same event and a failure to actually reset the user identifier on calling reset() — are these bugs or just expected behavior?

I am not  entirely familiar with `insert_ids`, I'm afraid. These are added automatically by the [Mixpanel SDK](https://help.mixpanel.com/hc/en-us/articles/115004613766-Default-Properties-Collected-by-Mixpanel) and aren't something we manipulate in any way in the [Mixpanel Destination Plugin](https://github.com/segmentio/analytics-react-native/tree/master/packages/plugins/plugin-mixpanel).  

As for the reset issue, it's hard to say without more information. [As you can see here](https://github.com/segmentio/analytics-react-native/blob/master/packages/plugins/plugin-mixpanel/src/MixpanelPlugin.ts#L89), when you call the Segment `reset()` method, we simply invoke Mixpanel's `reset()` method. Are you not able to reset the Mixpanel unique identifier or the Segment one? 

> will setting autoAddSegmentDestination = false mean that the events won't end up in segment, or will it eventually sent asynchrously (like in device-mode?)

This will stop your events from being sent to Segment. A good way to think about Device vs Cloud Mode is as follows- 

**Cloud Mode:** Your events are sent to Segment first and from there, to your Destinations via a server-side request. 

**Device Mode:** Your events will be sent to Segment and handed off to the Destination's SDK. Events are sent to the Destination directly from the device via the Destination's SDK. 

[More documentation](https://segment.com/docs/connections/destinations/#connection-modes)

I hope this helps! Please feel free to reach out to friends@segment.com for additional support.

**Comment by amy-dorsia** [comment]
Hi @alanjcharles! 

Thank you for the speedy response! I'll focus on Destination Plugins rather than the Device Mode, then. RE: `reset()` I think you linked me to the line for `flush` — is there somewhere else you meant to link?

**Comment by alanjcharles** [comment]
no problem! Oops 😅  I definitely misread that. We don't currently access the `reset()` method in the Mixpanel Plugin. Is that something you're looking for? If so, we can definitely add it. I'll try to find some cycles for it this week.

**Comment by amy-dorsia** [comment]
> no problem! Oops 😅 I definitely misread that. We don't currently access the `reset()` method in the Mixpanel Plugin. Is that something you're looking for? If so, we can definitely add it. I'll try to find some cycles for it this week.

@alanjcharles No worries 😅 would be great to have that! Otherwise we'd be unable to track multiple users on one device

**Comment by alanjcharles** [comment]
@amy-dorsia makes sense! #513

**Comment by alanjcharles** [comment]
@amy-dorsia  `reset()` is available in [`@segment/analytics-react-native-plugin-mixpanel@0.2.0`](https://www.npmjs.com/package/@segment/analytics-react-native-plugin-mixpanel). With that in mind, I'm going to close out this issue for now. Please feel free to open another if you run into anything else or reach out to friends@segment.com. Thanks!
