### ISSUE TITLE
Install attribution callback never initialised for AdjustPlugin

### ISSUE THREAD

**Issue by janyk** [segmentio/analytics-react-native#516]
The install attribution callback for Adjust will never be initialised - it is gated behind an if statement that as far as I know will never be true

See this line below, the private property `adjust` doesn't seem to be instantiated ever

https://github.com/segmentio/analytics-react-native/commit/14afe147e89f1820c916e563f52efeb1a7324b30#diff-bca6366748d4475793fd34a2f24d3b98362adac7d4befddd378a9d159dd457b3R39

Potentially the intention was to instantiate the AdjustConfig via a constructor argument?
Given the current design, I don't believe this `if` statement needs to be there, if it doesn't - I'm happy to introduce a PR to remove it

- `analytics-react-native` version: 2.1..10
- Integrations versions (if used): react-native-plugin-adjust: 0.3.0
- React Native version: 0.64.2

**Steps to reproduce**
Setup the Adjust integration as per the docs here: https://segment.com/docs/connections/destinations/catalog/adjust/
**Expected behavior**
The install attribution callback will be triggered when the app is installed from a tracking url from Adjust
**Actual behavior**
While the attribution happens in the Adjust SDK, the attribution callback isn't fired - and subsequently, the tracking event is not sent to Segment

**Comment by alanjcharles** [comment]
thanks @janyk! fix available in [0.3.1](https://www.npmjs.com/package/@segment/analytics-react-native-plugin-adjust)
