### ISSUE TITLE
proxy missing in the setup config

### ISSUE THREAD

**Issue by jayasme** [segmentio/analytics-react-native#520]
## Summary

Before version 2.0 it has a proxy property in the type `Configuration` and received by the `setup` function, so I can set the proxy info to the Segment, but after I upgraded the version to 2.x, the `proxy` is no longer supported, however, this is an important function I need, is there a way to add the proxy to Segment?
I can't find why it has been removed from `README.md` or `CHANGELOG.md` even `CHANGELOG.md` has been removed as well, nor in the migration guide, nor in the documentation.

## Proposed Solution

Bring `proxy` back! THANK YOU!

**Comment by 509dave16** [comment]
## Proposed Solution
The following changes would need to be done at minimum in order for Analytics React Native to support the `proxy` client option again:
- Update `Client Options` section table in `README.md` to include a row for `proxy` which will be a `string`
- Update `Config` typescript interface for client options argument passed to `createClient` to include `proxy` as a `string`
- Update `sendEvents.ts` to reference `proxy` from `config` parameter

**Comment by 509dave16** [comment]
@jayasme The `proxy` client option should be available in the next release. Will probably happen later this week. Hope that helps!

**Comment by oscb** [comment]
This is now released! https://github.com/segmentio/analytics-react-native/releases/tag/%40segment%2Fanalytics-react-native-v2.3.1
