### ISSUE TITLE
Does not build when Expo modules are used

### ISSUE THREAD

**Issue by sergey-ovdienko** [segmentio/analytics-react-native#523]
I have an issue building the app after installing both Expo and Segment Analytics. The error I get doesn't give me any clue of what could be wrong. Here is what I get:

<img width="262" alt="Screenshot 2022-05-03 at 15 09 33" src="https://user-images.githubusercontent.com/36043627/166450214-9ee329c9-1fe6-48a0-8154-fd6c8915e96a.png">

Here is the repo where it's reproducing: https://github.com/sergey-ovdienko/rn-expo-segment-demo

It's a bare minimum React Native app with only Expo and Segment Analytics installed. It's not a managed Expo workflow, so it should be supported as far as I understand.

Android is not configured in the repo, but it works fine. The issue is only with iOS.

- `analytics-react-native` version: 2.1.12
- Integrations versions (if used): not used
- React Native version: 0.68.1
- iOS or Android or both? iOS

**Steps to reproduce**
1. Init new React Native project via `npx react-native init NewProject` command.
2. Install Expo modules by the official guide: https://docs.expo.dev/bare/installing-expo-modules/
3. Install Segment Analytics by the official guide: https://segment.com/docs/connections/sources/catalog/libraries/mobile/react-native/

**Expected behavior**
Project builds and everything works.

**Actual behavior**
Project does not build.

**Comment by alanjcharles** [comment]
Hi @sergey-ovdienko not sure what you're running into exactly as I'm not able to reproduce with the following steps:

1. `npx react-native expoBuild` 
2. `npx install-expo-modules`
3. `yarn add @segment/analytics-react-native @segment/sovran-react-native @react-native-async-storage/async-storage`
4. `cd ios && pod install` 
5.  add Segment Client 
![image](https://user-images.githubusercontent.com/50601149/166803007-937714ce-3957-4624-b0c3-fea202a7b005.png)

6. wrap app in Analytics Provider
![image](https://user-images.githubusercontent.com/50601149/166803139-9cfe07d4-89fc-41be-8c8e-138b039331d8.png)

7. see app build successfully 
![image](https://user-images.githubusercontent.com/50601149/166803271-8b2ad2c7-38d8-45bc-973d-48aeba21018f.png)

8. confirm events are arriving in my source
![image](https://user-images.githubusercontent.com/50601149/166803456-132d1279-db6d-4648-94fa-78fbd3224d95.png)

Please feel free to reopen with more information or reach out to friends@segment.com for additional support.

**Comment by sergey-ovdienko** [comment]
Sorry @alanjcharles I forgot to mention that you have to set up iOS deep linking.

I mean this code:
```obj-c
@import segment_analytics_react_native;
...
- (BOOL)application:(UIApplication *)application
            openURL: (NSURL *)url
            options:(nonnull NSDictionary<UIApplicationOpenURLOptionsKey, id> *)options {

  [AnalyticsReactNative trackDeepLink:url withOptions:options];  
  return YES;
}
```

It fails to build after adding this code. Without it it builds fine.
