### ISSUE TITLE
Support for IOS platform 10

### ISSUE THREAD

**Issue by segebee** [segmentio/analytics-react-native#535]
## Summary
My team is upgrading to the latest version of the RN Library and I love it so far.
For android, we were able to provide support for existing apps that are on `minSdk 17` using the @override feature

However, overrides are not available for iOS and we can't proceed with the upgrade due to the error below:

```
[!] CocoaPods could not find compatible versions for pod "segment-analytics-react-native":
  In Podfile:
    segment-analytics-react-native (from `../node_modules/@segment/analytics-react-native`)

Specs satisfying the `segment-analytics-react-native (from `../node_modules/@segment/analytics-react-native`)` dependency were found, but they required a higher minimum deployment target.
error Command failed with exit code 1.
```
We are currently on `platform 10`

## Proposed Solution

Allow support for `platform 10` for iOS

**Comment by oscb** [comment]
Closing this one, we won't be adding support for older versions of iOS in the near future
