### ISSUE TITLE
Type for properties defined to `jsonMap`

### ISSUE THREAD

**Issue by MorenoMdz** [segmentio/analytics-react-native#536]
## Summary

This is causing a lot of discussion in our team, I wonder why the Segment team decided to have the properties type defined as `jsonMap`? 

One of the solutions I found was to use this method to index the types so typescript accepts it, but the contra point is that it might swallow type errors that could cause the track call to not work:

```js
export const indexed = <T extends {}>(obj: T): T & { [key: string]: never } =>
  obj
```

And then it wraps the properties like this:
```js
     track('Event Name',  indexed(object) )
```

What would be a better way to type the specifics in a way that the track method accepts it? The properties object shape is very dynamic after all.

## Proposed Solution

Add typescript examples in the documentation would be very helpful

**Comment by MorenoMdz** [comment]
For more context, passing a Set using the type converter there will make the whole event not being sent without errors.

**Comment by MorenoMdz** [comment]
![image](https://user-images.githubusercontent.com/29472480/167973594-74ffed7d-5a8e-418d-848e-59f58248c9f8.png)

**Comment by oscb** [comment]
@MorenoMdz this is by design. The idea of  the `JsonMap` type is to guarantee that the properties passed along are serializable into a JSON, here is the [type](https://github.com/segmentio/analytics-react-native/blob/f865d480479be83e0fa2f52137928925c781d238/packages/core/src/types.ts#L10). We don't want to make any assumptions on how to serialize objects so we leave that to the caller.

In your scenario TS is warning because Date is an object, you will need to convert it into a string or number depending on your scenario.

A quick example of what you could do:
```ts
track('Event name', {
  ...trackedData,
  startTime: trackedData.startTime.getTime(), // to get the ms value
});
```

**Comment by MorenoMdz** [comment]
> type

Got it, isn't it possible for the library to serialize everything before sending it? Yes, some of the end data will be wrong but then it is up to us to define it, right now we are having to do a whole lot of conversions to send the data we need.

One example that is giving me a hard time:

```
TRACK event saved Object {
  "event": "Explore Filters Updates Applied",
  "properties": Object {
    "days": Array [
      "TU",
      "WE",
      "TH",
      "FR",
      "SA",
    ],
    "distance": 60,
    "endTimeMax": 16,
    "endTimeMin": 0,
    "startTimeMax": 13,
    "startTimeMin": 0,
    "waitlist": false,
  },
  "type": "track",
}
```

The type is just strings and an array of strings, which seems to be supported by the `jsonMap` type, yet this is the error we get:

![image](https://user-images.githubusercontent.com/29472480/168082221-a58c771d-eb1b-4b52-bc7b-af721189cdfb.png)

**Comment by MorenoMdz** [comment]
Quick update, that crypt error was caused because our Days is a Set, which gets converted to an Array type if we use the `indexed` function above, so using this hacky converter makes TS happy: 
```js
export const convertFiltersToString = (filters: ExploreFiltersTracking) => ({
  ...filters,
  ...{ days: filters.days ? Array.from(filters.days) : undefined },
})
```

Would it be possible to add support for Sets as well in the `jsonMap`?
