### ISSUE TITLE
Does calling createClient multiple times instantiate Segment multiple times as well?

### ISSUE THREAD

**Issue by MorenoMdz** [segmentio/analytics-react-native#537]
## Summary

When we are calling `createClient` outside of a hook, following the example in the documentation, is it instantiating the library multiple times, as we already have one in the wrapper at App.js that is being used in the hooks?

Or is it a case where the JS thread is able to cache it and use the same instance?

Here is how I am initializing Segment atm:

```js
/**
 * Initialize the whole analytics tracking here
 */
export function getAnalytics(): SegmentClient | undefined {
  try {
    const isLocal = Env.ENV_NAME === 'local'
    console.log(!isProd && '...Initializing Segment in development mode...')

    /**
     * If running local use a null write key, Segment calls will be sent but be ignored by Segment
     * This is a workaround recommended by the Segment team until a native disable flag is re-added
     * https://github.com/segmentio/analytics-react-native/issues/483#issuecomment-1106663656
     */
    if (isLocal) {
      console.log('...Skipping Segment in local mode')
    }
    const writeKey = isLocal
      ? ''
      : Platform.OS === 'ios'
      ? keyset.iosWriteKey
      : keyset.androidWriteKey
    const segmentClient = createClient({
      writeKey,
      trackAppLifecycleEvents: true,
      collectDeviceId: true,
      debug: true,
      trackDeepLinks: true,
    })
    return segmentClient
  } catch (error) {
    console.log('analyticsInit', error)
    Sentry.Native.captureException(error)
  }
}
```

And this is how it gets used:
App.tsx
```js
  const segmentClient = getAnalytics()

  return (
    <AnalyticsProvider client={segmentClient}>
        ...
    </AnalyticsProvider>
  )
}
```

Non React files:
```js
getAnalytics()?.track(event, indexed(trackedData))
```

## Proposed Solution

A bit more information how the create client method handles the instances of the library will help a lot.

**Comment by oscb** [comment]
I think we could specify good practices on the docs or common scenarios of how to create it, the most common scenario is the one [in the example app](https://github.com/segmentio/analytics-react-native/blob/a70a9e6925b34372f3684aa1ecbfa19d7b6f6b3f/example/src/App.tsx#L36) where it gets created in the global scope that way you can reference it anywhere. You could potentially export it as well and use it in other files.

The idea is that you can have multiple clients with different keys in your app and instantiate them at any point depending on your flow.

For your scenario it seems like `getAnalytics()` should be a singleton, something like this:
```ts

let client: SegmentClient | undefined;

export const getAnalytics = () => {
	if (client != undefined) return client; 
    try {
      // ...
      client = createClient(...);
    catch {
     // ...
    }
};
```

Then in another file you can import and call `getAnalytics()?` and it will always reuse the same instance of the client
