### ISSUE TITLE
[feat] storePersistor option for createClient to pass through for createStore calls

### ISSUE THREAD

**Issue by 509dave16** [segmentio/analytics-react-native#542]
## Summary

`@segment/sovran-react-native`'s export [createStore](https://github.com/segmentio/sovran-react-native/blob/fc7b4f01ac6f0d3da889718c3fa9ab49383119e6/src/store.ts#L100-L101) has a `persist` option that allows for you to provide a `Persistor`. This is great for being able to leverage a faster storage library like MMKV.

However the `createClient` export of `@segment/analytics-react-native` does not pass through any `config` options to it's `SovranStorage` class which makes `createStore` function calls. Except for `writeKey` that is which maps to `storeId` in the `SovranStorage` class.

## Proposed Solution

1. `createClient` export's `Config` argument should include an option for `storePersistor`. Which will match the `Persistor` interface of `@segment/sovran-react-native`
2. `SovranStorage` class needs either a second argument for `storePersistor` or it needs to have it own `Config` interface for the argument to support a `storeId` and `storePersistor` options.
3. All `createStore` calls in `SovranStorage` class must pass `persistor` property in the `persist` object option.

**Comment by thianphat** [comment]
Hi @509dave16 , I was curious if you could provide an example of making this work with MMKV. I've tried adding the MMKV storage to storePersistor:

`storePersistor: storage`

Where `storage` is equal to `new MMKV()`

However, it's not working and of course, I am getting type errors where the methods don't align. How did you go about integrating this? Really appreciate it.
