### ISSUE TITLE
Build error when running in released NPM package code

### ISSUE THREAD

**Issue by 509dave16** [segmentio/analytics-react-native#544]
@oscb, need a little help  :sweat_smile:

- `analytics-react-native` version: 2.1.12
- Integrations versions (if used): N/A
- React Native version: N/A
- iOS or Android or both? N/A

**Steps to reproduce**
1. Use Node Version 16.5: `nvm use lts/gallium`
2. Install Bob Globally: `npm i -g react-native-builder-bob`
3. Enter analytics-react-native working directory: `cd node_modules/@segment/analytics-react-native`
4. Execute build script: `npm run build`

**Expected behavior**
New build for each module target should be present in `lib` folder

**Actual behavior**
" 'defaults' is not a valid target" is the error I get. Found one [react-native-builder-bob issue](https://github.com/callstack/react-native-builder-bob/issues/102) regarding this error. `analytics-react-native` does not have a `browserlist` set. So even though the solution was to remove it, I added the following to the `package.json` to see if it would address the "defaults" target error:
```
  "browserslist": [
    "last 1 version",
    "> 1%",
    "IE 10"
  ]
```
Didn't end up helping. Wondering if running `build` script in the published package code was never going to work because it does not contain all the scripts and configs present in the source code(i.e. Github repo).

Below is the full error output:
```
Error: [BABEL] /Users/david/Projects/theseus/node_modules/@segment/analytics-react-native/src/storage/index.ts: @babel/helper-compilation-targets: 'defaults' is not a valid target
- Did you mean 'safari'? (While processing: "/Users/david/Projects/theseus/node_modules/@segment/analytics-react-native/node_modules/@babel/preset-env/lib/index.js")
    at validateTargetNames (/Users/david/Projects/theseus/node_modules/@segment/analytics-react-native/node_modules/@babel/helper-compilation-targets/lib/index.js:71:13)
    at getTargets (/Users/david/Projects/theseus/node_modules/@segment/analytics-react-native/node_modules/@babel/helper-compilation-targets/lib/index.js:188:17)
    at getLocalTargets (/Users/david/Projects/theseus/node_modules/@segment/analytics-react-native/node_modules/@babel/preset-env/lib/index.js:227:48)
    at /Users/david/Projects/theseus/node_modules/@segment/analytics-react-native/node_modules/@babel/preset-env/lib/index.js:288:15
    at /Users/david/Projects/theseus/node_modules/@segment/analytics-react-native/node_modules/@babel/helper-plugin-utils/lib/index.js:23:12
    at async (/Users/david/Projects/theseus/node_modules/@segment/analytics-react-native/node_modules/@babel/core/lib/gensync-utils/async.js:44:33)
    at async (/Users/david/Projects/theseus/node_modules/@segment/analytics-react-native/node_modules/gensync/index.js:186:15)
    at /Users/david/Projects/theseus/node_modules/@segment/analytics-react-native/node_modules/gensync/index.js:216:13
    at Generator.next (<anonymous>)
    at /Users/david/Projects/theseus/node_modules/@segment/analytics-react-native/node_modules/@babel/core/lib/config/full.js:229:21
```

**Comment by oscb** [comment]
Uhm, This is unexpected. The `build` script contains everything, actually the whole repo contains everything we use for developing this library so it should just work.

I don't use `nvm` myself anymore cause it has always given me issues with RN build. I'm using node v18.0.0 right now, maybe that could be related?

**Comment by 509dave16** [comment]
@oscb I'll try a later version of Node. Though as you can probably tell from the following in the node_module not everything is there 😅 :
![Screen Shot 2022-05-17 at 10 53 22 AM](https://user-images.githubusercontent.com/2925882/168892555-bb63ffae-6091-4176-ad9e-1040edb01fc2.png)

We're going to contribute most likely to anyways. So a fork is probably better in this case.

**Comment by oscb** [comment]
Ooh, I see what you mean. You tried to run the build command from the actual node module. 

Yeah, the published package doesn't have everything in it to build it again due to how react-native-bob-builder outputs the stuff. 

It's a better idea to make a fork of this repo to build the package again.
