### ISSUE TITLE
React Native Firebase configuration. setup() does not exit

### ISSUE THREAD

**Issue by chloe722** [segmentio/analytics-react-native#545]
Hi, im trying to configure `@segment/analytics-react-native-firebase` by following [Setting Up Firebase with Analytics-React-Native](https://segment.com/docs/connections/destinations/catalog/firebase/#setting-up-firebase-with-analytics-react-native)
For some reason, when im trying to call `analytics.setup()`, the function isn't available. 

```
import analytics from '@segment/analytics-react-native';
analytics.setup();

```

<img width="300" alt="Screenshot 2022-05-18 at 17 56 12" src="https://user-images.githubusercontent.com/21269074/169087946-176a9b53-74cd-46c7-a0c4-fb7d5b7c7d2c.png">

I currently have initialized client instance by calling `createClient()`
```
  segmentClient = createClient({
    writeKey: SEGMENT_WRITE_KEY,
    trackAppLifecycleEvents: true,
  });
```

- `analytics-react-native` version: 2.1.11
- React Native version: 0.66

**Comment by oscb** [comment]
Hi @chloe722 

The docs you mention seem to be out of date. In particular you don't need to call `setup` on the client anymore.
I recommend taking a look at the readme of the plugin here in github, those are more constantly updated: https://github.com/segmentio/analytics-react-native/tree/master/packages/plugins/plugin-firebase

```ts
import { createClient } from '@segment/analytics-react-native';

import { FirebasePlugin } from '@segment/analytics-react-native-plugin-firebase';

const segmentClient = createClient({
  writeKey: 'SEGMENT_KEY'
});

segmentClient.add({ plugin: new FirebasePlugin() });
```

Let us know if you have any issues
