### ISSUE TITLE
amplitude_attribution_ids is being sent as null for Android

### ISSUE THREAD

**Issue by TrekSoft** [segmentio/analytics-react-native#561]
The property `amplitude_attribution_ids` is being sent as null only from Android. 

- `analytics-react-native` version: 2.1.9
- Integrations versions (if used): 0.2.1
- React Native version: 0.66.4
- iOS or Android or both?: Just Android

**Steps to reproduce**
AppsFlyer is setup with the plugin and Amplitude is setup with the plugin.

**Expected behavior**

Both AppsFlyer events and Segment events send Amplitude a payload that includes a value for `amplitude_attribution_ids`

**Actual behavior**

The `amplitude_attribution_ids` field is being populated for the AppsFlyer events sent to Amplitude but not the Segment events. This leads to the Segment events not being attributed to the AppsFlyer install event.

**Comment by TrekSoft** [comment]
Also this started happening only after we upgraded to v2.0 from v1.5

**Comment by alanjcharles** [comment]
@TrekSoft you should be able to add this `AdvertisingId` plugin to start collecting the Android specific attribution ID for Amplitude. Let me know if you run into any issues. 

https://www.npmjs.com/package/@segment/analytics-react-native-plugin-advertising-id

**Comment by TrekSoft** [comment]
Amazing!! Thank you so much @alanjcharles !!
