### ISSUE TITLE
Play store warning about Advertising ID changes unsupported by Segment SDK

### ISSUE THREAD

**Issue by MorenoMdz** [segmentio/analytics-react-native#565]
When we added our latest build in Play store today we faced this warning:

>Your app ourApp version code 63 includes SDK com.segment.analytics.android:analytics, 4.9.4 or an SDK that one of your libraries depends on, which collects personal or sensitive data that includes but may not be limited to Advertising ID, Android ID identifiers. Persistent device identifiers may not be linked to other personal and sensitive user data or resettable device identifiers as described in the User Data policy.
Starting from August 9, 2022 midnight (UTC), new app releases containing the SDK version(s) that do not comply with the User Data policy will be blocked from release. You may consider moving to another SDK; removing this SDK; or if available from your SDK provider, upgrading to a policy-compliant version of this SDK that does not include the violating code.
According to the information provided by your SDK provider, you may consider upgrading to 4.10.1. Please consult the SDK provider for further information.

Is that a known thing and would updating the SDK to the latest version fix it?

- `analytics-react-native` version: 2.1.12
- Integrations versions (if used):
- React Native version:  0.68.2
- iOS or Android or both? Android

**Comment by 509dave16** [comment]
@MorenoMdz Analytics React Native `2.0.0` and above don't depend on Analytics Android and Analytics iOS anymore. Are you sure you didn't receive that warning for build using Analytics React Native version `1.5.x`?

**Comment by 509dave16** [comment]
Previously for Analytics Android to be compliant they removed the access of `Settings.Secure.ANDROID_ID` and `Build.SERIAL` in the following commit : [get rid of android id and serial number](https://github.com/segmentio/analytics-android/commit/b00c51c131a818773865e74ff3f230848f2f273a), which addressed this common violation: `Your app collects or links persistent device identifiers (e.g., IMEI, IMSI, SIM Serial #, etc.)`

And in Analytics React Native 2.x.x, they are directly accessing `Settings.Secure.ANDROID_ID` : [AnalyticsReactNativeModule.kt -> getUniqueId](https://github.com/segmentio/analytics-react-native/blob/40be1abbcff26871c89f0029250b3d4da7c37249/packages/core/android/src/main/java/com/segmentanalyticsreactnative/AnalyticsReactNativeModule.kt#L57-L63) .

Which is what theoretically resulted in violations for Analytics Android previously.

**Comment by MorenoMdz** [comment]
> 

It is a very weird bug because the version listed in the warning is a dozen versions behind the one we have, I will close this now as I suspect this error is outdated and shouldn't be affecting us in the current version.
