### ISSUE TITLE
Device ID Collection Violates Google Play's User Data Policy

### ISSUE THREAD

**Issue by 509dave16** [segmentio/analytics-react-native#566]
## Summary
Previously for Analytics Android to be compliant the access of `Settings.Secure.ANDROID_ID` and `Build.SERIAL` was removed in the following commit : [get rid of android id and serial number](https://github.com/segmentio/analytics-android/commit/b00c51c131a818773865e74ff3f230848f2f273a). Which addressed this common violation: `Your app collects or links persistent device identifiers (e.g., IMEI, IMSI, SIM Serial #, etc.)`

However in Analytics React Native 2.x.x, `Settings.Secure.ANDROID_ID` is being directly accessed : [AnalyticsReactNativeModule.kt -> getUniqueId](https://github.com/segmentio/analytics-react-native/blob/40be1abbcff26871c89f0029250b3d4da7c37249/packages/core/android/src/main/java/com/segmentanalyticsreactnative/AnalyticsReactNativeModule.kt#L57-L63) .

Which is what theoretically resulted in violations for Analytics Android previously.

This access of `Settings.Secure.ANDROID_ID` that violates the Google Play User Data policy needs to be addressed.

## Details
- `analytics-react-native` version: 2.2.1
- Integrations versions (if used): N/A
- React Native version: 0.68.0
- iOS or Android or both? Android

## Steps to reproduce
- Install any `2.x.x` version fof `@segment/analytics-react-native`.
- Submit Android build to Google Play Store.

### Expected behavior
No User Data policy violations.

### Actual behavior(p.s. theoretically)
We have yet to submit our build of the new app experience containing the upgrade to  `2.2.1` for Analytics React Native. But we have already received violation warnings from Google Play on a build of our app for the old experience that's using Analytics Android `4.10.0`. So we are anticipating the same warning when we upgrade from Analytics React Native `1.5.2` to `2.2.1` in a build for the new experience of our app:
<img width="849" alt="Screen Shot 2022-06-09 at 5 04 47 PM" src="https://user-images.githubusercontent.com/2925882/172964623-fcb0d489-411f-4b9d-801d-78ab5dab7575.png">

## References
- [Google Play User Data Policy](https://support.google.com/googleplay/android-developer/answer/10144311?hl=en)
![Screen Shot 2022-06-09 at 10 58 44 AM](https://user-images.githubusercontent.com/2925882/172959469-e7ceffb1-7411-460d-8e7a-9de416c8eb56.png)

**Comment by rborn** [comment]
I can confirm 🙏

**Comment by CrisPRuz** [comment]
+1

**Comment by kuznetsov-from-wonderland** [comment]
We have `deviceID: null` on Android when identify method is called.

**Comment by 509dave16** [comment]
@kuznetsov-from-wonderland Did you choose to pass `false` for `collectDeviceId` client option?

**Comment by 509dave16** [comment]
@rborn Thank you so much for providing confirmation on Analytics React Native 2.0 triggering the violation! Can you by chance share a screenshot of the violation? Thanks!

**Comment by oscb** [comment]
Thanks for the report! we changed the code to comply to Google's User Data policy now in PR: #567 it will be out on the next release of core

**Comment by prajeesh-mp** [comment]
> Thanks for the report! we changed the code to comply to Google's User Data policy now in PR: #567 it will be out on the next release of core

Can we expect an immediate release ?

**Comment by rborn** [comment]
@509dave16 I'm still on 1.5.0, will update the module and let you know :)
Thank you.

**Comment by 509dave16** [comment]
@oscb Awesome! Will be testing out the latest release. Will let you know if anything comes up.

**Comment by andrewkvavlewhite** [comment]
I'm still getting the error when trying to submit with v2.2.2

**Comment by 509dave16** [comment]
@andrewkvavlewhite Can you provide screenshot/copy of the violation warning when you tried submitting your build on Google Play?

**Comment by andrewkvavlewhite** [comment]
@509dave16 Hey I ended up figuring it out, thanks.

For everyone else who ran into this issue, make sure you run ./gradlew clean and follow [these steps from google](https://support.google.com/googleplay/android-developer/answer/2477981#resubmit). Otherwise, the error will persist.

**Comment by NoRoboto** [comment]
> @509dave16 Hey I ended up figuring it out, thanks.
> 
> For everyone else who ran into this issue, make sure you run ./gradlew clean and follow [these steps from google](https://support.google.com/googleplay/android-developer/answer/2477981#resubmit). Otherwise, the error will persist.
> 
> And technically any version of this library v1.5.1 and above should work

Hi!, this has been extended for version `com.segment.analytics.android:analytics:4.9.3`

![image](https://user-images.githubusercontent.com/8453089/176800832-8c5d95c0-92ec-48ee-858d-52a711a47956.png)

**Comment by DominicTobias** [comment]
Did anyone find a solution to this? In summary deviceID can look like it could be turned on due to providing a `collectDeviceId` so Google scanning gives a false positive? Why is this an option if it causes apps using segment to get rejected by Google?
