### ISSUE TITLE
Version 2.2.2 potentially causing ANRs

### ISSUE THREAD

**Issue by krizzu** [segmentio/analytics-react-native#571]
Heya,
This is something that I did not happen to experience (hopefully) yet, but looking at version 2.2.2 [fix for getDeviceId on Android](https://github.com/segmentio/analytics-react-native/commit/f2616aaf2fbfd76577368cf1dd3ab147d72f7c27), I can see that it's the same implementation from [segment-android in version 4.10.1](https://github.com/segmentio/analytics-android/pull/781/files#diff-b2e3bd6518e72976b2e0560084e95a5d256793ce35ec400085b3e6c0b02b7e7fR319), which is now patched [due to ANRs coming from DRM api.](https://github.com/segmentio/analytics-android/releases/tag/4.10.4)

Should we have the same patch in this repo?

- `analytics-react-native` version: 2.2.2
- React Native version: 0.67.4
- iOS or Android or both? Android

**Comment by oscb** [comment]
Thanks for reporting this! Glad to see our users paying attention!

I do not think the same bug will happen in RN as the NativeModules lifecycle is different from the way Android initialized/set the DeviceId which caused ANRs to be blocking. That said, we will keep an eye on this in case it starts showing up. 

I am also refactoring some of the logic in RN to match the asynchronous nature of setting the values in the device context that we do in swift/kotlin. It is mostly for performance but it will also add yet another layer to prevent ANRs from affecting RN in case future version of RN change the way NativeModules work.

**Comment by krizzu** [comment]
Digging through some old issues from ExoPlayer, I [found this issue where init of DRM caused the ANR](https://github.com/google/ExoPlayer/issues/6730#issuecomment-565376352). If that's true and if creating an instance might cause ANR, then I'd assume that NativeModules are affected, as they're single threaded.  

> I am also refactoring some of the logic in RN to match the asynchronous nature of setting the values in the device context that we do in swift/kotlin. It is mostly for performance but it will also add yet another layer to prevent ANRs from affecting RN in case future version of RN change the way NativeModules work.

Great, looking forward to see that
