### ISSUE TITLE
V2+ and Mixpanel plugin

### ISSUE THREAD

**Issue by adrien-may** [segmentio/analytics-react-native#573]
## Summary

Is mixpanel plugin supported on the latest version ?

In https://segment.com/docs/connections/sources/catalog/libraries/mobile/react-native/#plugin-architecture, Mixpanel is not listed as a valid destination since v2.

I saw a merged PR #498 stating the opposite.

## Proposed solution

Do we need to update the doc ? Or is it not completely ready yet ?

**Comment by alanjcharles** [comment]
@adrien-may  Mixpanel is available for V2: 
[Github]( https://github.com/segmentio/analytics-react-native/tree/master/packages/plugins/plugin-mixpanel)
[NPM](https://www.npmjs.com/package/@segment/analytics-react-native-plugin-mixpanel)

Let me know if you run into any issues
