### ISSUE TITLE
Latest @segment/analytics-react-native-appsflyer not compatible with @segment/analytics-react-native 2.2.2

### ISSUE THREAD

**Issue by LydGol90** [segmentio/analytics-react-native#575]
- `analytics-react-native` version: 2.2.2
- Integrations versions (if used): 1.5.3
- React Native version:
- iOS or Android or both? iOS

Install latest `@segment/analytics-react-native` (2.2.2) and latest `@segment/analytics-react-native-appsflyer` (1.5.3)
Run pod install

There is an error as `@segment/analytics-react-native-appsflyer` is still looking for the old dependency name `RNAnalytics`

<img width="691" alt="Screenshot 2022-06-20 at 14 43 37" src="https://user-images.githubusercontent.com/29592293/174615048-8469afba-0cd1-4572-aa14-a1b61523e229.png">

This can be fixed by changing dependency name in podspec to `segment-analytics-react-native`

However you then get this error when building as clearly that file no longer exists, but I'm not sure what I should be importing instead. Is there a patch possible or is it not possible to use the appsflyer integration with the latest segment sdk currently?

<img width="807" alt="Screenshot 2022-06-20 at 14 50 21" src="https://user-images.githubusercontent.com/29592293/174616354-160e9bed-2308-4d5f-96ea-1ebca558b05a.png">

Many thanks,
Lydia

**Comment by shalu-simformsolutions** [comment]
@LydGol90  can you please share the solution for this issue?
