### ISSUE TITLE
Appsflyer plugin - JSON Parse error: Unexpected identifier "undefined"

### ISSUE THREAD

**Issue by wmacall** [segmentio/analytics-react-native#577]
- `analytics-react-native` version: 2.2.1
- Integrations versions (if used): `@segment/analytics-react-native-plugin-appsflyer` version: `0.3.2`
- React Native version: 0.63.4
- iOS or Android or both? Just Android

**Steps to reproduce**
Sometimes the value from `onInstallConversionData` its undefined and the `@segment/analytics-react-native-plugin-appsflyer` library crash

**Expected behavior**
The plugin works normally 

**Actual behavior**
The app crash on Android, because the value from `onInstallConversionData` probably is undefined
```
SyntaxError - JSON Parse error: Unexpected identifier "undefined"{
[native code]parse                 
node_modules/@segment/analytics-react-native-plugin-appsflyer/src/AppsflyerPlugin.tsxappsFlyer.onInstallConversionData
```

**Comment by Asgaroth** [comment]
This was supposed to be fixed in https://github.com/segmentio/analytics-react-native/pull/556

And the code is there, but I think there may be an issue with package publishing because the version that gets installed does not have the fix.

**Comment by oscb** [comment]
I'll trigger a release. That should have been released already.

**Comment by oscb** [comment]
It is now released: https://github.com/segmentio/analytics-react-native/releases/tag/%40segment%2Fanalytics-react-native-plugin-appsflyer-v0.3.3 

Let us know if you bump into any issues.
