### ISSUE TITLE
analytics-react-native-clevertap v1.5.3 is giving build error on Android studio Chipmunk

### ISSUE THREAD

**Issue by piyush-kukadiya** [segmentio/analytics-react-native#583]
`analytics-react-native-clevertap` **v1.5.3** is giving build error on Android studio Chipmunk.

`e: /Users/piyush.kukadiya/projects-clevertap/clevertap-react-native/Example/node_modules/@segment/analytics-react-native-clevertap/android/src/main/java/com/segment/analytics/reactnative/integration/clevertap/IntegrationModule.kt: (40, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.13.`

- `analytics-react-native` version: 1.5.0
- Integrations versions (if used): `analytics-react-native-clevertap` **v1.5.3**
- React Native version: 0.64.1
- iOS or Android or both? Android

Changing  `classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.21'` to v1.7.0 fixes this. @alanjcharles Can we have this fix in plugin. 
Thanks!

**Comment by alanjcharles** [comment]
removing duplicate- will address #582
