### ISSUE TITLE
[!] No podspec found for `RNAnalytics` in `../node_modules/@segment/analytics-react-native`

### ISSUE THREAD

**Issue by beqramo** [segmentio/analytics-react-native#585]
- `analytics-react-native` version: ---- 2.3.1
- Integrations versions (if used): 
- React Native version: ---- 0.68.2
- iOS or Android or both? --- both

```json
    "@segment/analytics-react-native": "^2.3.1",
    "@segment/analytics-react-native-mixpanel": "^1.5.3",
    "@segment/sovran-react-native": "^0.2.8",
   "react-native": "0.68.2",
```
**Steps to reproduce**

I'm trying to update package to v2 but it throws error, 

I ran this with pod install:

`yarn add @segment/analytics-react-native @segment/sovran-react-native @react-native-async-storage/async-storage 
`

**Expected behavior**

**Actual behavior**

**Comment by alanjcharles** [comment]
@beqramo it looks like you are using the mixpanel integration for `Analytics React Native 1.x`. Can you try this and let me know if you're still running into issues? https://www.npmjs.com/package/@segment/analytics-react-native-mixpanel

**Comment by beqramo** [comment]
Hi, thanks, I can approve that it worked.
