### ISSUE TITLE
Firebase plugin documentation needs additional information

### ISSUE THREAD

**Issue by jennifersalas** [segmentio/analytics-react-native#587]
## Summary

The documentation for firebase plugin installation is not sufficient to get it up and running.

## Proposed Solution
The firebase plugin README should contain additional instructions for installing. During implementation, we needed to follow directions from console firebase installation instructions for iOS/Android, which is not made clear in any of segment's documentation.

The firebase plugin documentation at https://segment.com/docs/connections/destinations/catalog/firebase/ is also out of date with the package.

**Comment by alanjcharles** [comment]
Hi @jennifersalas we do link to the Firebase packages in the installation section of the readme which cover the steps necessary to connect to Firebase (See React Native Firebase and React Native Firebase Analytics for more details of Firebase package) 
![image](https://user-images.githubusercontent.com/50601149/176269053-7dfffe08-0725-4d62-8254-f948b6e090b0.png)

However, totally take your point about the public documentation as it only covers Analytics React Native < 2.x implementations. I have submitted a request to our documentation team to make that more clear. Thanks for letting us know, please let me know if you run into any other issues.
