### ISSUE TITLE
SegmentClient type is not included in top level module exports

### ISSUE THREAD

**Issue by adaddeo** [segmentio/analytics-react-native#593]
- `analytics-react-native` version: 2.32
- Integrations versions (if used): n/a
- React Native version: 0.65.1
- iOS or Android or both? both

The `SegmentClient` type is not included in the top-level module export. We hold on to the return value of this type from `createClient` and use to make track calls as well access readonly state (such as user's Segment client assigned anonymous ID). 

Ideally we could write functions that take in the client and perform operations using it, however, since there isn't a type exported for it this isn't feasible to do in a robust manner. Request to include this in the top-level module exports.

**Comment by oscb** [comment]
This is fixed in 2.4.0
