### ISSUE TITLE
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.40 and higher. 

### ISSUE THREAD

**Issue by filipgerat** [segmentio/analytics-react-native#597]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@segment/analytics-react-native-firebase@1.5.3` for the project I'm working on.

The problem was with the kotlin versions. Such a classic problem, you can check this for reference https://github.com/segmentio/analytics-react-native/issues/90 . I've used the build.grade configuration for kotlin from @segment/analytics-react-native . (I have not yet checked whether the events arrive, but I've successfully built the app)

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@segment/analytics-react-native-firebase/android/build.gradle b/node_modules/@segment/analytics-react-native-firebase/android/build.gradle
index 0b4a6c8..694e7f8 100644
--- a/node_modules/@segment/analytics-react-native-firebase/android/build.gradle
+++ b/node_modules/@segment/analytics-react-native-firebase/android/build.gradle
@@ -2,13 +2,15 @@ apply plugin: 'com.android.library'
 apply plugin: 'kotlin-android'
 
 buildscript {
+    ext.defaultKotlinVersion = '1.4.0'
+    
     repositories {
         google()
         mavenCentral()
     }
     dependencies {
         classpath 'com.android.tools.build:gradle:3.1.4'
-        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.21'
+        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${rootProject.ext.has("kotlinVersion") ? rootProject.ext.get("kotlinVersion") : defaultKotlinVersion}"
     }
 }
 
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by alanjcharles** [comment]
Hi @filipgerat Thank you for bringing this to our attention and for providing a detailed fix! We currently do not have the bandwidth or enough customer requests to prioritize fixing anything > 2.x in the Analytics React Native library or its associated destinations. With that said, we have logged your request and will let you know if/when anything changes! In the meantime, please feel free to [update to the new Analytics React Native library](https://github.com/segmentio/analytics-react-native/blob/master/MIGRATION_GUIDE.md) and don't hesitate to reach out with any questions. Thanks again!
