### ISSUE TITLE
Unable to find a specification for `RNAnalytics` depended upon by `RNAnalyticsIntegration-Firebase`

### ISSUE THREAD

**Issue by sharjeelhaider** [segmentio/analytics-react-native#598]
After upgrading to segment version 2 I am unable to use `analytics-react-native-firebase`.  When i run pod install for  iOS i get an error "Unable to find a specification for `RNAnalytics` depended upon by `RNAnalyticsIntegration-Firebase` "
Also buidling android version gives an error "Execution failed for task ':segment_analytics-react-native-firebase:compileDebugKotlin"

- `analytics-react-native` version: 2.3.1
- `analytics-react-native-firebase` version: 1.5.3
- React Native version: 0.66.3
- iOS or Android or both? both

**Steps to reproduce**
1: Install segment  `analytics-react-native` version: 2.3.1
2: Install `analytics-react-native-firebase` version: 1.5.3
3: run pod install

**Expected behavior**
Install pod command should run successfully and android should build successfully 

**Actual behavior**
- Pod install command fail with error "Unable to find a specification for `RNAnalytics` depended upon by `RNAnalyticsIntegration-Firebase` "
- Buidling android also gives error "Execution failed for task ':segment_analytics-react-native-firebase:compileDebugKotlin'."

**Comment by JJ810** [comment]
@sharjeelhaider  I think you should use `@segment/analytics-react-native-plugin-firebase` library for firebase plugin in v2 - https://github.com/segmentio/analytics-react-native/blob/master/MIGRATION_GUIDE.md#plugins

**Comment by oscb** [comment]
Yes, please use the `@segment/analytics-react-native-plugin-firebase` plugin for v2. We changed the namings for the new version of the library.

Thanks @JJ810 for the reply here!
