### ISSUE TITLE
Intercom Integration

### ISSUE THREAD

**Issue by oshimayoan** [segmentio/analytics-react-native#60]
Hi, I'd like to do an integration with Intercom on react-native using `@segment/analytics-react-native-intercom` but it seems that package lacks documentation about how to do it.

Could someone help me figure out this, please?

Thanks in advance.

**Comment by paolitaclo** [comment]
same happen with AppsFyler :(

**Comment by hodayaGruzm** [comment]
hi, why this bug is closed?
what the solution for it?
