### ISSUE TITLE
Documentation Refers to useNativeConfiguration 

### ISSUE THREAD

**Issue by jayfunk** [segmentio/analytics-react-native#612]
I am in the process of upgrading our install of analytics-react-native analytics from 1.5.3. In our current version we configure Segment natively then in our javascript we used `useNativeConfiguration`. I found in the documentation that this API call is still an option if we choose to configure Segment on the native side. While going through the migration to V2 it seems that the `useNativeConfiguration` method does not exist on the Segment client. Is native configuration of the analytics API still possible with V2?

https://segment.com/docs/connections/sources/catalog/libraries/mobile/react-native/react-faqs/#can-i-also-use-the-native-analytics-api

**Comment by oscb** [comment]
Currently it is not available. The v2 client is completely running on RN runtime now so we don't expose the same objects in the native side as before.

May I ask what is your scenario here? We're exploring adding some methods to expose some of the client methods in the native side for hybrid apps but would like to more about use cases.

**Comment by jayfunk** [comment]
Looking at our native configuration it appears the only items that are not present in the React-Native implementation is:
```
```

**Comment by jayfunk** [comment]
Since native configuration is no longer possible with the V2 implementation what is the recommended approach to bridge the gap between the RN implementation and the need for native SDK features? If I were to keep our native implementation and reworked our RN implementation would I still be able to identify/attribute the two analytics instances as a single device?

**Comment by carl0shd** [comment]
Would be great if segment support `useNativeConfiguration` in v2. same as @jayfunk, we use in our application the native methods `registeredForRemoteNotificationsWithDeviceToken`, `receivedRemoteNotification`, `registerForRemoteNotifications` and the actual segment 1.5.0 version its not longer compatible with newer RN versions due to this error https://github.com/segmentio/analytics-react-native/issues/609

**Comment by oscb** [comment]
@adkenyon Hey, we just added this feature which might help your scenario: [Native AnonymousId](https://github.com/segmentio/analytics-react-native#native-anonymousid)
Sadly it's not full support for `useNativeConfiguration` as that would require some heavy refactoring, but it does let you send the anonymous Id from the native side.
Hope this helps in the meantime.
