### ISSUE TITLE
Promise.allSettled is not a function. 

### ISSUE THREAD

**Issue by alejoatg** [segmentio/analytics-react-native#617]
Error: Unhandled promise rejection [TypeError: Promise.allSettled is not a function. (In 'Promise.allSettled(promises)', 'Promise.allSettled' is undefined)]

Error when updating to version @segment/analytics-react-native v2.4.0

"react-native": "0.68.2"
"expo": "~45.0.0"

**Comment by serhey-dev** [comment]
Same happens for me. When updating from version "v2.2.0" to "v2.4.0" - this warning appears.

"expo": "^45.0.4"
"react-native": "0.68.2"

I also tried to add: "promise.allsettled": "^1.0.5" to my project. It didn't help.

**Comment by oscb** [comment]
Weird. Might be an expo specific thing?

Can you try adding this code in your app, you'll also need to install `promise.allsettled`, although analytics already has a dependency on it:

```ts
import allSettled from 'promise.allsettled';

allSettled.shim();
```

That code should be executed already by analytics but not sure why would it not pick it up.
Not a long term solution, but let's give it a try to pinpoint the issue.

**Comment by alejoatg** [comment]
resolved in https://github.com/segmentio/analytics-react-native/releases/tag/%40segment%2Fanalytics-react-native-v2.5.1
