### ISSUE TITLE
The device_id value changes with each request to Segment within the same session

### ISSUE THREAD

**Issue by jedashford** [segmentio/analytics-react-native#623]
On Android, every batch request of events that fire to segment have different device_id's. We use braze in device mode with segment and events going to braze are consistent with a specific device_id, but it doesn't match the device_id segment sends, with the addition that every batch of requests sent out from our application have different device_ids. 

Our iOS and Web applications have consistent device_ids across segment and braze with the device_id staying consistent through multiple batch requests and app resets.

We've tried an emulator and a physical device. 

Here is one batched request in a session
![image](https://user-images.githubusercontent.com/4111055/181643745-2c3f24ae-78c0-4859-9aaf-6feae6b235a9.png)

Here is the next batch request in the same session with the device_id being changed. This will continue changing with each batched request.
![image](https://user-images.githubusercontent.com/4111055/181643777-f5bb105e-0c7f-4d21-880d-90716053ef4c.png)

- `analytics-react-native` version: 
    "@segment/analytics-react-native": "2.3.2",
    "@segment/sovran-react-native": "0.2.8",
- Integrations versions (if used):
    "react-native-appboy-sdk": "1.36.0",
    "@segment/analytics-react-native-plugin-braze": "0.3.0",
- React Native version: 
0.69.1
- iOS or Android or both?
Issue is only with Android. 

**Steps to reproduce**
Install the SDKs, open the app, inspect the events fired by segment

**Expected behavior**
device_id stays consistently the same and matches any plugin's device_id

**Actual behavior**
device_id constantly changes with each request to segment

**Comment by jedashford** [comment]
I've submitted a ticket with Segment support. https://segment.zendesk.com/hc/en-us/requests/480173

**Comment by alanjcharles** [comment]
fixed in [`2.6.0`](https://github.com/segmentio/analytics-react-native/releases/tag/%40segment%2Fanalytics-react-native-v2.6.0https://github.com/segmentio/analytics-react-native/releases/tag/%40segment%2Fanalytics-react-native-v2.6.0)
