### ISSUE TITLE
migration guide missing pitfalls & other documentation

### ISSUE THREAD

**Issue by schmod** [segmentio/analytics-react-native#625]
The 2.x migration guide in this repository does not match [the one on the Segment Website](https://segment.com/docs/connections/sources/catalog/libraries/mobile/react-native/migration/).  

Specifically, the docs in this repo do not note that upgrading will cause `Application Installed` to double-fire for existing users (which is a fairly major pitfall for anybody who's doing any analysis based around that event!) 

Can you please update the guide in this repository to note this pitfall (as well as any other tracking changes that users might notice as a result of the upgrade)?

**Comment by alanjcharles** [comment]
#624
