### ISSUE TITLE
How to setup verbose logging?

### ISSUE THREAD

**Issue by TrekSoft** [segmentio/analytics-react-native#628]
Is there a way to configure this to enable verbose logging?

**Comment by jedashford** [comment]
adding ` debug: true` to the createClient worked for us.

`    Analytics.client = createClient({
      writeKey: SEGMENT_WRITE_KEY ?? '',
      trackAppLifecycleEvents: true,
      trackDeepLinks: true,
      debug: true,
      collectDeviceId: true,
      flushInterval: 10,
    })`

**Comment by alanjcharles** [comment]
@TrekSoft the suggestion @jedashford mentioned is the most verbose logging we have available.
