### ISSUE TITLE
Missing documentation for @segment/analytics-react-native-plugin-advertising-id

### ISSUE THREAD

**Issue by jedashford** [segmentio/analytics-react-native#634]
There is zero documentation about this plugin, even searching google is missing any reference to this plugin. I only found it through an issue ticket and then searching source code for plugins. This is such a critical piece that prevents partners like Branch from working correctly without this ID. Too many hours spent on trying to find out why segment events don't show in branch.io. All basically due to all documentation missing related to getting this advertising ID.

PR to fix to add it as a plugin in the README documentation: https://github.com/segmentio/analytics-react-native/pull/633, but this is still missing from any page at segment.com so someone will need to go tip off future explorers of clear documentation at Segment.

**Comment by alanjcharles** [comment]
thanks for the note @jedashford we are currently in the process of revamping our segment documentation to account for holes like this. I will also merge your PRs to the readme.
