### ISSUE TITLE
Expo Managed Android: Library causes v46.0.0 custom builds to error out and v45.0.0 custom builds to silently fail in the emulator

### ISSUE THREAD

**Issue by conoremclaughlin** [segmentio/analytics-react-native#638]
Adding this here for visibility:

Expo v46.0.0 - Sovran React Native cannot be built on Expo v46 for Android due to what appears to be old Kotlin files. 
https://github.com/segmentio/sovran-react-native/issues/39

Expo v45.0.0 - AnalyticsProvider will cause app.tsx to silently error out on custom built Android apks in the Android Emulator making navigation impossible and many libraries unable to return a result. The user interface becomes unresponsive but no error output is given. We fixed the issue by removing the library for our custom builds. 

We suspect both are due to old Android implementations. 

Expo now recommends using this library instead of their own segment package since `expo run:android` and `expo run:ios` support custom code.

- `analytics-react-native` version: 2.5.1
- Integrations versions (if used):
- React Native version: 0.68.3 (v45.0.0)
- iOS or Android or both?

**Steps to reproduce**
v46 - build an Expo app with `expo run:android`
v45 - create two screens and attempt to navigate between them on a custom-built apk on a Google API v31 Android emulator.

**Expected behavior**
v46 - build should successfully complete and run.
v45 - app should be able to navigate between screens and not halt form submissions via Formik and other network calls. 

**Actual behavior**
v46 - crashes the build.
v45 - navigation via react-navigation fails. all form submissions via Formik and other network fail without ever timing out

**Comment by alanjcharles** [comment]
@conoremclaughlin we just pushed a fix for [Android builds on Expo v46](https://github.com/segmentio/analytics-react-native/releases/tag/%40segment%2Fanalytics-react-native-v2.7.1).  Please feel free to follow up with more information if your builds are still failing

**Comment by conoremclaughlin** [comment]
Thank you, Alan! We’ll try it out!
