### ISSUE TITLE
IDFA Collision with Braze's recommended approach for enabling push notifications

### ISSUE THREAD

**Issue by jayfunk** [segmentio/analytics-react-native#641]
I have setup the example project to demonstrate the issue that I am encountering. I have setup the IDFA plugin as described in the documentation. I have then implemented a [minimal example](https://www.braze.com/docs/developer_guide/platform_integration_guides/react_native/push_notifications/) from the Braze docs for setting up push notifications. I have found that the push notification prompt will load before the IDFA plugin has had the chance to prompt the user for app tracking permissions. Due to this race condition the IDFA plugin is unable to properly mount, it is only after completely killing the app and restarting it, after push notification permissions have been determined, that the app tracking prompt is displayed. Then IDFA tracking events will be triggered, along with all other events containing the actual state of the ad tracking.

In my own application I added a prompt that displays before the push notification prompt, to see if that would resolve the issue, but it appears the IDFA plugin will not report the correct state of the prompt until the app has been killed and restarted.

Added to AppDelegate.mm:
```
- (void)applicationDidBecomeActive:(UIApplication *)application {
  if (@available(iOS 14.0, *)) {
    [ATTrackingManager requestTrackingAuthorizationWithCompletionHandler:^(ATTrackingManagerAuthorizationStatus status) {}];
  }
}

```

I might be handling this in an incorrect fashion, is there a recommended way to handle this?

- `analytics-react-native` version: 2.7.0
- Integrations versions (if used): IDFA Plugin 0.4.1
- React Native version: 0.69.2
- iOS or Android or both? iOS

**Steps to reproduce**
Apply the following diff to the example project in the @segment/analytics-react-native:
```
commit 7d77263c9a2cc93a90c316f2c863ffe74772e1e7
Author: Tyler Cook <tyler.cook@self.inc>
Date:   Thu Aug 11 12:26:17 2022 -0500

    Added minimal demonstration of IDFA plugin collision with Braze's
    recommended apporach for adding push notification support

diff --git a/example/ios/AnalyticsReactNativeExample/AppDelegate.h b/example/ios/AnalyticsReactNativeExample/AppDelegate.h
index 69dcc132..82bb2131 100644
--- a/example/ios/AnalyticsReactNativeExample/AppDelegate.h
+++ b/example/ios/AnalyticsReactNativeExample/AppDelegate.h
@@ -8,8 +8,9 @@
 #import <React/RCTBridgeDelegate.h>
 #import <UIKit/UIKit.h>
 #import <React/RCTBridgeModule.h>
+#import <UserNotifications/UNUserNotificationCenter.h>
 
-@interface AppDelegate : UIResponder <UIApplicationDelegate, RCTBridgeDelegate>
+@interface AppDelegate : UIResponder <UIApplicationDelegate, RCTBridgeDelegate, UNUserNotificationCenterDelegate>
 
 @property (nonatomic, strong) UIWindow *window;
 
diff --git a/example/ios/AnalyticsReactNativeExample/AppDelegate.mm b/example/ios/AnalyticsReactNativeExample/AppDelegate.mm
index 0c9310dc..4c5827c1 100644
--- a/example/ios/AnalyticsReactNativeExample/AppDelegate.mm
+++ b/example/ios/AnalyticsReactNativeExample/AppDelegate.mm
@@ -25,6 +25,14 @@ static NSString *const kRNConcurrentRoot = @"concurrentRoot";
 @implementation AppDelegate
 - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
 {
+UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
+    center.delegate = self;
+    UNAuthorizationOptions options = UNAuthorizationOptionAlert | UNAuthorizationOptionSound | UNAuthorizationOptionBadge;
+    [center requestAuthorizationWithOptions:options
+                          completionHandler:^(BOOL granted, NSError * _Nullable error) {
+    }];
+    [[UIApplication sharedApplication] registerForRemoteNotifications];
+
   RCTAppSetupPrepareApp(application);
   RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
 #if RCT_NEW_ARCH_ENABLED
diff --git a/example/src/App.tsx b/example/src/App.tsx
index 7989c372..c555af1a 100644
--- a/example/src/App.tsx
+++ b/example/src/App.tsx
@@ -28,7 +28,7 @@ import { Logger } from './plugins/Logger';
 // import { FacebookAppEventsPlugin } from '@segment/analytics-react-native-plugin-facebook-app-events';
 
 // @ts-ignore
-// import { IdfaPlugin } from '@segment/analytics-react-native-plugin-idfa';
+import { IdfaPlugin } from '@segment/analytics-react-native-plugin-idfa';
 
 // @ts-ignore
 import { AmplitudeSessionPlugin } from '@segment/analytics-react-native-plugin-amplitude-session';
@@ -45,9 +45,9 @@ const segmentClient = createClient({
   flushInterval: 10,
 });
 
-const LoggerPlugin = new Logger();
+// const LoggerPlugin = new Logger();
 
-segmentClient.add({ plugin: LoggerPlugin });
+// segmentClient.add({ plugin: LoggerPlugin });
 
 // To see an example Consent Manager uncomment the following
 // const ConsentManagerPlugin = new ConsentManager();
@@ -59,9 +59,9 @@ segmentClient.add({ plugin: LoggerPlugin });
 // To test the Facebook App Events plugin make sure to add your Facebook App Id to Info.plist
 // segmentClient.add({ plugin: new FacebookAppEventsPlugin() });
 
-// segmentClient.add({ plugin: new IdfaPlugin() });
+segmentClient.add({ plugin: new IdfaPlugin() });
 
-segmentClient.add({ plugin: new AmplitudeSessionPlugin() });
+// segmentClient.add({ plugin: new AmplitudeSessionPlugin() });
 
 // segmentClient.add({
 //   plugin: new AdvertisingIdPlugin(),
```

Load the application and notice the push notification prompt displays before the app tracking prompt. This makes it so the IDFA plugin never attempts to determine app tracking status. There is a log message when this occurs that makes me think the IDFA plugin is not getting loaded properly:

```
 WARN  Sending `IDFAQuery` with no listeners registered.
```

**Expected behavior**

The ad tracking prompt is displayed to the user after other system level prompts have been dismissed or if ad tracking selection was determined before the IDFA plugin is fully loaded it should report the correct selection for ad tracking.

**Actual behavior**

https://user-images.githubusercontent.com/2545666/184200837-54686947-c595-4c91-9c17-980a60aadfaa.mov

Ad tracking prompt never displays. If ad tracking is determined before the IDFA plugin loads, the incorrect Ad tracking state is reported.

**Comment by jedashford** [comment]
We built our own IDFA stuffs, so I can't speak for the plugin, but I did spend weeks in the hell of a configuration between segment and braze. I can say that we did not implement Braze's push notification prompt in the app delegate, instead we manage it ourselves with firebase. So to be clear, we followed braze instructions, but did not include the requestAuthorizationWithOptions:options  stuff. Then in RN land, we used firebase messaging to request permission from the user. As soon as they accept, then braze picks up the event from the appdelegate, and we also get the token in RN code. Maybe this can help you. I'd suggest opening a ticket with segment as I've had trouble with them responding through issues in github.

```
  async function requestUserPermission() {
    const authStatus = await messaging().requestPermission()
    const enabled = authStatus === messaging.AuthorizationStatus.AUTHORIZED || authStatus === messaging.AuthorizationStatus.PROVISIONAL
    Analytics.trackEvent<NotificationPermission>('Notification Permission', {enabled, authStatus})

    if (enabled) {
      const token = await messaging().getToken()
      handleNotificationToken(token).then()
    }
  }

  const handleNotificationToken = async (token: string) => {
    console.log(formatLog('PUSH_NOTIFICATION', 'FCM Push Token:'), token)
    Analytics.trackEvent<NotificationToken>('Notification Token', {token})
    // TODO send token to server?
  }

  async function decideNotifications() {
    // if they chose not to enable notifications, don't show the modal
    // if they have not told us to disable notifications, and its iOS, then show our modal
    const notificationDecision = await getNotificationDecision()
    const permissionStatus = await messaging().hasPermission()
    const hasNotificationPermission: boolean =
      permissionStatus === messaging.AuthorizationStatus.AUTHORIZED || permissionStatus === messaging.AuthorizationStatus.PROVISIONAL
    if (notificationDecision !== 'no' && Platform.OS === 'ios' && !hasNotificationPermission) {
      Analytics.trackScreen('Notification Screen')
      setShowModal(true)
    } else if (Platform.OS === 'android') {
      requestUserPermission().then()
    } else if (hasNotificationPermission) {
      const token = await messaging().getToken()
      handleNotificationToken(token).then()
    }
  }

**Comment by alanjcharles** [comment]
@jayfunk Thanks for reporting this! I'll be able to take a look at this later today or tomorrow morning and will follow up as soon as I have an update for you. 

@jedashford apologies for delayed responses, we try to be as active as possible on here.
