### ISSUE TITLE
segment_sovran-react-native:compileDebugKotlin FAILED  FAILURE: Build failed with an exception

### ISSUE THREAD

**Issue by Joshmatjjen** [segmentio/analytics-react-native#645]
I go this error after running:    **expo run:android**

> Task :segment_sovran-react-native:compileDebugKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':segment_sovran-react-native:compileDebugKotlin'.

- `analytics-react-native` version: 2.7.0
- Integrations versions (if used):
- React Native version:  0.69.4
- Android
-  Expo version:  "^46.0.0",

**Comment by pinpointpanda** [comment]
We've also just randomly started seeing Kotlin compilation fails with the AppsFlyer plugin (version 1). No changes in the project recently...

```
> Task :segment_analytics-react-native:compileDebugKotlin
w: /Users/mike/mike/eps/repos/eba-frontend/node_modules/@segment/analytics-react-native/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalytics.kt: (34, 17): Parameter 'idfa' is never used
w: /Users/mike/mike/eps/repos/eba-frontend/node_modules/@segment/analytics-react-native/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalyticsModule.kt: (69, 40): 'versionCode: Int' is deprecated. Deprecated in Java
w: /Users/mike/mike/eps/repos/eba-frontend/node_modules/@segment/analytics-react-native/android/src/main/java/com/segment/analytics/reactnative/core/RNAnalyticsModule.kt: (304, 62): Unchecked cast: Map<Any!, Any!> to Map<String, Any>

> Task :segment_analytics-react-native-appsflyer:compileDebugKotlin FAILED


...

e: Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors
e: /Users/mike/.gradle/caches/transforms-2/files-2.1/427ab7821a83589e8ed19d3fd5788140/jetified-kotlin-stdlib-jdk7-1.6.10.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
e: /Users/mike/.gradle/caches/transforms-2/files-2.1/610eff92e7fcd09f44778e1a2ee8ec59/jetified-kotlin-stdlib-jdk8-1.6.10.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
e: /Users/mike/.gradle/caches/transforms-2/files-2.1/7427efbc536a72c5f2271f2113560c30/jetified-kotlin-stdlib-common-1.6.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
e: /Users/mike/.gradle/caches/transforms-2/files-2.1/d3893146611e772f05aeb571259283c4/jetified-kotlin-stdlib-1.6.10.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
e: /Users/mike/mike/eps/repos/eba-frontend/node_modules/@segment/analytics-react-native-appsflyer/android/src/main/java/com/segment/analytics/reactnative/integration/appsflyer/IntegrationModule.kt: (40, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
The class is loaded from /Users/mike/.gradle/caches/transforms-2/files-2.1/d3893146611e772f05aeb571259283c4/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/mike/mike/eps/repos/eba-frontend/node_modules/@segment/analytics-react-native-appsflyer/android/src/main/java/com/segment/analytics/reactnative/integration/appsflyer/IntegrationModule.kt: (42, 21): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
The class is loaded from /Users/mike/.gradle/caches/transforms-2/files-2.1/d3893146611e772f05aeb571259283c4/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
e: /Users/mike/mike/eps/repos/eba-frontend/node_modules/@segment/analytics-react-native-appsflyer/android/src/main/java/com/segment/analytics/reactnative/integration/appsflyer/IntegrationPackage.kt: (36, 16): Unresolved reference: emptyList
e: /Users/mike/mike/eps/repos/eba-frontend/node_modules/@segment/analytics-react-native-appsflyer/android/src/main/java/com/segment/analytics/reactnative/integration/appsflyer/IntegrationPackage.kt: (40, 16): Unresolved reference: listOf

```



Version numbers:

    "@segment/analytics-react-native": "1.4.8",
    "@segment/analytics-react-native-appsflyer": "1.4.7",
    "react-native": "0.63.3",

**Comment by anhtrlive** [comment]
Same thing, yesterday everything was working, today it's an error.
I fixed this by add:
```
buildscript {
    ext {
       ...
        kotlinVersion = "1.6.0"
    }
```

```
dependencies {
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
    ...
```

my package.json:
```
    "react-native": "0.64.3",
    "@segment/analytics-react-native": "^1.5.2",
    "@segment/analytics-react-native-appsflyer": "^1.5.0",
```

my gradle properties:
```
...
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip
...
```

**Comment by pinpointpanda** [comment]
@alanjcharles any insight on this one? Seems a strange thing to just suddenly have builds start breaking, not sure what could have changed or where :)

**Comment by Joshmatjjen** [comment]
> Same thing, yesterday everything was working, today it's an error. I fixed this by add to `android/build.gradle`:
> 
> ```
> buildscript {
>     ext {
>        ...
>         kotlinVersion = "1.6.0"
>     }
> ```
> 
> ```
> dependencies {
>     classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
>     ...
> ```
> 
> my package.json:
> 
> ```
>     "react-native": "0.64.3",
>     "@segment/analytics-react-native": "^1.5.2",
>     "@segment/analytics-react-native-appsflyer": "^1.5.0",
> ```
> 
> my gradle properties:
> 
> ```
> ...
> distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip
> ...
> ```

**Comment by Joshmatjjen** [comment]
> Same thing, yesterday everything was working, today it's an error. I fixed this by add to `android/build.gradle`:
> 
> ```
> buildscript {
>     ext {
>        ...
>         kotlinVersion = "1.6.0"
>     }
> ```
> 
> ```
> dependencies {
>     classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
>     ...
> ```
> 
> my package.json:
> 
> ```
>     "react-native": "0.64.3",
>     "@segment/analytics-react-native": "^1.5.2",
>     "@segment/analytics-react-native-appsflyer": "^1.5.0",
> ```
> 
> my gradle properties:
> 
> ```
> ...
> distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip
> ...
> ```

@anhtrlive   This won't work for EAS expo since android folder is being generated

**Comment by anhtrlive** [comment]
If I understand correctly, the problem in `analytics-react-native-appsflyer/android/build.gradle` and it should fix it:

```diff
buildscript {
    repositories {
        jcenter()
        maven { url 'https://maven.google.com' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'
-        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.21'
+        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.0'
    }
}
```

**Comment by MorenoMdz** [comment]
Bumping this one

**Comment by MorenoMdz** [comment]
Have you folks tried setting the Kotlin version in the app config plugins or is it a more specific config?

**Comment by KaterinaUK** [comment]
Update in /node_modules/@segment/analytics-react-native-plugin-advertising-id/android/build.gradle change line 31 from minSdkVersion 19 to minSdkVersion 28, fixed the issue.
