### ISSUE TITLE
InjectTraits example - is this a typo?

### ISSUE THREAD

**Issue by 256hz** [segmentio/analytics-react-native#647]
## Summary
We're integrating the AppsFlyer React Native SDK into our application and have a question about the InjectTraits example provided [in the docs here](https://github.com/segmentio/analytics-react-native/blob/master/example/src/plugins/InjectTraits.ts).  Specifically this part:

```
    return {
      ...event,
      context: {
        ...event.context,
        traits: {
          ...event.context, // should this be ...event.context.traits?
```

Should the entire context be nested under the `traits` key?  Wouldn't this mean that any preexisting traits become nested under `event.context.traits.traits` instead of merged with the new ones?

Either way, clarification in the docs would be appreciated especially if this is intended behavior!  Thank you.

**Comment by oscb** [comment]
Thanks for this! This is a good catch, you're correct, it should be `...events.context.traits?`, not the full context. I'll make a fix on the example.
