### ISSUE TITLE
ConsentManager.tsx implemenation example insufficient

### ISSUE THREAD

**Issue by te-online** [segmentio/analytics-react-native#650]
It's amazing you provide examples for custom plugins, especially around consent!

However, I recently had to fix a few bugs with an implementation based on [this specific example](https://github.com/segmentio/analytics-react-native/blob/master/example/src/plugins/ConsentManager.tsx). In doing that I found a couple of issues with the example in question:

- It uses an alert to ask for permission while most users probably should use built-in OS permission request (iOS) or some custom UI (Android)
- It does not honor types of the super class, doesn't make it clear which methods are overrides and which ones are custom
- It ignores asynchronous operations and just fires them without waiting for a result, making error handling difficult
- It doesn't persist consent in any meaningful way, but makes it look like it does (especially the "Consent Authorized"). Why would anyone ask for permission every single time your app is started?

This example will likely send a beginner into a weird debugging loop.

I simplified the implementation for our case like this:
```ts
import {
  Plugin,
  PluginType,
  SegmentEvent,
} from '@segment/analytics-react-native';

export class ConsentManager extends Plugin {
  public type = PluginType.before;
  public key = 'Consent Manager';
  private consentStatus?: boolean;
  private queuedEvents: SegmentEvent[] = [];

  // We can override the behavior of event collection
  // by overriding this Plugin class method
  override execute(event: SegmentEvent) {
    if (this.consentStatus === true) {
      return event;
    }

    // When the status is not yet defined, we save events for later
    if (this.consentStatus === undefined) {
      this.queuedEvents.push(event);
      return;
    }

    // Consent was rejected
    this.queuedEvents = [];
    return;
  }

  public async setConsent(status: boolean): Promise<void> {
    this.consentStatus = status;
    await this.sendQueued();
  }

  private async sendQueued(): Promise<void> {
    const eventsToSubmit = [...this.queuedEvents];
    this.queuedEvents = [];
    for (const event of eventsToSubmit) {
      await this.execute(event);
    }
  }
}

```

Then I use the `setConsent` method from the outside and persist it there (for example in App.tsx). On start of the app, you can then pass the current state to the ConsentManager instance.

Happy to hear what you think about reworking this specific example. Sorry I didn't provide a PR, as this was faster for me to just share some feedback.

**Comment by alanjcharles** [comment]
Hi @te-online This is amazing, thanks for the feedback! I'd love to rework the example as we just haven't had the cycles to beef up all of the original examples we rolled out when in beta. Would you be able to make a PR whenever you have the chance so I can review it/pull it down and play with it? Thanks again!

**Comment by oscb** [comment]
Closing. 

The Consent management example might stay just as an example of more advanced plugins while we work on a more official version of it for release.
