### ISSUE TITLE
Amplitude events are reported as "outside session"

### ISSUE THREAD

**Issue by rborn** [segmentio/analytics-react-native#654]
Hello, 
I updated the module to v2 but now all the Amplitude events are "outside of session" (green) instead of "inside session" (blue)

https://help.amplitude.com/hc/en-us/articles/229313067-Look-up-event-data-for-individual-users#:~:text=Blue%20events%20in%20a%20session,or%20only%20show%20specific%20events.

- `analytics-react-native` version: 2.7.0
- Integrations versions (if used): analytics-react-native-plugin-amplitude-session": "0.3.1"
- React Native version: 0.67.4
- Both iOs and Android

**Steps to reproduce**

I just updated and adapted the module to version 2 (was 1.x before)

my code:

```
        Analytics = createClient({
            writeKey: configuration.apiKeys.segmentio,
            autoAddSegmentDestination: true,
            trackAppLifecycleEvents: true,
            trackAttributionData: true,
            debug: debugConfigs.segment,
            flushInterval: Config.APP_TYPE === 'test' || Config.APP_TYPE === 'demo' ? 1 : 20,
            flushAt: Config.APP_TYPE === 'test' || Config.APP_TYPE === 'demo' ? 1 : 20,
            trackDeepLinks: true
        });

        Analytics.add({ plugin: new AmplitudeSessionPlugin() });
```

**Expected behavior**

Amplitude should receive the events as being part of a session while they seem to be interpreted as being sent server side

**Actual behavior**

All events show as "outside"

Here is a sample of the difference:
![Screenshot 2022-08-24 at 16 32 09](https://user-images.githubusercontent.com/406409/186445924-613ec578-1197-4025-95ba-331d6af06481.png)

We are measuring the time the users are stating in the app, and currently this is broken 
![Screenshot 2022-08-24 at 16 47 12](https://user-images.githubusercontent.com/406409/186449395-4b36a68f-0a64-4e14-a398-3d9205b93275.png)

Thank you ❤️

**Comment by alanjcharles** [comment]
Hi @rborn Sorry to hear you're having issues with your migration. I've added this to our current sprint and will take a look as soon as I have a chance. Thanks for your patience!

**Comment by rborn** [comment]
@alanjcharles thanks for looking into this.
I think I have found something, we had the Segment/Amplitude connection since 3.5 years ago 😅, but it seems something changed and now there are 2 ways of doing this, "Actions" and "Classic" (we were Classic)


![Screenshot 2022-08-25 at 10 58 41](https://user-images.githubusercontent.com/406409/186676165-b001134d-2fff-414f-bec4-9b688227cee4.png)

I've redone the connection in the new Action mode and it seems the events start to pickup  and be "blue" again.
There are still users that keep being "green" but I believe the events will only be considered in a session if there is a session started, so if the users had the app in background probably won't show as blue.

I won't close the ticket for now, but I'll come back in a few days ( we'll make a new release) and update you.

If it turns to be this maybe this is something to mention in the docs?

Thanks for everything 🥰

**Comment by alanjcharles** [comment]
Hi @rborn Sorry I missed your message! I was just looking at this again to try and come up with a fix but it seems like you might have gotten it sorted! Please let me know whenever you have the chance. If that is the case, I'll be sure to add it to the documentation. Thanks so much!

**Comment by rborn** [comment]
@alanjcharles hey, yes all seems to be working after the new connection setup. Sorry for not getting back to you in time :(

**Comment by alanjcharles** [comment]
@rborn  no problem at all ! Thanks for letting me know.
