### ISSUE TITLE
The SDK needs to be decoupled from AsyncStorage

### ISSUE THREAD

**Issue by shamilovtim** [segmentio/analytics-react-native#655]
AsyncStorage should not be a transitive dependency of this library. Instead we should be able to provide you with getters and setters of our own local storage solution. In our case, we use MMKV. End users will be dissatisfied to learn that the entire AsyncStorage library has been brought into their project especially when they have opted not to use it due to performance concerns. Could you please provide a timeline for refactoring this issue with your RN SDK?

**Comment by oscb** [comment]
You can replace the AsyncStorage persistor with your own implementation. The [`storePersistor` option](https://github.com/segmentio/analytics-react-native/blob/256b7653a43b81e77947c35137b99878125315a8/packages/core/src/types.ts#L128) in the client lets you pass a getter and a setter for your own implementation of the persistence layer.

**Comment by shamilovtim** [comment]
> You can replace the AsyncStorage persistor with your own implementation. The [`storePersistor` option](https://github.com/segmentio/analytics-react-native/blob/256b7653a43b81e77947c35137b99878125315a8/packages/core/src/types.ts#L128) in the client lets you pass a getter and a setter for your own implementation of the persistence layer.

As long as AsyncStorage does not get bundled or linked into a project that's great.

**Comment by shamilovtim** [comment]
@oscb as a matter of open source etiquett please don't close issues without a proper resolution. in my previous comment I mentioned that you have asyncstorage as a dep rather than a peerdep so it's highly likely that you are going to link it into everyone's projects. react native does not treeshake native packages.

i see a contributor is doing this work now: https://github.com/segmentio/analytics-react-native/pull/734

**Comment by thianphat** [comment]
Hi @shamilovtim , I was curious if you could provide an example of making this work with MMKV. I've tried adding the MMKV storage to storePersistor:

`storePersistor: storage`

Where `storage` is equal to `new MMKV()`

However, it's not working and of course, I am getting type errors where the methods don't align. How did you go about integrating this? Really appreciate it.
