### ISSUE TITLE
Filter which events to sent to firebase

### ISSUE THREAD

**Issue by dgreasi** [segmentio/analytics-react-native#658]
## Summary

When adding firebase plugin in your app:
```
segmentClient.add({ plugin: new FirebasePlugin() });
```

All the events will be sent directly to Firebase and Segment as the [documentation](https://segment.com/docs/connections/destinations/catalog/firebase/) describes:
```
Firebase is Google’s platform for mobile apps. The Segment Firebase destination requires that you bundle the Firebase SDK with your project. The Segment-wrapped destination code then runs on the user’s device, and sends its tracking calls to the Firebase API endpoints, and a copy to Segment for archiving.
```

It could be useful if those events are only sent to Segment and then you could use the **Destination Filters** functionality to filter out what events should be sent to the final destination based on **traits**.

As of now, it seems that the only way to not send events to Firebase is to remove the plugin from the segment client.

Am i missing something?

**Comment by oscb** [comment]
We are actually working on getting Destination Filters working on device mode plugins in a future release of the library.

Right now you can filter events but you have to manually code your own plugin to filter them. I can provide some examples if it is helpful!

**Comment by dgreasi** [comment]
This would be helpful if the custom plugin can be applied to filter events that have as destination FIrebasePlugin.

**Comment by alanjcharles** [comment]
@dgreasi There is a tutorial at the end of [this blog](https://segment.com/blog/analytics-react-native-2-blog/ ) to do exactly what you're describing, if [Destination Filters](https://segment.com/docs/connections/sources/catalog/libraries/mobile/react-native/#destination-filters) don't work for you. Hope this helps!

**Comment by dgreasi** [comment]
@alanjcharles thanks for the response. The custom plugin approach is not so useful in our case.

We are still waiting for the Destination Filters for Firebase, so that every event goes only in Segment and then be forwarded to the appropriate destinations.
