### ISSUE TITLE
UserId sent to Clevertap not change after Clevertap change userId

### ISSUE THREAD

**Issue by minhchienwikipedia** [segmentio/analytics-react-native#669]
I'm using Segment and CleverTap, we want to send the events from Segment to CleverTap but when the user logout and changes to another account userId change as well but Segment still sent the tracking events to the old account. What exactly flows to work with multiple accounts on the same device?

- `analytics-react-native` version: 2.7.2
- Integrations versions (if used): Native iOS, Android for CleverTap
- React Native version: 0.66
- iOS or Android or both? both

**Steps to reproduce**

**Expected behavior**

**Actual behavior**

**Comment by alanjcharles** [comment]
@minhchienwikipedia thanks for reaching out! [The only available Segment <> Clevertap integration (ie 1.5.3)](https://www.npmjs.com/package/@segment/analytics-react-native-clevertap) currently only works with versions of `analytics-react-native` below `2.0.0`. We are working on a new integration that will be supported for versions `2.0.0` and greater. You can follow status updates here #582
