### ISSUE TITLE
Deep link tracking with UTM params

### ISSUE THREAD

**Issue by Moorst** [segmentio/analytics-react-native#671]
## Summary

I want to track utm params on deep links in my react native app. It appears that you can't pass properties to the context via the `useAnalytics` screen method - only the `screenName` and `options` which are passed to the properties object.  

Is there a suggested method of doing this?

I also followed the `iOS Deep Link Tracking Setup` but this conflicts with the changes I made in the AppDelegate.m for react navigation:

```
- (BOOL)application:(UIApplication *)application
   openURL:(NSURL *)url
   options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [RCTLinkingManager application:application openURL:url options:options];
}

- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity
 restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
{
 return [RCTLinkingManager application:application
                  continueUserActivity:userActivity
                    restorationHandler:restorationHandler];
}

```

Could you suggest how to update my AppDelegate.m to cater for both react navigation & segment in this instance?

**Comment by oscb** [comment]
Hi @Moorst,

You can add the line:
```
[AnalyticsReactNative trackDeepLink:url withOptions:options]; 
```

before handling your deeplinks:

```objective-c
#import <segment_analytics_react_native-Swift.h>

- (BOOL)application:(UIApplication *)application
   openURL:(NSURL *)url
   options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  [AnalyticsReactNative trackDeepLink:url withOptions:options]; 
  return [RCTLinkingManager application:application openURL:url options:options];
}
```


We will also explore adding a method directly into the client to set these values manually.

Let me know if that helps!

**Comment by Moorst** [comment]
That's helpful, thank you.


But in terms of passing the utm params to the context, how can I achieve that?
