### ISSUE TITLE
defaultSettings are not applied correctly when settings can't be fetched

### ISSUE THREAD

**Issue by jgable** [segmentio/analytics-react-native#678]
- `analytics-react-native` version: latest
- Integrations versions (if used): not used
- React Native version: latest
- iOS or Android or both?: both

**Steps to reproduce**

- Initialize a client with a defaultSettings object passed to createClient
- SegmentDestination is not enabled because the integrations objects is not passed

```ts
const client = createClient({
  defaultSettings: {
    integrations: {
      "Segment.io": {
        apiKey,
        apiHost: CUSTOM_INGESTION_URL,
        ...DEFAULT_SEGMENT_SETTINGS,
      },
    }
  },
  writeKey: apiKey,
  trackAppLifecycleEvents: true,
  flushAt: 10,
  proxy: CUSTOM_INGESTION_URL,
});
```

**Expected behavior**

- defaultSettings should be applied when passed

**Actual behavior**

- defaultSettings are not applied and the segment destination is not enabled

**Workaround**

You can specify just the integrations part and add a @ts-ignore to workaround this issue, but I'm unsure what other problems this might cause.

```ts
this.client = createClient({
  defaultSettings: {
    // @ts-ignore Segment defaultSettings type is bugged, you only pass the integrations part
    "Segment.io": {
      apiKey,
      apiHost: CUSTOM_INGESTION_URL,
      ...DEFAULT_SEGMENT_SETTINGS,
    },
  },
  writeKey: apiKey,
  trackAppLifecycleEvents: true,
  flushAt: 10,
  proxy: CUSTOM_INGESTION_URL,
});
```

**Specific Code Affected**

I believe these lines are the culprit. Notice that when getting a settings response json only the integrations piece is passed to store.settings.set on line 249 but the whole defaultSettings object is passed on line 259.

https://github.com/segmentio/analytics-react-native/blob/076848f9fffbd9bcf126805b177f4d62029017b2/packages/core/src/analytics.ts#L244-L262

**Comment by konoufo** [comment]
This is now fixed by #684. Thank you for reporting this!
