### ISSUE TITLE
Offline-first support

### ISSUE THREAD

**Issue by ivansantosz** [segmentio/analytics-react-native#68]
Does this lib support buffer events when the device is offline? if yes, maybe I could update the docs?

**Comment by adamzerner** [comment]
I believe so. I asked this question to support and got this response:

> Yeah, messages will still be queued in our React Native library. It is essentially a wrapper for both our Android and IOS libraries so you should expect any mobile behavior mentioned in our docs to work with React Native. Please let me know if that's not the case!
