### ISSUE TITLE
Wrong version when event sent to Segment

### ISSUE THREAD

**Issue by sonnguyprophet** [segmentio/analytics-react-native#682]
I have installed the latest version as below 

    "@segment/analytics-react-native": "^2.8.0"
    "@segment/analytics-react-native-plugin-appsflyer": "^0.4.0"
    "@segment/analytics-react-native-plugin-braze": "^0.4.0"
    "@segment/analytics-react-native-plugin-mixpanel": "^0.2.3"

I saw that when the events were sent to Segment it still used 2.7.2 version instead 2.8.0, please refer images below
![image](https://user-images.githubusercontent.com/92285567/191882961-08e0faac-14ac-403f-9c81-9185cd7cb2be.png)
![image](https://user-images.githubusercontent.com/92285567/191883942-5e9d2fe1-00fb-4b83-b52d-70260a0d46d0.png)

- `analytics-react-native` version: 2.8.0
- Integrations versions (if used):
- React Native version: 0.67.4
- iOS or Android or both? both

**Steps to reproduce**

**Expected behavior**
it should be 2.8.0 version
**Actual behavior**
still track with 2.7.2 version

**Comment by oscb** [comment]
Thanks for reporting this, we are aware of this error in the event versioning, we're looking into possible solutions. This was introduced with a previous fix in the build.

**Comment by oscb** [comment]
This will be fixed in the next release
