### ISSUE TITLE
[Question] Why the need for AdMob for advertising-id

### ISSUE THREAD

**Issue by TrekSoft** [segmentio/analytics-react-native#687]
For the `analytics-react-native-plugin-advertising-id` it seems we need to setup the app in AdMob.

Why is this needed?

My understanding is that the the advertising id is specific to the device, independent of that platform.

**Comment by bprymicz** [comment]
We skipped that step and was still seeing the advertisingId show up in the debugger. So unless something changes, I don't think it's required.

**Comment by alanjcharles** [comment]
apologies- seems like it was just a mix up when referencing the documentation. Thanks for the heads up, I will remove it from the documentation!

**Comment by TrekSoft** [comment]
Thanks so much both!

**Comment by gbyesiltas** [comment]
Hey everyone, I know this was closed a long time ago but I believe the step was not removed from the documentation? Or was there another piece of documentation that's not there anymore? In any case, I opened a PR to remove the part that got me confused about the AdMob step
