### ISSUE TITLE
Return value of useAnalytics is not memoized

### ISSUE THREAD

**Issue by jalada** [segmentio/analytics-react-native#689]
Hey Segment! In the definition of `useAnalytics`:

https://github.com/segmentio/analytics-react-native/blob/3cfa8b953eb1ae66f519b16fc4ed43a527586832/packages/core/src/client.tsx#L52

You're returning an object with a bunch of functions in it. I _think_ that because you're not memoizing the object it's considered different on every run. This can cause issues if one of them is being used as a dependency for a `useEffect` callback, because the callback will get called over and over.

The bad workaround is to not include it as a dependency, which eslint hates. I made this workaround feel slightly nicer by limiting it to a memoized wrapper of your hook:

```javascript
import {useAnalytics} from "@segment/analytics-react-native";
import {useMemo} from "react";

const useMemoizedAnalytics = () => {
  const analyticsFns = useAnalytics();
  return useMemo(
    () => analyticsFns,
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [],
  );
};

export default useMemoizedAnalytics;
```

Lemme know if I'm mistaken - I've been using React since beta and this stuff still confuses me... For example, I'm wondering if my workaround will be a problem if the client context changes? Perhaps I should be checking that context myself too...

**Comment by vkundapur** [comment]
Ya, I have seen this issue as well

**Comment by oscb** [comment]
This is great feedback and a good catch. I don't think your solution will give you any issues, technically yes, the context might change which will give you a different client object so you might want to check for that in memoization but to be fair that is a very edge case, unless you are switching clients in your `<AnalyticsProvider>` you should be fine.

I will make the change to return a memoized set of functions, no reason for these to be regenerated every time.
