### ISSUE TITLE
is there a moengage plugin available for segment?

### ISSUE THREAD

**Issue by rizshivalli** [segmentio/analytics-react-native#690]
Do we have a moengage plugin available for segment in react native?

**Comment by oscb** [comment]
No, we don't have a plugin for moengage right now. That said you can use the cloud mode destination: https://segment.com/docs/connections/destinations/catalog/moengage/

Is there any functionality in particular you need from the device mode plugin for moengage?
It should also be easy to create a plugin for your scenario if needed, but I would strongly recommend using the cloud mode destination if that works for you: https://github.com/segmentio/analytics-react-native#writing-your-own-plugins

**Comment by zeusstl** [comment]
@rizshivalli Are you suggesting to install Moengage using Segment Moengage IOS installation (https://github.com/moengage/MoEngage-Segment-iOS) and then use cloud mode for passing the events to moengage?

**Comment by zeusstl** [comment]
There is actually a new Moengage plugin for Segment now: `react-native-segment-plugin-moengage`
https://www.npmjs.com/package/react-native-segment-plugin-moengage
