### ISSUE TITLE
this.proccess is not a function (offline mode)

### ISSUE THREAD

**Issue by mi-mazouz** [segmentio/analytics-react-native#692]
Hi folks,

I'm trying to call track function in a saga, here is my code

Analytic.ts
```
import { createClient } from '@segment/analytics-react-native';
import { AmplitudeSessionPlugin } from '@segment/analytics-react-native-plugin-amplitude-session';
import Config from 'react-native-config';

const segmentClient = createClient({
    writeKey: Config.SEGMENT_WRITE_KEY,
});

segmentClient.add({ plugin: new AmplitudeSessionPlugin() });

export default segmentClient;
```

saga.ts
```
import Analytic from './analytic';

function* myFunction() {
    try {
        yield call(Analytic.track, 'MY_ENVENT_NAME');
    } catch (error) {
        console.log(error);
    }
}
```

I want to notice that I have no internet connection when this saga is running.

I got this error:

```
TypeError: this.process is not a function
    at track$ (analytics.ts:482)
    at tryCatch (regeneratorRuntime.js:86)
    at Generator._invoke (regeneratorRuntime.js:66)
    at Generator.next (regeneratorRuntime.js:117)
    at tryCatch (regeneratorRuntime.js:86)
    at invoke (regeneratorRuntime.js:124)
    at regeneratorRuntime.js:148
    at tryCallTwo (core.js:45)
    at doResolve (core.js:200)
    at new Promise (core.js:66)
```

Everything works fine if I'm online, either using the useAnalytics hook in components or calling the client directly in a saga like above. So I guess this problem is happening because I'm offline.

The doc doesn't say much about offline mode so any help on that would be appreciated.

- "@segment/analytics-react-native": "^2.8.0",
- "@segment/analytics-react-native-plugin-amplitude-session": "^0.3.1",
- "@segment/sovran-react-native": "^0.4.4",
- "react-native": "0.68.2",
- iOS or Android or both? IOS not tested on android

**Comment by oscb** [comment]
I'm not very familiar with Sagas but I think the problem is that you need to call it with the context of the `Analytics` object so that `this` is not undefined.

Looking at [this docs](https://redux-saga.js.org/docs/api/#callcontext-fn-args):
```ts
yield call([Analytic, Analytic.track], 'MY_ENVENT_NAME');
// or
yield call([Analytic, 'track'], 'MY_ENVENT_NAME');
```

**Comment by mi-mazouz** [comment]
Ohh thanks!! I forgot this syntax when I use it elsewhere, sorry
