### ISSUE TITLE
Incompatible anonymous ids

### ISSUE THREAD

**Issue by RohovDmytro** [segmentio/analytics-react-native#696]
Latest segment version generates anonymous id which is not compatible with anonymous id of MixPanel.

<img width="499" alt="image" src="https://user-images.githubusercontent.com/1548235/196792907-8d255075-64ce-41c9-9ca5-624e974c02e1.png">

**Comment by jparksecurity** [comment]
I got the same error on Android and iOS. However, it happens to me only if I use `expo run` or `expo start --dev-client`.

It works on the build.

Working(build)
![Working](https://user-images.githubusercontent.com/14362029/196819218-2156cd49-23b8-4866-b6b5-48244eab92fe.png)

iOS Not working
![iOS - not working](https://user-images.githubusercontent.com/14362029/196819222-ee9d6e2c-6f9f-42df-9481-88fa3e094ce6.png)

Android Not working
![Android - not working](https://user-images.githubusercontent.com/14362029/196819224-3e9b6f90-a4ce-411d-9251-e6182b4dda10.png)

My environment is 
```
├─ @segment/analytics-react-native@2.7.1
└─ @segment/sovran-react-native@0.4.4
```

**Comment by RohovDmytro** [comment]
Yeah, the dev and release build use different mechanism of generating anonymous id. The proposal is to at least unify the format of the string.

**Comment by oscb** [comment]
Seems like we only had the DEV behavior due to an old RN bug that has already been fixed. I'll remove it in the next release.

**Comment by willdawsonme** [comment]
This change breaks the ability to use the javascript debugger. As soon as the debugger is activated, I get the aforementioned react-native error: https://github.com/facebook/react-native/issues/26705. There's some relevant discussion over at `react-native-device-info`: https://github.com/react-native-device-info/react-native-device-info/issues/776.

Is there a way to make this UUID call asynchronous so consumers can use the debugger?
