### ISSUE TITLE
Project with path ':segment_sovran-react-native' could not be found in project ':@segment_analytics-react-native'

### ISSUE THREAD

**Issue by charles-goncalves** [segmentio/analytics-react-native#699]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@segment/analytics-react-native@2.9.0` for the project I'm working on.

- `analytics-react-native` version: 1.17.10
- `sovran-react-native` version: 0.4.5
- React Native version: 0.65.1
- iOS or Android or both? Android only

## Steps to reproduce
I just followed your [Installation guide in this project's README](https://github.com/segmentio/analytics-react-native#installation). 

## Expected behavior
```shell
$ yarn config:staging && react-native run-android --appIdSuffix debug

...

BUILD SUCCESSFUL in 1m 34s
```

## Actual behavior
```shell
$ yarn config:staging && react-native run-android --appIdSuffix debug

...

Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/user/project_root/node_modules/@segment/analytics-react-native/android/build.gradle' line: 136

* What went wrong:
A problem occurred evaluating project ':@segment_analytics-react-native'.
> Project with path ':segment_sovran-react-native' could not be found in project ':@segment_analytics-react-native'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s

    at makeError (/Users/user/project_root/node_modules/execa/index.js:174:9)
    at /Users/user/project_root/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/user/project_root/node_modules/react-native/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:106:5)
    at async Command.handleAction (/Users/user/project_root/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Patch
Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@segment/analytics-react-native/android/build.gradle b/node_modules/@segment/analytics-react-native/android/build.gradle
index 852d924..ab63930 100644
--- a/node_modules/@segment/analytics-react-native/android/build.gradle
+++ b/node_modules/@segment/analytics-react-native/android/build.gradle
@@ -133,5 +133,5 @@ dependencies {
   // noinspection GradleDynamicVersion
   api 'com.facebook.react:react-native:+'
   implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
-  implementation project(path: ':segment_sovran-react-native')
+  implementation project(path: ':@segment_sovran-react-native')
 }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by charles-goncalves** [comment]
I also had to do this minor fix in the same project that i'm working on:
```diff
diff --git a/android/app/build.gradle b/android/app/build.gradle
index a9133286..8b59dba4 100755
--- a/android/app/build.gradle
+++ b/android/app/build.gradle
@@ -199,6 +199,10 @@ android {
 
         }
     }
+    
+    packagingOptions {
+       resources.excludes.add("META-INF/*")
+    }
 }
```

Without this change and after the patch related above, the installation leads to another android build failure:
```shell
error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'META-INF/-no-jdk.kotlin_module' from inputs:
      - /Users/user/project/node_modules/@segment/analytics-react-native/android/build/intermediates/library_java_res/debug/res.jar
      - /Users/user/project/node_modules/@segment/sovran-react-native/android/build/intermediates/library_java_res/debug/res.jar
     Adding a packagingOptions block may help, please refer to
     https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html
     for more information

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 43s

    at makeError (/Users/user/project/node_modules/execa/index.js:174:9)
    at /Users/user/project/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/user/project/node_modules/react-native/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:106:5)
    at async Command.handleAction (/Users/user/project/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
```
This error is related to these files in your projects:
```shell
$ du -ah ./node_modules/@segment | grep META-INF/-no-jdk.kotlin_module
4,0K    ./node_modules/@segment/sovran-react-native/android/build/tmp/kotlin-classes/debug/META-INF/-no-jdk.kotlin_module
4,0K    ./node_modules/@segment/analytics-react-native/android/build/tmp/kotlin-classes/debug/META-INF/-no-jdk.kotlin_module
```
I think that it may be useful add this in the project README, if these files are needed.

**Comment by oscb** [comment]
Thanks for the report, I'll take a look at this. Not sure if it might be related to the RN version (0.65) as there have been several fixes in newer versions that have solved issues for us. I do recommend upgrading if that's within your possibilities.

I will still check this against that version of RN to confirm

**Comment by charleyoliveira** [comment]
Yes its related with gradle version used on RN 0.65.
Upgrade gradle to 7.0 solve this problem.

**Comment by oscb** [comment]
Closing as this is related to RN 0.65

**Comment by andreacab2** [comment]
Hi there,
If it helps, it does not work either on RN 0.70 and gradle 7.5 (plugin 7.2)

**Comment by Kevinparra535** [comment]
same

**Comment by longb1997** [comment]
> same here
> 
> ```shell
> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '/Users/kevinparralopez/Documents/HEMAV/layers-frontend/packages/mobile/node_modules/@segment/sovran-react-native/android/build.gradle' line: 3
> 
> * What went wrong:
> A problem occurred evaluating project ':segment_sovran-react-native'.
> > For input string: "1.7.0"
> ```

same, do you have any solution?

**Comment by Kevinparra535** [comment]
> > same here
> > ```shell
> > FAILURE: Build failed with an exception.
> > 
> > * Where:
> > Build file '/Users/kevinparralopez/Documents/HEMAV/layers-frontend/packages/mobile/node_modules/@segment/sovran-react-native/android/build.gradle' line: 3
> > 
> > * What went wrong:
> > A problem occurred evaluating project ':segment_sovran-react-native'.
> > > For input string: "1.7.0"
> > ```
> 
> same, do you have any solution?

Downgrade the library version

**Comment by BenTimonCards** [comment]
> > > same here
> > > ```shell
> > > FAILURE: Build failed with an exception.
> > > 
> > > * Where:
> > > Build file '/Users/kevinparralopez/Documents/HEMAV/layers-frontend/packages/mobile/node_modules/@segment/sovran-react-native/android/build.gradle' line: 3
> > > 
> > > * What went wrong:
> > > A problem occurred evaluating project ':segment_sovran-react-native'.
> > > > For input string: "1.7.0"
> > > ```
> > 
> > 
> > same, do you have any solution?
> 
> Downgrade the library version

Please to what version because i am using version 1.1.3

**Comment by Kevinparra535** [comment]
I've found a temporary solution; you need to add this line to `/node_modules/@segment/analytics-react-native/android/src/main/java/com/segmentanalyticsreactnative/AnalyticsReactNativeModule.kt#L128`
```kt
    val appVersion: String = pInfo.versionName ?: "Unknown"
```

Packages Version: 
```json
    "@segment/analytics-react-native": "2.14.0",
    "@segment/sovran-react-native": "1.0.3",
    "react": "18.2.0",
    "react-native": "0.72.4",
```

> ⚠️ This only works on the Android build
