### ISSUE TITLE
Ios build is failing

### ISSUE THREAD

**Issue by acollazomayer** [segmentio/analytics-react-native#70]
I add the libraries in the coca pod And i have this error:

```
fatal error: ‘Segment-Mixpanel/SEGMixpanelIntegrationFactory.h’ file not found
#import <Segment-Mixpanel/SEGMixpanelIntegrationFactory.h>
```

**Comment by jatsrt** [comment]
This was an issue with cocoapods 1.7.0, 1.7.1 should fix.

**Comment by AmitPandya007** [comment]
Hi
My working project is react-native and I have detached it. DO I need to use pod install to resolve the error?
Suggestions will be really helpful. Thanks in advance.
