### ISSUE TITLE
Unhandled promise rejection at `flush` function

### ISSUE THREAD

**Issue by julianoabrss** [segmentio/analytics-react-native#702]
Hello folks!

I'm getting multiple error logs from time to time after setting up Segment on start up. Did a little digging and it happens at `src/analytics.ts` at the `flush` function, when it calls ` await allSettled(promises);`. I was using `2.3.2` until now and after upgrading to the latest (`2.9.1`) these errors started popping up. Went back a few versions and it happens on `2.4.0` onwards.
Do I need to upgrade more libraries or is this something happening to everyone?

``` ERROR  Unhandled promise rejection [RangeError: Maximum call stack size exceeded (native stack depth)]```

- `analytics-react-native` version: 2.9.1
- Integrations versions (if used): "@segment/sovran-react-native": "0.4.5"
- React Native version: 0.69.6
- iOS or Android or both? Just iOS

**Steps to reproduce**
Open the app and call `createClient`

**Expected behavior**
No error logs

**Actual behavior**
Multiple error logs
``` ERROR  Unhandled promise rejection [RangeError: Maximum call stack size exceeded (native stack depth)]```

**Comment by julianoabrss** [comment]
@oscb I don't, sadly

**Comment by oscb** [comment]
Ok, well that still cuts some places to check! I'll dig on this today.

**Comment by oscb** [comment]
@julianoabrss Another question, is this happening to you on device or in the simulator? Could you share the configuration of your client by any chance (sans the write key of course) ?
