### ISSUE TITLE
Failed send segment events when no connection

### ISSUE THREAD

**Issue by herparis** [segmentio/analytics-react-native#704]
- `analytics-react-native` version: 2.5.1
- React Native version: 0.68.2
- iOS or Android or both? both

**Steps to reproduce**
1 - Dispatch multiple segment events
2 - Go offline quickly after dispatching those events

**Expected behavior**
1 - Logs saying "Error: Failed to send `n` events."

**Actual behavior**
1 - Hold those events without any error display on the console and send them when the connection is on again

**Comment by oscb** [comment]
@herparis is the Expected and Actual behaviour backwards in your bug report by any chance? Are you not seeing the events getting to Segment after the connection is reestablished?

**Comment by OrLevy23** [comment]
Hey, i'm facing similar issue.
my idea is that we basically keep storing those events until a connection is restored.
I'm seeing this in debug 
<img width="399" alt="image" src="https://user-images.githubusercontent.com/21291210/204769182-9d053ae4-d409-43c0-8c93-5e5eccfa3260.png">
and I'm wondering what would happen in prod release? will it cause a crash?

**Comment by alanjcharles** [comment]
@herparis  @OrLevy23  can you folks try updating to `2.10.0` ? @oscb has updated our flush policy so it's likely this has been resolved

**Comment by oscb** [comment]
This error only happens during debug, the intention was to highlight if something's wrong if you are not able to see the events in the segment debugger online. It will disable errors in production builds, so no risk of crashing.

This is configurable too: https://github.com/segmentio/analytics-react-native/blob/b95788ba8ecb547ffc9f43ba94f628c25f3660d1/packages/core/src/types.ts#L133 
If you manually set `debug = false` in the `Config` for the client it will remove these errors. (There's also an even more thorough option with the `logger` to actually handle these with your own logic, but that might be a little bit too much for this case.)


Even though they are being logged as errors, the events are queued and stored until the connection is restored.
