### ISSUE TITLE
Duplicated Install Attributed event found in PostgreSQL destination.

### ISSUE THREAD

**Issue by chihieu0112** [segmentio/analytics-react-native#710]
So we are tracking app events and store it into PostgreSQL data warehouse 
destination. Recently we have some duplicated Install Attributed events when looking up on our PostgreSQL data warehouse (Android install event only). Only the _id_ column is different. 
![Screenshot_3](https://user-images.githubusercontent.com/56855487/202421938-7785163e-0cbf-4068-a720-b677d57265db.png)
I don't know if this problem cause by our code base, Segment or the users. There are 10% of this event was duplicated.

**Comment by oscb** [comment]
Hi @chihieu0112 

Trying to get more context about this issue:
- Did you recently upgrade from the v1 to v2 version of this library? 
- Are you using multiple analytics instances by any chance?
- Can you share your configuration and when does your analytics client get instantiated?

**Comment by chihieu0112** [comment]
Thanks for your reply @oscb 
1. Yes, we upgraded this library from v1.5.0 to v2.2.1. 
2. We are using 2 sources: mobile app and web as you can  see in the image below. For destinations, we only use 1 PostgreSQL warehouse to store the Install Attribute event. 
3. We track our app events using @segment/analytics-react-native-plugin-appsflyer. The images below is our configuration.

![image](https://user-images.githubusercontent.com/56855487/202619884-cafdcd7f-039a-4df4-b55c-c4201be7059d.png)
![image](https://user-images.githubusercontent.com/56855487/202620320-405eb3e7-0602-4788-9ed8-3b1844a7b3bc.png)

We integrated Segment SDK v2.2.0 from 2022 June 10th and deployed around early July. For v1.5.0 is from 2022 April 27th.

In case you need more information, we are not using methods from Appsflyer SDK (which is react-native-appsflyer library). Only use from the @segment/analytics-react-native-plugin-appsflyer library to capture events.

- analytics-react-native version: 2.2.1
- React Native version: 0.66.0
- iOS or Android or both? Android

**Comment by chihieu0112** [comment]
1. The React Native Production source is using to capture Install Attribute event.

![image](https://user-images.githubusercontent.com/56855487/202631000-cc294f47-58ea-4378-82da-993bc0e7d62d.png)

2. And store into Postgre Production Warehouse.

![image](https://user-images.githubusercontent.com/56855487/202631143-3ddef508-da11-426b-bb08-8efd448caabd.png)
![image](https://user-images.githubusercontent.com/56855487/202631428-f1213535-10cb-49f2-8d97-cfb51ec000f9.png)

3. We also have an UAT source, but it will only go to the UAT Postgre. Also we don't config Install Attribute on UAT.

![image](https://user-images.githubusercontent.com/56855487/202631798-a995d6aa-78fe-4263-b791-545ad6047f72.png)

**Comment by alanjcharles** [comment]
@chihieu0112 sorry to hear you're running into issues here. This investigation seems to be better suited to our support engineering friends as they have more access to data, workspace info and things of that nature. Please feel free to reach out to them at friends@segment.com. If a bug is uncovered by you or them while you work through the debugging process, they can escalate and bring it to our attention accordingly. Thanks!
