### ISSUE TITLE
Wrong device version

### ISSUE THREAD

**Issue by asen-ruuby** [segmentio/analytics-react-native#720]
- `analytics-react-native` version: 2.9.0
- React Native version: 0.67.2

Hi, I'm using version 2.9.0 and I've tested it on iPhone 11 with ios version 16.1 and that device is reported in segment as iPhone 12,1. Is there a fix of the problem and why it generally happens? 

Thanks.

**Comment by alanjcharles** [comment]
Hi @asen-ruuby sorry to hear you're running into issues. I haven't been able to replicate this, I'm afraid. Every device I have available to test with returns the right device version. If it helps, [this is the code](https://github.com/segmentio/analytics-react-native/blob/master/packages/core/ios/AnalyticsReactNative.swift#L28) that retrieves the device model directly from the system itself. I'm going to close this issue out for now as I haven't been able to replicate it. Please feel free to reach out to `friends@segment.com` for additional troubleshooting support. They will be able to take a deeper diver into your implementation to see if we can pinpoint the issue. If they do find a bug, they can escalate it directly to us as well.
