### ISSUE TITLE
Ask for information

### ISSUE THREAD

**Issue by v0lck3r** [segmentio/analytics-react-native#723]
Hello guys,

I'm a security researcher. 
While performing some tests for one of our clients, I discovered found  the API key `segmentWriteKey`. In fact, I can't just report that the key is leaked to the client without showing the impact of leaking API keys.
To do so, I would like to know more about the utility of this api key and what an attacker can do (maximum impact) if he finds this leaked somewhere!

Thanks in adavance.

**Comment by alanjcharles** [comment]
Hi @volneyvj Thanks for reaching out! 

The segment write key is considered public information- you can find it in the payload of track events on our website, for instance: 
![image](https://user-images.githubusercontent.com/50601149/205980850-fbb72317-ecde-4ed3-a5dd-6616c33dca45.png)


For more security-related information, I would recommend reaching out to friends@segment.com as they will be more suited to a longer discussion. I am going to close this out as we are attempting to limit the Github issues page to bug reports. Thanks again, best of luck!
