### ISSUE TITLE
Cannot find module '@segment/analytics-react-native-plugin-firebase' or its corresponding type declarations.

### ISSUE THREAD

**Issue by Nicktho** [segmentio/analytics-react-native#728]
It seems that the `@segment/analytics-react-native-plugin-firebase` package does not include the `lib` folder on npm which is referenced by the `main` property in it's `package.json`

- `analytics-react-native` version: 291
- Integrations versions (if used): firebase
- React Native version: 0.70.5
- iOS or Android or both?: both

**Steps to reproduce**

`npm i @segment/analytics-react-native-plugin-firebase`

somewhere in your code:
```ts
import { FirebasePlugin } from '@segment/analytics-react-native-plugin-firebase';
```

**Expected behavior**

It can find the module

**Actual behavior**
<img width="776" alt="image" src="https://user-images.githubusercontent.com/8622243/206347349-d2c64610-953e-4d6d-a12c-c63f490021ed.png">

**Comment by alanjcharles** [comment]
@Nicktho apologies, thanks for bringing this to our attention. [Fixed with 0.3.5](https://www.npmjs.com/package/@segment/analytics-react-native-plugin-firebase)
