### ISSUE TITLE
Specifying flush policies when creating a client yields warning

### ISSUE THREAD

**Issue by peterthompson** [segmentio/analytics-react-native#732]
When specifying flush policies as part of creating a segment client the app displays the following console warning,

```
Error: Exception in HostFunction: Malformed calls from JS: field sizes are different.

[[91,89,89,89,89,71,134,89],[1,1,0,1,0,1,0,0],[["{\"type\":\"log\",\"level\":\"info\",\"mode\":\"BRIDGE\",\"data\":[\"Received settings from Segment succesfully.\"]}",1],[13],[111,1000,1671101056651,false],[19],[113,1000,1671101056651,false],["appStateDidChange"],[120,2000,1671101056653,false]],1262]
Error: Exception in HostFunction: Malformed calls from JS: field sizes are different.
```

Version: 2.10.0
React Native version: 0.70.4

**Comment by oscb** [comment]
@peterthompson Can you share your client configuration?

**Comment by felippepuhle** [comment]
I faced this same problem but solved by using `addFlushPolicy` rather than passing an array of `flushPolicies` on `createClient`

**Comment by oscb** [comment]
@felippepuhle thanks for that information! That helped me pinpoint the actual issue here, will be fixed in the next release.
