### ISSUE TITLE
Segment and expo managed

### ISSUE THREAD

**Issue by ScopeSV** [segmentio/analytics-react-native#735]
Hi. 

As you don't have a discussion panel in Github, I'll send my inquiry as an issue. 

We are using Segment for our websites. We have a mobile app written with Expo Managed.
Is it possible to add this Segment package to an Expo-managed build? I can see it says "Not working in Expo Go", however, if you use a development build of an Expo-managed build - will that work?

BR
Stephan Valois

**Comment by TomasSestak** [comment]
> Hi.
> 
> As you don't have a discussion panel in Github, I'll send my inquiry as an issue.
> 
> We are using Segment for our websites. We have a mobile app written with Expo Managed. Is it possible to add this Segment package to an Expo-managed build? I can see it says "Not working in Expo Go", however, if you use a development build of an Expo-managed build - will that work?
> 
> BR Stephan Valois

yes it will: https://github.com/segmentio/analytics-react-native#expo

**Comment by oscb** [comment]
@ScopeSV yes, as mentioned it will work if you use Expo's [Custom Dev Clients](https://docs.expo.dev/development/create-development-builds/)

Expo Go won't work because it doesn't let you add custom native modules, but with EAS and Custom Dev Clients you can.
