### ISSUE TITLE
The package 'analytics-react-native' can't access a custom native module in js test 

### ISSUE THREAD

**Issue by skanwarjeet** [segmentio/analytics-react-native#738]
analytics-react-native giving me this warning when I run test on it.

```
    console.warn
      The package 'sovran-react-native' doesn't seem to be linked. Make sure: 
      
      - You have run 'pod install'
      - You rebuilt the app after installing the package
      - You are not using Expo managed workflow

```

and

```
 The package 'analytics-react-native' can't access a custom native module. Make sure: 
      
      - You have run 'pod install'
      - You rebuilt the app after installing the package
      - You are not using Expo managed workflow
```

I tried to mock it like

```
jest.mock('@segment/analytics-react-native', () => ({
  setup: jest.fn(),
  identify: jest.fn(),
  reset: jest.fn(),
}));
```
but it gives error 

`Super expression must either be null or a function`

What is the proper way to test it or create mock of it?

  [1]: https://i.stack.imgur.com/ESAmx.png

**Comment by oscb** [comment]
The methods you might need to mock depends on what methods you are calling from `@segment/analytics-react-native` in the things you're testing. The most likely is that you got stuff calling `createClient` and the `useAnalytics` hook so your mock would look like:

```
jest.mock('@segment/analytics-react-native', () => ({
  createClient: () => ({
    add: jest.fn()
  }),
  useAnalytics: () => {
    track: jest.fn(),
    identify: jest.fn(),
    reset: jest.fn(),
    group: jest.fn(),
    screen: jest.fn(),
    alias: jest.fn(),
    flush: jest.fn(),
  }),
})
```

You might require adding some additional function mocks to the object returned by `createClient` if you are using any of the more specific methods the `SegmentClient` object has, but uses cases like our example the above should be enough.

I'll make a note to add an extended version of this in the readme as an example for Jest

**Comment by soulfresh** [comment]
I had to take this a step further in order to test code that uses `<AnalyticsProvider>` so posting it here for others. I ended up creating a file that exports the segment mocks AND provider and then importing that into my `setupTests.ts` file (or you could probably combine it into one file if you use a `.tsx` extension for `setupTests`).

```tsx
// Segement.mock.tsx
import React from 'react'

const Context = React.createContext(undefined)

export default {
  // Expose a custom Provider since requiring the actual one will output console warnings
  AnalyticsProvider: ({ client, children }) => (
    <Context.Provider value={client}>{children}</Context.Provider>
  ),
  createClient: () => ({
    add: jest.fn(),
  }),
  useAnalytics: () => ({
    track: jest.fn(),
    identify: jest.fn(),
    reset: jest.fn(),
    group: jest.fn(),
    screen: jest.fn(),
    alias: jest.fn(),
    flush: jest.fn(),
  }),
}
```
```tsx
// setupTests.ts
import mockSegment from './path/to/Segment.mock.tsx'

jest.mock('@segment/analytics-react-native', () => mockSegment)
```

It's a shame there's no documentation around testing in the README
