### ISSUE TITLE
Unhandled promise rejection at every flush call

### ISSUE THREAD

**Issue by KonstantinosKoulaxizis** [segmentio/analytics-react-native#743]
Hi everyone, I'm facing an issue while I try to run my app at an Android TV emulator.
On an iOS emulator it works as expected and I haven't try to test it on a real device. There are two similar closed issues but the problem wasn't solved [#702](https://github.com/segmentio/analytics-react-native/issues/702) and [#648](https://github.com/segmentio/analytics-react-native/issues/648)

I'm able to see the events I'm tracking and everything works as expected, the only issue is the error message I'm receiving.

- `analytics-react-native` version: 2.10.1
- Integrations versions (if used): "@segment/sovran-react-native": "0.4.5"
- React Native version: 0.68.2
- iOS or Android or both? Android TV emulator

**Steps to reproduce**
Emulators used: Android TV (4K) API 33
Use one of `useAnalytics` methods and after the `flush` method is called you will receive the following error
`Unhandled promise rejection [RangeError: Maximum call stack size exceeded.]` x3

**Expected behavior**
No error logs

**Actual behavior**
Every time the flush function is called
`Unhandled promise rejection [RangeError: Maximum call stack size exceeded.]`

**Comment by KonstantinosKoulaxizis** [comment]
The problem occurs in iOS and Android mobile emulators

After some investigation I was able to find out the source of those errors. 
The function allSettled imported form `'promise.allsettled'` was throwing those errors.

A simple fix is to remove the package and use a local function instead, there is also a [PR](https://github.com/segmentio/analytics-react-native/pull/745) with my solution

**Comment by YungTosti** [comment]
Would be great if this issue can be resolved, especially since @KonstantinosKoulaxizis added a PR to it.
