### ISSUE TITLE
Unsure how to use clevertap plugin with either v1 or v2 : `The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20` 

### ISSUE THREAD

**Issue by root-ansh** [segmentio/analytics-react-native#747]
I am not sure how to initialise the clevertap's plugin in a new project. I have tried the plugin with both the new and an older version of segment and in both of these i am getting this error:
```css

FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':segment_analytics-react-native-clevertap' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.21

BUILD FAILED in 7s

    at makeError (/Users/ansh/Downloads/a_work/c_demos/ct_demo_segment_rn/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:174:9)
    at /Users/ansh/Downloads/a_work/c_demos/ct_demo_segment_rn/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/ansh/Downloads/a_work/c_demos/ct_demo_segment_rn/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:82:7)
    at async Command.handleAction (/Users/ansh/Downloads/a_work/c_demos/ct_demo_segment_rn/node_modules/@react-native-community/cli/build/index.js:108:9)
info Run CLI with --verbose flag for more details.

Process finished with exit code 1

```

upon inspecting the clevertap plugin (`v1.5.1`),  i found that it is using an older version of kotlin which might be probably causing the issue.
```css
 dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.21'
    }

```

So is there any particular combination of versions of react native, firebase libs(either via node package or added directly in android code as dependency), clevertap and segment node packages that could be added in a new project and made to successfully run ? I have tried the following respective combinations and none seems to work

- `analytics-react-native` version: `1.5.1` , `^2.10.1`
- Integrations versions (if used): `"@segment/analytics-react-native-clevertap": "1.5.1"` , `"@segment/analytics-react-native-clevertap": "^1.5.3"`
- React Native version: `"react": "18.2.0"`, `"react-native": "0.71.1"`

**Comment by alanjcharles** [comment]
@root-ansh apologies for the delay here. It is noot possible to use the Clevertap integration we had available for Analytics React Native versions 2.x and greater. However we have just released a CleverTap Destination Plugin you can use with the new library: https://www.npmjs.com/package/@segment/analytics-react-native-plugin-clevertap 

I am going to close this out for now but please feel free to open a new issue if you find any issues with the CleverTap plugin
