### ISSUE TITLE
Add option to disable data collection for users who opt out

### ISSUE THREAD

**Issue by gratian-dicu-hillrom** [segmentio/analytics-react-native#757]
## Summary
As a user i would like to have the option to enable/disable data collection. Currently this feature is not available and workarounds are needed in order to mimic this option.

## Proposed Solution
Similar to Analytics-iOS, expose 2 functions that enable and disable data forwarding to all destinations including segment.

**Comment by alanjcharles** [comment]
Hi @gratian-dicu-hillrom thanks for reaching out! We don't have any plans to add this functionality, I'm afraid. However, you can implement a consent manager to determine if/when you should collect and send events. Here is an example we have in our example app: https://github.com/segmentio/analytics-react-native/blob/master/example/src/plugins/ConsentManager.tsx 

Please feel free to reach out to friend@segment.com for additional support and/or post any other issues you might run into here and we'll respond as soon as we can. Thanks!
