### ISSUE TITLE
Segment without hooks needs globally  

### ISSUE THREAD

**Issue by RKhatri93** [segmentio/analytics-react-native#758]
Hi Team Segment,

From the below code, I understand that we can use this with the help of creating an instance of segment analytics with the help of createClient.
What if we need to call this for multiple screens? Do we need to create it again or do we've to use a global instance of createClient?

import {
  createClient,
  AnalyticsProvider,
} from '@segment/analytics-react-native';

// create the client once when the app loads
const segmentClient = createClient({
  writeKey: 'SEGMENT_API_KEY'
});

One more query is before tracking we need to call the below code everytime we need to track any event. Is there any other way to do the same? Please suggest.
segmentClient.add({ plugin: new AmplitudeSessionPlugin() });

**Comment by lalmalani** [comment]
hey @RKhatri93, here's guidance on how to use the analytics-react-native client across your entire app.
https://segment.com/blog/analytics-react-native-2-blog/

**Comment by oscb** [comment]
@RKhatri93 you an use the object you create globally. You can export it if you want to use across files.

If you want to use it for screens I would recommend using the hooks still, as you can use the example [here](https://github.com/segmentio/analytics-react-native#automatic-screen-tracking) for how to use it with the most common navigation libraries, but you can also register a `useEffect` that runs only when your screen component is created.
