### ISSUE TITLE
Unhandled error found on a production

### ISSUE THREAD

**Issue by buuuudzik** [segmentio/analytics-react-native#773]
Hey!

We're using segment library with appsFlyer plugin and recently we're found a problem that on a production we've received such errors:
```
Error Unable to resolve host "inapps.appsflyer.com": No address associated with hostname 
    node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:105:50 promiseMethodWrapper
    node_modules/react-native-appsflyer/index.js:45:8 logEventPromise
    node_modules/react-native-appsflyer/index.js:54:24 logEvent
    node_modules/@segment/analytics-react-native-plugin-appsflyer/src/methods/track.ts:26:4 _default
    node_modules/@segment/analytics-react-native-plugin-appsflyer/src/AppsflyerPlugin.tsx:73:4 track
    node_modules/@segment/analytics-react-native/src/plugin.ts:58:17 execute
    (native) call
    node_modules/@segment/analytics-react-native/src/plugin.ts:196:4 ?anon_0_
```

This specific error is probably caused by some Adblocker and it could be fixed also in AppsFlyer lib but if it's about plugins **Segment should handle possible errors when it executes .track() or other method on a plugin**. It could pass such an error to `errorHandler`.

"@segment/analytics-react-native": "2.10.1",
"@segment/analytics-react-native-plugin-appsflyer": "^0.4.0",
"@segment/analytics-react-native-plugin-idfa": "^0.5.0",
"react-native": "0.70.5",
- iOS and Android

**Steps to reproduce**
Throw an error in `plugin.execute()` method

**Expected behavior**
It should be handled by `errorHandler`

**Actual behavior**
It's unhandled.

**Comment by oscb** [comment]
We should be [catching](https://github.com/segmentio/analytics-react-native/blob/oscb/metrics/packages/core/src/timeline.ts#L104) these. Might be something in particular with the AF plugin, will check.

I'm also giving AppsFlyer a heads up about this error.

Thanks for the report.

**Comment by narliecholler** [comment]
any progress on this?
