### ISSUE TITLE
Universal link tracking using "deep link opened"

### ISSUE THREAD

**Issue by pepf** [segmentio/analytics-react-native#776]
Hey there,

I noticed a discrepancy between iOS and Android in their handling of "universal links" (ios term) / "app links" (android). Both have the purpose of converting a "trusted domain" web-style link into a path that a native app can open, and the logic to convert a "web-style" structure into a native path is well describe in for example [the react-navigation docs](https://reactnavigation.org/docs/deep-linking/).

In our case we use a appsflyer provided "domain" (to keep the issue simple I'd like to leave appsflyer out of it), which is setup as trusted domain for both ios and android to allow opening our app. It looks something like https://anyfin.onelink.me/  .

The issue I notice is that android **does** fire "deep link opened" events when opening the app through such links, while ios does not fire this event.

Versions overview:
```
    "react-native": "0.70.5",
    "@segment/analytics-react-native": "^2.12.0",
    "@segment/analytics-react-native-plugin-appsflyer": "^0.5.0",
    "@segment/analytics-react-native-plugin-firebase": "^0.3.5",
    "@segment/sovran-react-native": "^0.4.5",
    "@sentry/react-native": "^4.11.0",
```

**Steps to reproduce**
Setup universal/app links instructed in the segment readme, set trackdeeplinks to `true`.
Use a universal/app link, to open the app. Android will fire the event, the url will start with "http" to indicate its an app link. iOS does not do this.

**Expected behavior**
Either both, or none of the platforms should fire this event, to be explicit about if this is intended behavior or not. I would propose to send it for both, and perhaps adjust the event structure to clarify the difference between universal and "deep" links. Although this can be seen from the url as well.

**Actual behavior**
Android fires deep link event from the code block over here:
https://github.com/segmentio/analytics-react-native/blob/4734389dd6c9debd08f6be0b59d3192428586ed9/packages/core/src/analytics.ts#L419-L429
iOS apps never reaches this block when opening universal links.

**Alternatives explored**
I can do this myself calling it from react-navigation, but in that case I need to keep in mind that deeplinks are "auto"-tracked trough segment and only specific url structures I need to replicate logic that already exists in this codebase. So I would prefer to solve it here instead.

Example of appdelegate.m adjustment that would support universal link tracking:
```objc
// Required for universal links (if we support them)
- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity
 restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
{
  if ([userActivity.activityType isEqualToString: NSUserActivityTypeBrowsingWeb]) {
    NSURL *url = userActivity.webpageURL;
    NSDictionary *options = @{};
    [AnalyticsReactNative trackDeepLink:url withOptions:options];
  }

```

**Comment by alanjcharles** [comment]
Hi @pepf thank you for reaching out. I definitely understand the confusion here. We require additional setup for tracking [deep links on iOS for the core sdk](https://github.com/segmentio/analytics-react-native#ios-deep-link-tracking-setup). However, we rely on the `openURL()` method to track deep links on iOS so, to your point, it should be more clear in the instructions for this plugin that you'll need to access this in your `AppDelegate` as well. I'll make the change. Please let me know if you have any other questions or if there is something I've misunderstood.

**Comment by alanjcharles** [comment]
#783
