### ISSUE TITLE
Error: com.appsflyer.sdk.network

### ISSUE THREAD

**Issue by alome007** [segmentio/analytics-react-native#780]
- `analytics-react-native` version: ^2.9.0
- Integrations versions (if used): "@segment/analytics-react-native-plugin-appsflyer": "0.5.0"
- React Native version: 0.68.1
- iOS or Android or both? both

**Comment by oscb** [comment]
@alome007 could you share more of what's the error you're seeing and when does it happen?

**Comment by alome007** [comment]
<img width="616" alt="Screenshot 2023-03-10 at 18 33 16" src="https://user-images.githubusercontent.com/47638856/224383939-8cbe0a66-d254-4ab0-a457-d2239f8e1582.png">

As seen from sentry on production

**Comment by renanbronchart** [comment]
Same problem here.
- Only on iOS.
- From react-native 0.71 (No error with 0.67)

**Comment by renanbronchart** [comment]
@alanjcharles or @oscb have you got news about that?

**Comment by alanjcharles** [comment]
Hi folks- Are you still experiencing this? I am not able to reproduce on the following versions: 
 ```
    "react-native": "0.72.9",
    "react-native-appsflyer": "^6.14.3",
```
