### ISSUE TITLE
Query regarding support

### ISSUE THREAD

**Issue by mohit23x** [segmentio/analytics-react-native#784]
The readme file says that the v1 of Segment will be deprecated in favor of v2.

It also clearly mentions that the v1.5.1 and older will be deprecated, will v1.5.2 still be supported long-term?

**Comment by oscb** [comment]
@mohit23x thanks for bringing this up, we need to update the ReadMe. v1.5.2 won't be supported long-term. The only change vs 1.5.1 is a hot fix for Android. 

If you use v1.5.2 it won't stop working after v1 reaches End of Life, however we won't release any updates or plugins for it, so future versions of RN might not work with it. I strongly recommend v2 if you are just getting started.

Let me know if you have any questions or you can contact Segment Support if you need any help migrating.
