### ISSUE TITLE
Google reject app due to Policy Declaration - Data Safety Section

### ISSUE THREAD

**Issue by vikrant-k-simformsolutions** [segmentio/analytics-react-native#792]
### Your app is not compliant with Google Play Policies

Issue details

We found an issue in the following area(s):

- SPLIT_BUNDLE 5: Policy Declaration - Data Safety Section: Device Or Other IDs Data Type - Device Or Other IDs (some common examples may include Advertising ID, Android ID, IMEI, BSSID, MAC address), Possible SDKs: com.appsflyer:af-android-sdk

- SPLIT_BUNDLE 6: Policy Declaration - Data Safety Section: Device Or Other IDs Data Type - Device Or Other IDs (some common examples may include Advertising ID, Android ID, IMEI, BSSID, MAC address), Possible SDKs: com.appsflyer:af-android-sdk

- SPLIT_BUNDLE 7: Policy Declaration - Data Safety Section: Device Or Other IDs Data Type - Device Or Other IDs (some common examples may include Advertising ID, Android ID, IMEI, BSSID, MAC address), Possible SDKs: com.appsflyer:af-android-sdk

- `analytics-react-native` version: ^1.4.7
- Integrations versions (if used): "@segment/analytics-react-native-appsflyer": "^1.5.3",
- React Native version: 0.63.3
- iOS or Android or both? Android only

**Comment by alanjcharles** [comment]
Hi @vikrant-k-simformsolutions we are in the process of sunsetting Analytics React Native versions < 2.0. Is it possible to upgrade and let me know if this is still an issue?  You can find the [migration guide here](https://segment.com/docs/connections/sources/catalog/libraries/mobile/react-native/migration/). Thanks! Let me know if you run into any issues
