### ISSUE TITLE
Unable to find a specification for `sovran-react-native` depended upon by `segment-analytics-react-native`

### ISSUE THREAD

**Issue by SavageWilliam** [segmentio/analytics-react-native#794]
**Set up**
Expo development client build 

With:
```
"Expo": "47.0.0",
"@segment/analytics-react-native": "^2.13.4"
```

**Error:**
Build error using EAS:
```
Unable to find a specification for `sovran-react-native` depended upon by `segment-analytics-react-native`
```

**Comment by alanjcharles** [comment]
Hi @SavageWilliam have you added the `@segment/sovran-react-native` package as outlined in our [setup guide](https://github.com/segmentio/analytics-react-native#installation)?
