### ISSUE TITLE
Question: react-native-appboy-sdk deprecated?

### ISSUE THREAD

**Issue by TrekSoft** [segmentio/analytics-react-native#806]
I see that `react-native-appboy-sdk` is now deprecated in favor of `@braze/react-native-sdk`

However the README still says to use `react-native-appboy-sdk`

Are there any known issues with this and is there a plan to move to `@braze/react-native-sdk`?

EDIT: Also I see that in the yarn lock file it actually lists `"@braze/react-native-sdk" "^2.0.2"` as a dependency so is the README just out of date?

**Comment by alanjcharles** [comment]
Hi @TrekSoft yes, sorry about that. I'll update the readme before the next release as we have some other braze changes going out. Thanks for letting us know!

**Comment by TrekSoft** [comment]
Ok wonderful - thanks @alanjcharles!

**Comment by TrekSoft** [comment]
@alanjcharles - hmm, so it looks like `@braze/react-native-sdk` only works with React Native .68: https://github.com/braze-inc/braze-react-native-sdk/issues/193#issuecomment-1458818227

Does that mean this plugin also will only work with that version of React Native or higher as well or is there a suggested workaround to allow support below that?
