### ISSUE TITLE
Settings CDN proxy url

### ISSUE THREAD

**Issue by teejteej** [segmentio/analytics-react-native#813]
The analytics-js library supports setting a proxy not only for tracking, but also for the Settings CDN url.
Is there support for this in the analytics-react-native library as well?

Or is there some other way around this? For example, using an invalid writeKey, and then always supplying defaultSettings?
That wouldn't be the nicest way around it though.

Thanks!

**Comment by alanjcharles** [comment]
Hi @teejteej thanks for reaching out. Can I ask what your use-case is for this? We are not against it, just trying to get more context as we haven't had requests for this in react native quite yet. Thanks!

**Comment by alanjcharles** [comment]
thanks @teejteej  I'll follow up as soon as I can!

**Comment by hvardhan-unth** [comment]
Addressed in PR https://github.com/segmentio/analytics-react-native/pull/834
