### ISSUE TITLE
Missing app, device, screen info in context item

### ISSUE THREAD

**Issue by hongduclam** [segmentio/analytics-react-native#817]
- `analytics-react-native` version: latest
- Integrations versions (if used):
- React Native version: 0.71.6
- iOS or Android or both? both
- Expo: 48
**Steps to reproduce**
Running Expo project and trying to track all events. 

**Expected behavior**
Should collect app, device, and screen info in context item
**Actual behavior**
Not collect app, device, screen info in context item

![Screenshot 2023-04-21 at 2 22 29 PM](https://user-images.githubusercontent.com/9206941/233571270-38a28af6-68c1-439e-86e6-c01c02c2d819.png)

**Comment by alanjcharles** [comment]
Hi @hongduclam sorry to hear you're running into issues. It's hard to say what is happening without more information, I'm afraid. Can you reach out to `friends@segment.com`? Our support engineers are much better suited to aid in this kind of investigation. If there is a bug we need to resolve, they can escalate it with us accordingly. Thanks!

**Comment by alanjcharles** [comment]
@hongduclam this is happening because you are using an [incompatible expo framework.](https://github.com/segmentio/analytics-react-native/issues/817)
