### ISSUE TITLE
Appsflyer plugin failing

### ISSUE THREAD

**Issue by santomegonzalo** [segmentio/analytics-react-native#824]
Hi team, we are using `@segment/analytics-react-native-plugin-appsflyer` and we are getting some errors on our sentry about a `isString` function. When I look into the sourcecode my VSCode is complaining about the same issue

<img width="744" alt="Screenshot 2023-05-05 at 10 23 58" src="https://user-images.githubusercontent.com/2914973/236469841-07d6af43-a299-4c25-b617-0575dff5e501.png">

- `analytics-react-native` version: latest
- React Native version: latest
- iOS or Android or both? both

**Comment by JCaraballo113** [comment]
How did you get this to work at all? Literally doesnt even work for me :)

**Comment by oscb** [comment]
Should be fixed in the next version.
Enabling Typescript's `skipLibCheck` also helps.
