### ISSUE TITLE
BrazePlugin error: Segment client not initialising correctly

### ISSUE THREAD

**Issue by danbatsb** [segmentio/analytics-react-native#829]
Hi team

Updating the `@segment/analytics-react-native-plugin-braze` to version 0.5.3 seems to break Segment initialisation. It seems to be an issue in the `BrazePlugin` in the update function, when the `brazeSettings` are undefined. Its this line [here](https://github.com/segmentio/analytics-react-native/blob/ffdf3e00a545f4457918236ce074031cbf8b6bfd/packages/plugins/plugin-braze/src/BrazePlugin.tsx#L45) that seems to be breaking things.

If I remove the Braze plugin then Segment works fine, similarly if I update that code to check if `brazeSettings` exists then it all works fine. I've downgraded the plugin to 0.5.1 for now as that doesn't have this code and works ok.

![Screenshot 2023-05-15 at 18 29 23](https://github.com/segmentio/analytics-react-native/assets/4232372/598bddc3-9933-4b8a-ad68-90f429f01df9)

```
"@braze/react-native-sdk": "^4.1.0",
"@segment/analytics-react-native": "^2.14.0",
"@segment/analytics-react-native-plugin-braze": "0.5.3",
"@segment/sovran-react-native": "^1.0.2",
"react-native": "0.70.5"
```

**Comment by alanjcharles** [comment]
Hi @danbatsb I'm not able to replicate this. I just set up braze in our example app on the latest versions and everything seems to work as expected. Make sure you have all of the [native braze initialization setup](https://www.braze.com/docs/developer_guide/platform_integration_guides/react_native/react_sdk_setup/) as they've changed that recently. If you're still running into errors I would recommend reaching out to `friends@segment.com` for a quicker turnaround time.

**Comment by shoelessness** [comment]
+1 on this same bug. Confirmed that `0.5.1` works as expected!
