### ISSUE TITLE
Latest version of @segment/sovran-react-native is not published to NPM registry

### ISSUE THREAD

**Issue by servercimen** [segmentio/analytics-react-native#831]
The latest version of @segment/sovran-react-native (v1.0.2) which contains [this fix](https://github.com/segmentio/analytics-react-native/pull/820) isn't published to NPM registry https://www.npmjs.com/package/@segment/sovran-react-native?activeTab=readme

**Steps to reproduce**
Run: yarn add @segment/sovran-react-native

**Expected behavior**
v1.0.3 is installed

**Actual behavior**
v1.0.2 is installed

**Comment by oscb** [comment]
I just pushed the package manually. 
Thanks for letting us know, CI didn't report any errors and yet skipped NPM publish last time.
Let us know if you bump into any issues.

**Comment by efstathiosntonas** [comment]
please update the [releases page](https://github.com/segmentio/analytics-react-native/releases), this is a serious bug that costs us money.
