### ISSUE TITLE
Is this repo being maintained?

### ISSUE THREAD

**Issue by benevbright** [segmentio/analytics-react-native#84]
I'm switching from `react-native-analytics-segment-io` to this since I see some problem to get old one work with latest react-native and it's official one(thanks). 

So, I want to know this one is working well (especially with latest react-native) and it's being maintained well. I saw some issues that didn't get a response by Segment. 

Many people are using this and it's Ok?

**Comment by coffenbacher** [comment]
`Not a good sign when this goes unanswered for ~6 months...

**Comment by misterpoloy** [comment]
This library is not maintained, they din't answer the issues.
