### ISSUE TITLE
Segment not properly registering all events in the dashboard

### ISSUE THREAD

**Issue by SarathMohan7th** [segmentio/analytics-react-native#840]
**Summary:**

The segment is not properly registering all events in the dashboard even if all the events are triggered from our end through the API (api.segment.io/v1/b) in a React Native Android app.

**Additional Information:**
- @segment/analytics-react-native : "^2.13.1"
- React Native version: "^0.63.5"
- Android

**Steps to reproduce**
- Use the React Native app with "react-native" version "^0.63.5".
- Trigger events from the app using the Segment API (api.segment.io/v1/b).
- Check the Segment dashboard to see if all the events are properly registered.

**Expected Behavior:**
All events triggered from the React Native app should be properly registered and visible in the Segment dashboard.

**Actual Behavior:**
Some events are not being registered in the Segment dashboard, even though they are triggered correctly from the app through the API.
- Please refer [[Doc](https://wide-thumb-8c7.notion.site/SEGMENT-QA-Mobile-App-d1fc6f53cdf94a5f8a20401eb2a2c26c)]

**Comment by oscb** [comment]
@SarathMohan7th Sadly this is a limitation on the Segment Debugger side. It doesn't show 100% of the events processed by Segment. They are still processed by Segment, just won't show in the debugger. 

If you still have issues with it please contact friends@segment.com to get more help with the Dashboard side
