### ISSUE TITLE
AppsFlyer plugin not working

### ISSUE THREAD

**Issue by JCaraballo113** [segmentio/analytics-react-native#848]
So when I install the appsflyer plugin and do the config I am not seeing the `appsFlyerId` in my events at all and as such events fail delivery. Also seeing this error:

```
TypeError: undefined is not a function
    at extractCurrency
```

I am using expo but I believe I have done everything I need including adding the apps flyer sdk in the plugins like so:

```
plugins: [
      ['react-native-appsflyer', {}],
     
    ]
```
- `analytics-react-native` version: 2.13.4
- Integrations versions (if used):  `"react-native-appsflyer": "^6.10.3"` `@segment/analytics-react-native-plugin-appsflyer`
- React Native version: 0.71.8
- iOS or Android or both? Both

**Steps to reproduce**

Install apps flyer plugin.

**Expected behavior**
It works and events get to appsFlyer with appsFlyerId
**Actual behavior**
Not working. There is no appsFlyerId and getting an unhandled promise rejection warning.

**Comment by envisean** [comment]
@JCaraballo113 how did you end up fixing this?
