### ISSUE TITLE
An internal error occurred: , [Error: Error on Firebase Track] in expo 

### ISSUE THREAD

**Issue by BhavyaCodeAlchemy** [segmentio/analytics-react-native#849]
configure segment key :

import { FirebasePlugin } from "@segment/analytics-react-native-plugin-firebase";

const segmentClient = createClient({
  writeKey: config.SEGMENT_KEY,
});

after configure segment key i will add firebase plugin like below :

segmentClient.add({ plugin: new FirebasePlugin() });

after add FirebasePlugin to my segmentClient. i used segmentClient.track("event text") for event i got An internal error occurred: , [Error: Error on Firebase Track] Error

An internal error occurred: , [Error: Error on Firebase Track]
at node_modules/@sentry/utils/cjs/instrument.js:113:6 in logger.CONSOLE_LEVELS.forEach$argument_0
at node_modules/@segment/analytics-react-native/src/logger.ts:28:3 in Logger
at node_modules/@segment/analytics-react-native/src/analytics.ts:775:2 in SegmentClient#reportInternalError
at node_modules/@segment/analytics-react-native-plugin-firebase/src/FirebasePlugin.tsx:63:3 in FirebasePlugin

- `analytics-react-native` version:
"@segment/analytics-react-native": "^2.15.0",
    "@segment/analytics-react-native-plugin-firebase": "^0.3.9",
    "@segment/sovran-react-native": "^1.0.4",
    "@react-native-firebase/analytics": "^18.1.0",
    "@react-native-firebase/app": "^18.1.0",
    "expo": "~47.0.12",
- React Native version: 0.70.8
- iOS or Android or both? iOS

**Comment by oscb** [comment]
Is this in expo go or a managed expo build?

Expo Go does not support native modules such as Firebase is, it sounds like Firebase is crashing here possibly due to that.

I would recommend using Expo Managed Builds instead as it gives you the best of both worlds without having to eject to RN CLI.

**Comment by mj-iosdev** [comment]
@oscb This is Managed Expo build. I tried to create Development as well as Production build and it is still not able to fix this issue
