### ISSUE TITLE
Event is sometimes not showing in debugger

### ISSUE THREAD

**Issue by marygarciapepperstone** [segmentio/analytics-react-native#862]
An event is sometimes not displayed in the Debugger even though it appears to be executed (confirmed with a Logger plugin). 

In this screenshot, there are 3 events that were triggered in our app, the first two (highlighted with pink and green) are sent and showing but the latest (highlighted in red) isn't. Tried waiting for a couple of minutes and then opening and closing the app but the latest event were still missing from the debugger.

<img width="1305" alt="Screenshot 2023-07-27 at 8 57 27 PM" src="https://github.com/segmentio/analytics-react-native/assets/112386606/1db182d0-7002-407b-8feb-bc058d3bfc6a">

- `analytics-react-native` version:  ^2.14.0
- Integrations versions (if used):
- React Native version: 0.71.8
- iOS or Android or both?: only tried from iOS

**Steps to reproduce**

Segment client settings:

```
export const segmentClient = createClient({
  writeKey: SEGMENT_WRITE_KEY,
  trackAppLifecycleEvents: true,
  debug: DEV_DEBUG.CONSOLE_LOG_SEGMENT,
  flushInterval: 1,
});

segmentClient.add({ plugin: new Logger() });

```

**Expected behavior**
The event is shown in the debugger
**Actual behavior**
The event is not showing in the debugger

**Comment by sushilr** [comment]
I'm experiencing these problems as well. I see them tracked in the logs and it also says "Sent 5 events" etc but i see only 1 in the debugger (sometime none). I'm on the latest 2.15.0 and RN 0.71.11.
