### ISSUE TITLE
Tried to register two views with the same name RCTFBLoginButton

### ISSUE THREAD

**Issue by schriker** [segmentio/analytics-react-native#864]
`react-native-fbsdk-next` from `@segment/analytics-react-native-plugin-facebook-app-events` is causing conflicts. In our app we have facebook login implemented using `react-native-fbsdk-next` after installing plugin `@segment/analytics-react-native-plugin-facebook-app-events` and calling `new FacebookAppEventsPlugin()` app will crash with error: 

`Tried to register two views with the same name RCTFBLoginButton, js engine: hermes`

This is happening for both iOS and Android

![image](https://github.com/segmentio/analytics-react-native/assets/28902144/7600cd8f-ec5e-4387-b70b-1b328c7eeeb8)

- `analytics-react-native` version: 2.15.0
- `@segment/analytics-react-native-plugin-facebook-app-events`: 0.5.2
- React Native version: 0.71.12
- iOS or Android or both?: both

For workaround for now we just simply import `react-native-fbsdk-next` directly from `@segment/analytics-react-native-plugin-facebook-app-events/node_modules/react-native-fbsdk-next`

**Comment by oscb** [comment]
@schriker next release will change `react-native-fbsdk-next` to a `peerDependency`, I believe this should help in your scenario to have only 1 version of it in your app
