### ISSUE TITLE
Your app is not compliant with Google Play Policies

### ISSUE THREAD

**Issue by acmancera** [segmentio/analytics-react-native#865]
We just received that our app has been removed due to this issue:
![image](https://github.com/segmentio/analytics-react-native/assets/111389799/44a1751e-de79-49a5-900a-028a688af11f)

We're currently on the newest version of the react native package, and can't find the problem for this in the code.

- `analytics-react-native` version: 2.15.0
- Integrations versions (if used): "@segment/sovran-react-native": "1.0.4"
- React Native version: 0.71.6
- iOS or Android or both? Android

**Steps to reproduce**

Build the app using analytics-react-native version 2.15.0 and then deploy it to the Google Play Store.

**Expected behavior**

The app should be published without any problems.

**Actual behavior**

The app is rejected and/or removed from the Google Play Store because of it is not compliant with Google Play Policies.

**Comment by acmancera** [comment]
It seems this was not a problem with the SDK itself, but with our other tracks not being up to date. If anyone else gets to this issue, check that all the tracks for your app in the play store are updated before trying something else.

**Comment by pslandyl** [comment]
@acmancera How do you resolve this issue?

**Comment by pslandyl** [comment]
I have upgraded to the latest version `"2.15.0"`, but I noticed that our client initialization code sets `collectDeviceId` to `true`, does it solve this problem by removing this or setting it to `false`?

**Comment by acmancera** [comment]
In our project we actually don't have that variable set in our initialization and it's up in the Play Store today, so if you're still seeing this error that might be related.

**Comment by pslandyl** [comment]
exactly, we set that variable to true incidently. Unsettibg that just
works. Thanks
