### ISSUE TITLE
Do I need to install sovran myself?

### ISSUE THREAD

**Issue by leonardofrmello** [segmentio/analytics-react-native#870]
I needed to update my project's React-native and after this update it asked to install @segment/sovran-react-native in my project, after installing Sovran my project stopped merging the USERID into the track merging with identify.
Does anyone know why?
I can't run the project without sovran!
Now I have two problems I can't update React and to update my segment it doesn't work

When trying to run my project without Sovran it shows this error below.

android/build.gradle' line: 136
A problem occurred evaluating project ':segment_analytics-react-native'.
> Project with path ':segment_sovran-react-native' could not be found in project ':segment_analytics-react-native'.

**Comment by oscb** [comment]
@leonardofrmello you have to install `@segment/sovran-react-native` for the analytics package to work.

Can you explain more about what's happening around this:
> stopped merging the USERID into the track merging with identify.

Are you not seeing `userId` on a `track` after an `identify` ?
