### ISSUE TITLE
_logTime incorrectly uses string for iOS, should be unix timestamp (FacebookAppEvents)

### ISSUE THREAD

**Issue by esdrasetrenne** [segmentio/analytics-react-native#875]
The `_logTime` for iOS should be a unix timestamp but we are using a string which will cause all iOS app events to fail.

`@segment/analytics-react-native-plugin-facebook-app-events: 0.5.1` correctly passed `undefined` for `_logTime` which allows facebook ios sdk to set it by default. See [here](https://github.com/facebook/facebook-ios-sdk/blob/1c776c79926e5d6c06e914460206dfb0e0d78981/FBSDKCoreKit/FBSDKCoreKit/AppEvents/FBSDKAppEvents.m#L1121-L1123).

`@segment/analytics-react-native-plugin-facebook-app-events: ^0.5.2` uses an empty string which causes all iOS events to error.

Suggested fix:
The return value for the `sanitizeEvent` function [here](https://github.com/segmentio/analytics-react-native/blob/master/packages/plugins/plugin-facebook-app-events/src/FacebookAppEventsPlugin.ts#L73-L78) should either return `undefined` or the current unix time stamp on iOS

i.e.:
Unix Time Stamp:
```
  return {
    ...params,
    fb_num_items: productCount,
    // IOS requires unix timestamp or undefined
    _logTime: isIOS ? Math.floor(Date.now() / 1000) : unknownToString(logTime) ?? '',
    _appVersion: (event.context as Context).app.version,
  };
```

Undefined:
```
  return {
    ...params,
    fb_num_items: productCount,
    // IOS requires unix timestamp or undefined
    _logTime: isIOS ? undefined : unknownToString(logTime) ?? '',
    _appVersion: (event.context as Context).app.version,
  };
```

Note: I prefer the `undefined` method and letting the ios sdk handle creating the unix timestamp

In the meantime our app will probably patch this package

**Comment by oscb** [comment]
Good finding @esdrasetrenne !

I wonder if it's actually more about the bridge sending of the `_logtime` from the FBSDK Next package to native. 

The logTime should never be `undefined` as it uses the `event.timestamp` [here](https://github.com/segmentio/analytics-react-native/blob/ef0e02fcc247e722c0119e3420812d855a2fe5c1/packages/plugins/plugin-facebook-app-events/src/FacebookAppEventsPlugin.ts#L62). Which is stamped right away when the event gets created. We only have
