### ISSUE TITLE
Peer dependency issue for Firebase plugin

### ISSUE THREAD

**Issue by jacquesdev** [segmentio/analytics-react-native#880]
## Summary

I've noticed that your firebase plugin you have the baked in peer dependencies:
    "@react-native-firebase/app": "^17.3.2",
    "@react-native-firebase/analytics": "^17.3.2"

## Proposed Solution

Would it be possible to either not have that, or to upgrade to the 18? Technically it means, Firebase for my whole app is stuck at a level, which is around 6 months old, losing out on many of the improvements that have been made since then? I've just installed firebase 18.4.0, and segment is still happily sending events (at least there doesn't seem to be a dependency conflict). I've done that using --force, but it's a pain to have to that every time, especially if it's not really important

**Comment by oscb** [comment]
We pin it to a major version since new releases might break up things. But given that there's no issue happy to give it a bump.

**Comment by jacquesdev** [comment]
Thanks @oscb - would you like me to get in a PR for this?

**Comment by oscb** [comment]
@jacquesdev that would be very appreciated! latest sounds good.

**Comment by jacquesdev** [comment]
Added: https://github.com/segmentio/analytics-react-native/pull/883
