### ISSUE TITLE
Could not HEAD 'https://jcenter.bintray.com/com/segment/analytics/android/analytics/maven-metadata.xml'.

### ISSUE THREAD

**Issue by akhilsanker** [segmentio/analytics-react-native#886]
- `@segment/analytics-react-native` version:  1.5.3
- Integrations versions (if used):
- React Native version: 0.66.5
- iOS or Android or both? Android

**Steps to reproduce**
Unable to run android

**Expected behavior**
Run android successfully 

**Actual behavior**
Android run fails.

<img width="998" alt="Screenshot 2023-10-03 at 11 41 38 AM" src="https://github.com/segmentio/analytics-react-native/assets/32122016/51120489-24b2-4d45-9369-95cdf72a73b6">

**Comment by oscb** [comment]
RN v1 reached end-of-life on March 2023. We won't be able to provide more help on this one. We strongly suggest migrating to v2.

This also looks similar to this [issue](https://github.com/segmentio/analytics-react-native/issues/525), I might suggest doing a clean build with v1.5.3. Gradle cache tends to be problematic.
