### ISSUE TITLE
  crypto.getRandomValues() not supported. expo 48

### ISSUE THREAD

**Issue by Willie-Pretorius** [segmentio/analytics-react-native#891]
- `analytics-react-native` version: "@segment/analytics-react-native": "^2.17.0",
- Integrations versions (if used):
- React Native version: "react-native": "0.71.14",
- iOS or Android or both? Android.

 FAIL  __tests__/screens/login/LoginScreen.test.js
  ● Test suite failed to run

    crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported

      3 | const uuid = require("uuid");
      4 | import WebView from "react-native-webview";
    > 5 | import {createClient} from '@segment/analytics-react-native';
        | ^
      6 | import PlatformUtil from '../util/PlatformUtil';
      7 |
      8 | export default class SegmentAnalytics {

      at rng (node_modules/@segment/analytics-react-native/node_modules/uuid/dist/esm-browser/rng.js:13:13)

Others suggested they asked the person who maintains the library to import react-native-get-random-values as a dependency.

**Comment by oscb** [comment]
Sadly this is not something we have control over. But will reconsider this dependency if this is a blocker. The mantainer of `react-native-get-random-values` has to figure this one out.
