### ISSUE TITLE
Amplitude Session plugin doesnt work with Amplitude Classic mode

### ISSUE THREAD

**Issue by Ananthakr-Jupiter** [segmentio/analytics-react-native#896]
- `analytics-react-native` version: 2.16.1
- Integrations versions (if used): 0.3.3 - `@segment/analytics-react-native-plugin-amplitude-session`
- React Native version: 0.65.2
- iOS or Android or both?: Both

**Steps to reproduce**
Connect an Amplitude destination app in classic mode with new 2.x version of this library along with Amplitude session plugin

**Expected behavior**
Session property should be added in each event

**Actual behavior**
Session is not added as the event, hence not reflected in Amplitude dashboard.

**Note:**
The issue is with how the session plugin expects the value of destination to be `Actions Amplitude`(https://github.com/segmentio/analytics-react-native/blob/b3ff210f9ca66c032bb3303cc2ad2c7d8158f59a/packages/plugins/plugin-amplitudeSession/src/AmplitudeSessionPlugin.tsx) while for classic mode the name of destinations come by default as `Amplitude`.

The plugin doesn't offer any way to customize this name as well.

**Comment by alanjcharles** [comment]
Hi @Ananthakr-Jupiter apologies for the delay here. Can you confirm if this is still an issue for you so we can prioritize it accordingly? Thanks!
