### ISSUE TITLE
Problem with type export

### ISSUE THREAD

**Issue by stereodenis** [segmentio/analytics-react-native#898]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@segment/analytics-react-native@2.17.0` for the project I'm working on.

Problem with type export

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@segment/analytics-react-native/src/index.ts b/node_modules/@segment/analytics-react-native/src/index.ts
index fc29c26..79aa444 100644
--- a/node_modules/@segment/analytics-react-native/src/index.ts
+++ b/node_modules/@segment/analytics-react-native/src/index.ts
@@ -14,9 +14,7 @@ export {
 } from './util';
 export { SegmentClient } from './analytics';
 export { SegmentDestination } from './plugins/SegmentDestination';
-export {
-  CategoryConsentStatusProvider,
-  ConsentPlugin,
-} from './plugins/ConsentPlugin';
+export type { CategoryConsentStatusProvider } from './plugins/ConsentPlugin';
+export { ConsentPlugin } from './plugins/ConsentPlugin';
 export * from './flushPolicies';
 export * from './errors';
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by oscb** [comment]
Hi @stereodenis thanks for the report and for sharing a solution for it.

I'm kinda curious about what error were you getting before this patch. Is it due to a particular typescript configuration?

**Comment by oscb** [comment]
Fix is already released
