### ISSUE TITLE
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher. The following dependencies do not satisfy the required version: project ':@segment_analytics-react-native-firebase' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.0

### ISSUE THREAD

**Issue by sirajalam049** [segmentio/analytics-react-native#90]
I couldn't find the repo for segment_analytics-react-native-firebase for opening here.

Environment:
gradle:3.4.1
"@segment/analytics-react-native": "^1.1.0-beta.0",
 "@segment/analytics-react-native-firebase": "^1.1.0-beta.0",
"react": "16.8.6",
 "react-native": "0.60.4",

I'm getting the following error

`The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
The following dependencies do not satisfy the required version:
project ':@segment_analytics-react-native-firebase' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.0`

Then I opened 
@segment > analytics-react-native-firebase > build.gradle and I saw

`classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.0'`

which is supposed to be as same in @segment/analytics-react-native which is 

`classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.21'`

I can't make a PR, so temporarily changing in node_modules and expect a patch to publish soon.

**Comment by Jyrno42** [comment]
Also and issue for `@segment/analytics-react-native-amplitude`. Can't find the source either so won't be able to create a PR myself.

**Comment by vpontis** [comment]
@bsneed any thoughts on this? This is a blocker for us using this library on RN 0.60.0 which is mandatory as of this Wednesday.

Also, where can we find the repo / source code for the `@segment/analytics-react-native-amplitude` package?

**Comment by yamov** [comment]
Same problem for `@segment/analytics-react-native-mixpanel` and `@segment/analytics-react-native-google-analytics`.

**Comment by QuanticPotatoes** [comment]
Same issue with `@segment/analytics-react-native-google-analytics`.

**Comment by Jonovono** [comment]
Yup, same issue with adjust. Anyone have a solution yet? @QuanticPotatoes @yamov  @vpontis ?

**Comment by vpontis** [comment]
@Jonovono I switched to using the Expo libraries -- https://www.npmjs.com/package/expo-analytics-segment

**Comment by michaelchihuyho** [comment]
@Jonovono solution is at the bottom of the PR description. We're currently using https://github.com/ds300/patch-package to patch @segment/analytics-react-native-amplitude until this is addressed. This is what our patch looks like:

```patch
diff --git a/node_modules/@segment/analytics-react-native-amplitude/android/build.gradle b/node_modules/@segment/analytics-react-native-amplitude/android/build.gradle
index e555b14..3d034e4 100644
--- a/node_modules/@segment/analytics-react-native-amplitude/android/build.gradle
+++ b/node_modules/@segment/analytics-react-native-amplitude/android/build.gradle
@@ -8,7 +8,7 @@ buildscript {
     }
     dependencies {
         classpath 'com.android.tools.build:gradle:3.1.4'
-        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.0'
+        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.21'
     }
 }
 
```

@f2prateek this should be a simple fix but the repos in question are private, could the segment team prioritize this?

**Comment by sirajalam049** [comment]
No reply from any author. If the package is open on npm, so it should be there also for someone to contribute.

**Comment by Jyrno42** [comment]
Has anyone contacted Segments support?

**Comment by bsneed** [comment]
Hi all, I was on vacation for a bit and caught the activity here this morning.  I'll get this prioritized on our end.  Please accept my sincere apologies for the delay.

**Comment by nitinmp** [comment]
@bsneed pls get this prioritized. The progess on this repo has been really slow. We are also waiting on a few PRs to be merged like "CleverTap integration #102" from few days. Help here will be highly appreciated.

**Comment by oaosman84** [comment]
Seeing the same issue for react-native-appboy.

**Comment by MoeMamdouh** [comment]
i got this error
```
* What went wrong:
Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> More than one file was found with OS independent path 'META-INF/-no-jdk.kotlin_module'
```
