### ISSUE TITLE
Braze plugin does not successfully de-duplicate Identify calls

### ISSUE THREAD

**Issue by Jack-Gill-TH** [segmentio/analytics-react-native#907]
- `analytics-react-native` version: 2.15.0
- Integrations versions (if used): @segment/analytics-react-native-plugin-braze: 0.5.4
- React Native version: 0.68.7
- iOS or Android or both? Both

**Steps to reproduce**
Make an initial call to identify with a specific set of traits
Make a second call to identify with the same set of traits

**Expected behavior**
Identify is not forwarded to braze

**Actual behavior**
Identify is forwarded to braze

---
This is because the code that checks for a duplicate payload just performs a referential equality on the two traits objects: https://github.com/segmentio/analytics-react-native/blob/0a79010b847bd36579757442aad56242f816bdae/packages/plugins/plugin-braze/src/BrazePlugin.tsx#L92

I think it's fairly unlikely that this code will be called each time with the same object reference, so this should be updated to perform some kind of deep equality.

**Comment by oscb** [comment]
Closing. Fix is released in [v0.6.1](https://www.npmjs.com/package/@segment/analytics-react-native-plugin-braze/v/0.6.1)
