### ISSUE TITLE
Branch plugin is not working

### ISSUE THREAD

**Issue by AlessandroGasparri** [segmentio/analytics-react-native#910]
- `analytics-react-native` version: 2.17.0
- Integrations versions (if used): I'm not suer what to put here, but i'm using @segment/analytics-react-native-plugin-branch version 1.0.3
- React Native version: "0.72.4
- iOS or Android or both?: both

**Steps to reproduce**
Install the branch plugin and enable the destination.

**Expected behavior**
The plugin should be activated and sending events to branch.

**Actual behavior**
The plugin does not get activated.
Upon further investigation in your codebase it might be that the plugin does not get activated beacuse there is a mismatch between the key defined in the plugin codebase, which is `Branch` and the one received from the remote settings, which is `Branch Metrics`. Locally patching those files makes the plugin work, I can submit a PR if needed.

**Comment by hvardhan-unth** [comment]
Addressed in PR https://github.com/segmentio/analytics-react-native/pull/949
