### ISSUE TITLE
Example using MMKV as the storePersistor?

### ISSUE THREAD

**Issue by thianphat** [segmentio/analytics-react-native#911]
Does anyone have a working example of utilizing MMKV storage instead of Async Storage? Getting this error when adding MMKV storage to storePersistor

`persistor.get is not a function (it is undefined)`

![Screenshot 2024-01-11 at 1 23 22 PM](https://github.com/segmentio/analytics-react-native/assets/23284914/921a036f-2e9d-4f47-b40a-7e2a29d42d8c)

![Screenshot 2024-01-11 at 1 23 55 PM](https://github.com/segmentio/analytics-react-native/assets/23284914/53a41d95-8f22-4a18-8ca3-0c6abb282ba5)

**Comment by joeruello** [comment]
@thianphat If you're still looking for an example:

```
const storage = new MMKV({
  id: 'mycoolapp:segment',
});
const mmkvStorePersistor = {
  async get<T>(key: string) {
    try {
      const value = storage.getString(key);
      if (value !== null && value !== undefined) {
        return JSON.parse(value) as unknown as T;
      }
    } catch (e) {
      logger.error(e as Error);
    }

    return undefined;
  },
  async set<T>(key: string, value: T) {
    try {
      storage.set(key, JSON.stringify(value));
    } catch (e) {
      logger.error(e as Error);
    }
  },
};

export const segmentClient = createClient({
  writeKey: Config.SEGMENT_WRITE_KEY,
  trackAppLifecycleEvents: true,
  errorHandler: analyticsErrorCallback,
  storePersistor: mmkvStorePersistor,
})
```

**Comment by oscb** [comment]
@joeruello thanks for that great example!

@thianphat here's the interface of the `Persistor` for reference, is not a 1-to-1 match to MMKV or other storages but a simplified version of it: https://github.com/segmentio/analytics-react-native/blob/87f34e3ae318f85666ef1b8b94b5646e138bda17/packages/sovran/src/persistor/persistor.ts#L20-L31

**Comment by thianphat** [comment]
@oscb @joeruello very helpful. thank you so much!
