### ISSUE TITLE
Please add support for React Native 0.73 and Expo SDK 50

### ISSUE THREAD

**Issue by anojht** [segmentio/analytics-react-native#915]
Please add support for React Native 0.73 and Expo SDK 50 which now defaults to Java 17 for the build environment.

- `analytics-react-native` version: 2.15.0
- Integrations versions (if used): 
- React Native version: 0.73
- iOS or Android or both? both

Currently builds are failing due to Java version being pinned at 11:
<img width="1095" alt="image" src="https://github.com/segmentio/analytics-react-native/assets/21053678/7bab58bb-52a1-4ee7-92dd-b983a546b163">

**Comment by leemhenson** [comment]
Yeah, not working for me on Expo 50 either. This is what I see from `expo prebuild`:

```
expo prebuild --clean

Warning! Your git working tree is dirty.
It's recommended to commit all your changes before proceeding, so you can revert the changes made by this command if necessary.

✔ Would you like to proceed? … yes

✔ Cleared android, ios code
✔ Created native directories
✔ Updated package.json | no changes
✔ Finished prebuild
⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: Unable to find a specification for `sovran-react-native` depended upon by `segment-analytics-react-native`

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
 ```

**Comment by catodapice** [comment]
any news on this? I've RN 0.73 and still failing on Android & iOS

**Comment by naleon** [comment]
guys, do you have any due date for this update?

**Comment by Jeecabs** [comment]
In case it's helpful for anyone, I managed to resolve the Android build issues. Here's what worked for me:

I cleared the `node_modules` and `package-lock.json`, then reinstalled everything. After doing so, the builds started passing in EAS. Here are the versions of the relevant packages I used in my `package.json`:

```json
{
    "react-native": "0.73.2",
    "expo": "~50.0.6",
    "expo-random": "~13.6.0",
    "@segment/analytics-react-native": "^2.18.0",
    "@segment/sovran-react-native": "^1.1.0"
}
```

**Comment by anojht** [comment]
I can confirm clearing the lock file and the `node_modules` directory then doing an install does indeed fix the builds on EAS.

Leaving the issue open for the maintainers to review any changes needed to properly support the new SDK.

**Comment by oscb** [comment]
0.73 shouldn't require any update on the library, as per [this note on RN repo](https://github.com/react-native-community/discussions-and-proposals/issues/671) by default RN should handle the namespace part.

While it now supports Java v17 by default, supporting v11 should just be compatible with new java versions. 

I know from experience that Gradle cache is problematic after a major upgrade (either on RN or on our library) so yes, the fix should be to do a clean build. Delete grade cache, delete build. Not sure if NPM needs to be cleaned but might be required for Expo.

Doing some work to align to the new namespace change but I confirmed the lib already works without changes in the E2E 0.73 example we have in the repo.

**Comment by klam-wavefin** [comment]
iOS XCode build is still failing for me after using the latest `"@segment/sovran-react-native": "1.1.1",`, wondering if anyone else sees the same thing. I am in the middle of upgrading RN to `0.73.4`

<img width="342" alt="image" src="https://github.com/segmentio/analytics-react-native/assets/152901763/b1977a16-786a-439e-a647-fe7d4dbac97f">
