### ISSUE TITLE
Privacy Manifest?

### ISSUE THREAD

**Issue by LydGol90** [segmentio/analytics-react-native#923]
## Summary
Hi, I am looking a creating the Privacy Report for our app. I have seen that the analytics-swift SDK has a privacy manifest and that it includes collecting device id for Developer’s Advertising or Marketing. I'm not clear on whether this lib uses the analytics-swift SDK under the hood or whether it would need it's own Privacy Manifest or whether we just need to create our own Privacy Manifest based on how we use this lib? As far as I understand this lib does not collect IDFA by default and so we would not need to include Device ID in our manifest?

## Proposed Solution
Include a Privacy Manifest here and/or info about what this lib collects for developers to create their own manifest.

Many thanks for your help,
Lydia

**Comment by hvardhan-unth** [comment]
Addressed in PR https://github.com/segmentio/analytics-react-native/pull/948
