### ISSUE TITLE
Expo Go & @segment/analytics-react-native-plugin-idfa: Cannot read property 'getTrackingAuthorizationStatus' of null

### ISSUE THREAD

**Issue by 0xPT** [segmentio/analytics-react-native#928]
Hi, I'm using Expo Go in development, and I'm having no problems with the @segment/analytics-react-native by itself, but I am running into an issue with the IDFA plugin for it. I'm getting this error when importing it: `TypeError: Cannot read property 'getTrackingAuthorizationStatus' of null, js engine: hermes`. I'm able to get around it by using a dynamic import, based on if it's in Expo Go or not, but that seems incorrect.

- `analytics-react-native` version: ^2.19.1
- Integrations versions (if used): @segment/analytics-react-native-plugin-idfa
- React Native version: 0.73.4
- iOS or Android or both? iOS

**Steps to reproduce**
1. Import @segment/analytics-react-native
2. Import @segment/analytics-react-native-plugin-idfa
3. Should crash

**Expected behavior**
I would expect either a warning or the error to be handled gracefully to allow for Expo Go development.

**Actual behavior**
I get a full TypeError that causes the app to not be able to load.

**Comment by oscb** [comment]
Right now we don't have support for Expo Go, specially with plugins as they require native modules. I suggest for your dev builds you conditionally add plugins only when not running in expo go mode: 

```
const isRunningInExpoGo = Constants.appOwnership === 'expo'

if (!isRunningInExpoGo) {
  client.add({plugin: IDFA) 
}
```
