### ISSUE TITLE
track() ignores undefined properties

### ISSUE THREAD

**Issue by matt-way** [segmentio/analytics-react-native#94]
We ran into an annoying debugging issue where the properties sent via `analytics.track(name, properties)` were not showing up. It seems the lib must ignore any key that has an undefined value. I think it makes a lot more sense to provide the properties, even if the values provided are undefined, and this could be valid tracking information (also would help catch bugs).

For example:

```
// someKey should still show up in properties.
analytics.track('myEvent', { someKey: undefined })
```

**Comment by rlopezapplaudo** [comment]
The only available types are defined over on brige.ts
export type JsonValue = boolean | number | string | null | JsonList | JsonMap

The current behavior is actually in line with how JSON values are handled in JavaScript:
JSON.stringify({ a:1, b:undefined, c:2 }) produces {"a":1,"c":2}

{a: undefined} is often used as a construct to ignore a JSON key.
If you need "a=" then '' seems to be semantically good enough.
