### ISSUE TITLE
React Native Android.

### ISSUE THREAD

**Issue by BabarLW** [segmentio/analytics-react-native#957]
Getting this error any one knows how to resolve this issue.

Versions: 
 "react-native": "0.72.1",
 "@segment/analytics-react-native": "^2.15.0",
 "@segment/analytics-react-native-plugin-firebase": "^0.4.1",
 "@segment/sovran-react-native": "^1.0.4"

error Failed to install the app. Command failed with exit code 1: ./gradlew app:installStagingDebug -PreactNativeDevServerPort=8081
ERROR:D8: com.android.tools.r8.kotlin.H FAILURE: Build failed with an exception. * What went wrong:
Execution failed for task ':app:mergeExtDexStagingDebug'.
> Could not resolve all files for configuration ':app:stagingDebugRuntimeClasspath'. > Failed to transform play-services-measurement-api-22.0.1.aar (com.google.android.gms:play-services-measurement-api:22.0.1) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}. > Execution failed for DexingWithClasspathTransform: /Users/daniyal/.gradle/caches/transforms-3/fce79546c9af2d256829ae51e049b9cf/transformed/jetified-play-services-measurement-api-22.0.1-runtime.jar. > Error while dexing. > Failed to transform play-services-measurement-api-22.0.1.aar (com.google.android.gms:play-services-measurement-api:22.0.1) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.status=release, org.gradle.usage=java-runtime}. > Execution failed for DexingWithClasspathTransform: /Users/daniyal/.gradle/caches/transforms-3/fce79546c9af2d256829ae51e049b9cf/transformed/jetified-play-services-measurement-api-22.0.1-runtime.jar. > Error while dexing. * Try:
> Run with --stacktrace option to get the stack trace.

**Comment by hvardhan-unth** [comment]
Hey @BabarLW 
This issue is not reproducible at my end. Issue is not with the analytics-react-native library.
If you are not satisfied with this and wants further investigation then you can reach out to our support team at (mailto:friends@segment.com).
If needed you can reopen the issue.
