### ISSUE TITLE
Mixpanel - Missing increment properties method

### ISSUE THREAD

**Issue by youssdevx** [segmentio/analytics-react-native#958]
"@segment/analytics-react-native": "^2.19.2",
"@segment/analytics-react-native-plugin-mixpanel": "^0.4.0",

**Issue**

I want to use the increment properties feature with Mixpanel.
However, I could not find any information on how to do that in React Native.
Moreover, I can see that the Mixpanel plugin only proposes identify, track, screen, group and alias methods in `/node_modules/@segment/analytics-react-native-plugin-mixpanel/src/MixpanelPlugin.ts`

Is there any way to do this using Segment?

FYI
- Mixpanel doc : https://docs.mixpanel.com/docs/tracking-methods/sdks/react-native#incrementing-numeric-properties
- https://segment.com/docs/connections/destinations/catalog/actions-mixpanel/#increment-properties

Thanks for your help

**Comment by hvardhan-unth** [comment]
Hi @youssdevx, 
The Mixpanel plugin in the analytics-react-native library doesn't expose any method such as track, screen, etc, it just check the type of event received and then calls the appropriate method for that event from the https://github.com/mixpanel/mixpanel-react-native SDK. Therefore, you can import the mixpanel-react-native SDK and use the corresponding function from it for increment property.
