### ISSUE TITLE
Upgrade Kotlin Version for Flurry

### ISSUE THREAD

**Issue by buchereli** [segmentio/analytics-react-native#97]
```
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.0'
    }
```

The Flurry integration causes issues with using Android Gradle plugin version `3.4.2`. Upgrading from `1.3.0` to `1.3.21` fixes the issue with the enforced minimum and matches the kotlin version used by the main segment package. This issue is forcing me to use Android Gradle plugin version `3.3`.

**Comment by markunmind** [comment]
There is a PR here to fix this issue as we also couldn't get Detox to run on tests on Android with the Segment library: https://github.com/segmentio/analytics-react-native/pull/115
