### ISSUE TITLE
Queue timeout before completed restoration

### ISSUE THREAD

**Issue by zgordon02** [segmentio/analytics-react-native#973]
- `analytics-react-native` version:
^2.19.2
- Integrations versions (if used):
N/A
- React Native version:
0.72.1 AND 0.74.3
- iOS or Android or both?
BOTH

![Screenshot 2024-07-10 at 1 04 04 PM](https://github.com/segmentio/analytics-react-native/assets/90853783/071b8be9-6834-4af7-aa8d-026512fe0252)

**Steps to reproduce**
Send various screen and track events

Here is an example screen event I am sending:
`SCREEN event saved {"name": "TEST_SCREEN", "properties": {"_environment": "LOCAL", "_otaVersion": "N/A"}, "type": "screen"}`

**Expected behavior**
No warning
**Actual behavior**
This warning appears multiple times per session. However, the events are shown properly in the segment console

**Comment by zgordon02** [comment]
Important to note that I have left almost all options to their default:

```
    segmentClient.current = createClient({
      writeKey: environment?.segmentKey,
      trackAppLifecycleEvents: true,
    });
```

**Comment by mayfairr** [comment]
++ Also getting this.

**Comment by umairmaqbool3** [comment]
I am also getting same warnings... 
![checkerror](https://github.com/user-attachments/assets/a3f50e5d-16fd-49d4-b8f7-e482cf855a53)

**Comment by mcoeur** [comment]
Same here with version 2.19.2.
Adding a comment to get notifications on this thread 👌

**Comment by seanadkinson** [comment]
Also seeing these warnings spewed in my console.

**Comment by MarkKravchuk** [comment]
Same here, any ideas how to suppress or silence these warnings?

**Comment by zgordon02** [comment]
> Same here, any ideas how to suppress or silence these warnings?

I have not tried this, but the code should be something like this:

```
import { LogBox } from 'react-native';
// ...
LogBox.ignoreLogs(["An internal error occurred: Error: Queue timeout before completed restoration"]);

```

**Comment by leethree** [comment]
I think this is caused by this recent change https://github.com/segmentio/analytics-react-native/pull/943

The QueueFlushingPlugin has a default timeout of 500ms and it will fail if it's not intialized within that time. But in our testing it sometimes takes 2 seconds for the entire thing to be ready. So it will block every events from being sent.

**Comment by zgordon02** [comment]
> So it will block every events from being sent.

FWIW I have not noticed events dropped while seeing this warning. It appears to be functioning normally

**Comment by CoryWritesCode** [comment]
also seeing this after upgrading

**Comment by itajenglish** [comment]
+ 1

**Comment by DAVIS-PYTH** [comment]
Commenting to get updated

**Comment by gesturetaj** [comment]
I think this has been fixed in the last release. I no longer these warnings anymore after updating.

**Comment by itajenglish** [comment]
I think this has been fixed in the last release. I no longer these warnings anymore after updating.

**Comment by DAVIS-PYTH** [comment]
Thanks @itajenglish 

installing version 2.19.4 fixed this for me.

PS: I reached out on LinkedIn

**Comment by zgordon02** [comment]
Seeing that others have mentioned it's fixed in the latest release, I'm closing this issue.

**Comment by dhatGuy** [comment]
It might be related. After upgrading to 2.19.4, I keep getting this in the log
```
INFO Flush triggered but queue restoration and settings loading not complete. Flush will be retried.
```
![image](https://github.com/user-attachments/assets/bf3421fe-45bd-46d1-8f03-df90cc2c7656)

**Comment by DAVIS-PYTH** [comment]
same here with @dhatGuy

**Comment by zgordon02** [comment]
@dhatGuy I could repoen this issue, but that warnings may be unrelated to this one. Can you create a new issue?

**Comment by dhatGuy** [comment]
> @dhatGuy I could repoen this issue, but that warning may be unrelated to this one. Can you create a new issue?

Yes, I have
https://github.com/segmentio/analytics-react-native/issues/989
